// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: coral/colony/v1/colony.proto

package colonyv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	v11 "github.com/coral-mesh/coral/coral/agent/v1"
	v1 "github.com/coral-mesh/coral/coral/mesh/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_coral_colony_v1_colony_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_colony_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_colony_proto_rawDescGZIP(), []int{0}
}

type GetStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Colony identifier.
	ColonyId string `protobuf:"bytes,1,opt,name=colony_id,json=colonyId,proto3" json:"colony_id,omitempty"`
	// Application name.
	AppName string `protobuf:"bytes,2,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	// Environment (e.g., "production", "staging").
	Environment string `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"`
	// Status ("running", "degraded", "unhealthy").
	Status string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	// When the colony started.
	StartedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// Uptime in seconds.
	UptimeSeconds int64 `protobuf:"varint,6,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	// Number of connected agents.
	AgentCount int32 `protobuf:"varint,7,opt,name=agent_count,json=agentCount,proto3" json:"agent_count,omitempty"`
	// Dashboard URL.
	DashboardUrl string `protobuf:"bytes,8,opt,name=dashboard_url,json=dashboardUrl,proto3" json:"dashboard_url,omitempty"`
	// Storage size in bytes.
	StorageBytes int64 `protobuf:"varint,9,opt,name=storage_bytes,json=storageBytes,proto3" json:"storage_bytes,omitempty"`
	// Network endpoint information.
	// WireGuard listen port (UDP).
	WireguardPort int32 `protobuf:"varint,10,opt,name=wireguard_port,json=wireguardPort,proto3" json:"wireguard_port,omitempty"`
	// WireGuard public key.
	WireguardPublicKey string `protobuf:"bytes,11,opt,name=wireguard_public_key,json=wireguardPublicKey,proto3" json:"wireguard_public_key,omitempty"`
	// WireGuard registered endpoints (e.g., ":51820").
	WireguardEndpoints []string `protobuf:"bytes,12,rep,name=wireguard_endpoints,json=wireguardEndpoints,proto3" json:"wireguard_endpoints,omitempty"`
	// Buf Connect service port (TCP).
	ConnectPort int32 `protobuf:"varint,13,opt,name=connect_port,json=connectPort,proto3" json:"connect_port,omitempty"`
	// Colony mesh IPv4 address.
	MeshIpv4 string `protobuf:"bytes,14,opt,name=mesh_ipv4,json=meshIpv4,proto3" json:"mesh_ipv4,omitempty"`
	// Colony mesh IPv6 address.
	MeshIpv6 string `protobuf:"bytes,15,opt,name=mesh_ipv6,json=meshIpv6,proto3" json:"mesh_ipv6,omitempty"`
	// Number of active agents.
	ActiveAgentCount int32 `protobuf:"varint,16,opt,name=active_agent_count,json=activeAgentCount,proto3" json:"active_agent_count,omitempty"`
	// Number of degraded agents.
	DegradedAgentCount int32 `protobuf:"varint,17,opt,name=degraded_agent_count,json=degradedAgentCount,proto3" json:"degraded_agent_count,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_coral_colony_v1_colony_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_colony_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_colony_proto_rawDescGZIP(), []int{1}
}

func (x *GetStatusResponse) GetColonyId() string {
	if x != nil {
		return x.ColonyId
	}
	return ""
}

func (x *GetStatusResponse) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *GetStatusResponse) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *GetStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetStatusResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *GetStatusResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *GetStatusResponse) GetAgentCount() int32 {
	if x != nil {
		return x.AgentCount
	}
	return 0
}

func (x *GetStatusResponse) GetDashboardUrl() string {
	if x != nil {
		return x.DashboardUrl
	}
	return ""
}

func (x *GetStatusResponse) GetStorageBytes() int64 {
	if x != nil {
		return x.StorageBytes
	}
	return 0
}

func (x *GetStatusResponse) GetWireguardPort() int32 {
	if x != nil {
		return x.WireguardPort
	}
	return 0
}

func (x *GetStatusResponse) GetWireguardPublicKey() string {
	if x != nil {
		return x.WireguardPublicKey
	}
	return ""
}

func (x *GetStatusResponse) GetWireguardEndpoints() []string {
	if x != nil {
		return x.WireguardEndpoints
	}
	return nil
}

func (x *GetStatusResponse) GetConnectPort() int32 {
	if x != nil {
		return x.ConnectPort
	}
	return 0
}

func (x *GetStatusResponse) GetMeshIpv4() string {
	if x != nil {
		return x.MeshIpv4
	}
	return ""
}

func (x *GetStatusResponse) GetMeshIpv6() string {
	if x != nil {
		return x.MeshIpv6
	}
	return ""
}

func (x *GetStatusResponse) GetActiveAgentCount() int32 {
	if x != nil {
		return x.ActiveAgentCount
	}
	return 0
}

func (x *GetStatusResponse) GetDegradedAgentCount() int32 {
	if x != nil {
		return x.DegradedAgentCount
	}
	return 0
}

type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_coral_colony_v1_colony_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_colony_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_colony_proto_rawDescGZIP(), []int{2}
}

type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*Agent               `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_coral_colony_v1_colony_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_colony_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_colony_proto_rawDescGZIP(), []int{3}
}

func (x *ListAgentsResponse) GetAgents() []*Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

type Agent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent identifier.
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// DEPRECATED: Component name (single-service mode).
	// Use 'services' field for multi-service agents.
	//
	// Deprecated: Marked as deprecated in coral/colony/v1/colony.proto.
	ComponentName string `protobuf:"bytes,2,opt,name=component_name,json=componentName,proto3" json:"component_name,omitempty"`
	// Mesh IPv4 address.
	MeshIpv4 string `protobuf:"bytes,3,opt,name=mesh_ipv4,json=meshIpv4,proto3" json:"mesh_ipv4,omitempty"`
	// Mesh IPv6 address.
	MeshIpv6 string `protobuf:"bytes,4,opt,name=mesh_ipv6,json=meshIpv6,proto3" json:"mesh_ipv6,omitempty"`
	// Last seen timestamp.
	LastSeen *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	// Status ("healthy", "degraded", "unhealthy").
	Status string `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	// Services monitored by this agent (RFD 011).
	Services []*v1.ServiceInfo `protobuf:"bytes,7,rep,name=services,proto3" json:"services,omitempty"`
	// NEW: Runtime context (RFD 018).
	RuntimeContext *v11.RuntimeContextResponse `protobuf:"bytes,8,opt,name=runtime_context,json=runtimeContext,proto3" json:"runtime_context,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Agent) Reset() {
	*x = Agent{}
	mi := &file_coral_colony_v1_colony_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_colony_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_colony_proto_rawDescGZIP(), []int{4}
}

func (x *Agent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// Deprecated: Marked as deprecated in coral/colony/v1/colony.proto.
func (x *Agent) GetComponentName() string {
	if x != nil {
		return x.ComponentName
	}
	return ""
}

func (x *Agent) GetMeshIpv4() string {
	if x != nil {
		return x.MeshIpv4
	}
	return ""
}

func (x *Agent) GetMeshIpv6() string {
	if x != nil {
		return x.MeshIpv6
	}
	return ""
}

func (x *Agent) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *Agent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Agent) GetServices() []*v1.ServiceInfo {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *Agent) GetRuntimeContext() *v11.RuntimeContextResponse {
	if x != nil {
		return x.RuntimeContext
	}
	return nil
}

type GetTopologyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopologyRequest) Reset() {
	*x = GetTopologyRequest{}
	mi := &file_coral_colony_v1_colony_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopologyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopologyRequest) ProtoMessage() {}

func (x *GetTopologyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_colony_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopologyRequest.ProtoReflect.Descriptor instead.
func (*GetTopologyRequest) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_colony_proto_rawDescGZIP(), []int{5}
}

type GetTopologyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Colony identifier.
	ColonyId string `protobuf:"bytes,1,opt,name=colony_id,json=colonyId,proto3" json:"colony_id,omitempty"`
	// List of agents.
	Agents []*Agent `protobuf:"bytes,2,rep,name=agents,proto3" json:"agents,omitempty"`
	// List of connections between components.
	Connections   []*Connection `protobuf:"bytes,3,rep,name=connections,proto3" json:"connections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopologyResponse) Reset() {
	*x = GetTopologyResponse{}
	mi := &file_coral_colony_v1_colony_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopologyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopologyResponse) ProtoMessage() {}

func (x *GetTopologyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_colony_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopologyResponse.ProtoReflect.Descriptor instead.
func (*GetTopologyResponse) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_colony_proto_rawDescGZIP(), []int{6}
}

func (x *GetTopologyResponse) GetColonyId() string {
	if x != nil {
		return x.ColonyId
	}
	return ""
}

func (x *GetTopologyResponse) GetAgents() []*Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

func (x *GetTopologyResponse) GetConnections() []*Connection {
	if x != nil {
		return x.Connections
	}
	return nil
}

type Connection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Source component ID.
	SourceId string `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	// Target component ID.
	TargetId string `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	// Connection type ("http", "grpc", "database", etc.).
	ConnectionType string `protobuf:"bytes,3,opt,name=connection_type,json=connectionType,proto3" json:"connection_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Connection) Reset() {
	*x = Connection{}
	mi := &file_coral_colony_v1_colony_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connection) ProtoMessage() {}

func (x *Connection) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_colony_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connection.ProtoReflect.Descriptor instead.
func (*Connection) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_colony_proto_rawDescGZIP(), []int{7}
}

func (x *Connection) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *Connection) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *Connection) GetConnectionType() string {
	if x != nil {
		return x.ConnectionType
	}
	return ""
}

// RequestCertificateRequest requests a client certificate using a bootstrap token.
type RequestCertificateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bootstrap token (JWT).
	Jwt string `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	// Certificate signing request (PEM-encoded).
	Csr           []byte `protobuf:"bytes,2,opt,name=csr,proto3" json:"csr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestCertificateRequest) Reset() {
	*x = RequestCertificateRequest{}
	mi := &file_coral_colony_v1_colony_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestCertificateRequest) ProtoMessage() {}

func (x *RequestCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_colony_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestCertificateRequest.ProtoReflect.Descriptor instead.
func (*RequestCertificateRequest) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_colony_proto_rawDescGZIP(), []int{8}
}

func (x *RequestCertificateRequest) GetJwt() string {
	if x != nil {
		return x.Jwt
	}
	return ""
}

func (x *RequestCertificateRequest) GetCsr() []byte {
	if x != nil {
		return x.Csr
	}
	return nil
}

// RequestCertificateResponse returns the issued certificate.
type RequestCertificateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Client certificate (PEM-encoded).
	Certificate []byte `protobuf:"bytes,1,opt,name=certificate,proto3" json:"certificate,omitempty"`
	// CA certificate chain (PEM-encoded).
	CaChain []byte `protobuf:"bytes,2,opt,name=ca_chain,json=caChain,proto3" json:"ca_chain,omitempty"`
	// Certificate expiration timestamp (Unix seconds).
	ExpiresAt     int64 `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestCertificateResponse) Reset() {
	*x = RequestCertificateResponse{}
	mi := &file_coral_colony_v1_colony_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestCertificateResponse) ProtoMessage() {}

func (x *RequestCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_colony_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestCertificateResponse.ProtoReflect.Descriptor instead.
func (*RequestCertificateResponse) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_colony_proto_rawDescGZIP(), []int{9}
}

func (x *RequestCertificateResponse) GetCertificate() []byte {
	if x != nil {
		return x.Certificate
	}
	return nil
}

func (x *RequestCertificateResponse) GetCaChain() []byte {
	if x != nil {
		return x.CaChain
	}
	return nil
}

func (x *RequestCertificateResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

// RevokeCertificateRequest revokes a previously issued certificate.
type RevokeCertificateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Certificate serial number.
	SerialNumber string `protobuf:"bytes,1,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	// Revocation reason.
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeCertificateRequest) Reset() {
	*x = RevokeCertificateRequest{}
	mi := &file_coral_colony_v1_colony_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeCertificateRequest) ProtoMessage() {}

func (x *RevokeCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_colony_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeCertificateRequest.ProtoReflect.Descriptor instead.
func (*RevokeCertificateRequest) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_colony_proto_rawDescGZIP(), []int{10}
}

func (x *RevokeCertificateRequest) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *RevokeCertificateRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// RevokeCertificateResponse confirms certificate revocation.
type RevokeCertificateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Revocation successful.
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeCertificateResponse) Reset() {
	*x = RevokeCertificateResponse{}
	mi := &file_coral_colony_v1_colony_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeCertificateResponse) ProtoMessage() {}

func (x *RevokeCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_colony_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeCertificateResponse.ProtoReflect.Descriptor instead.
func (*RevokeCertificateResponse) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_colony_proto_rawDescGZIP(), []int{11}
}

func (x *RevokeCertificateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type QueryUnifiedSummaryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: specific service or all services.
	Service string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	// Time range (e.g., "5m", "1h").
	TimeRange     string `protobuf:"bytes,2,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryUnifiedSummaryRequest) Reset() {
	*x = QueryUnifiedSummaryRequest{}
	mi := &file_coral_colony_v1_colony_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUnifiedSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUnifiedSummaryRequest) ProtoMessage() {}

func (x *QueryUnifiedSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_colony_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUnifiedSummaryRequest.ProtoReflect.Descriptor instead.
func (*QueryUnifiedSummaryRequest) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_colony_proto_rawDescGZIP(), []int{12}
}

func (x *QueryUnifiedSummaryRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *QueryUnifiedSummaryRequest) GetTimeRange() string {
	if x != nil {
		return x.TimeRange
	}
	return ""
}

type UnifiedSummaryResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Service name.
	ServiceName string `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	// Health status: healthy, degraded, critical.
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// Total requests/spans.
	RequestCount int64 `protobuf:"varint,3,opt,name=request_count,json=requestCount,proto3" json:"request_count,omitempty"`
	// Error rate as percentage (0-100).
	ErrorRate float64 `protobuf:"fixed64,4,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"`
	// Average latency in milliseconds.
	AvgLatencyMs float64 `protobuf:"fixed64,5,opt,name=avg_latency_ms,json=avgLatencyMs,proto3" json:"avg_latency_ms,omitempty"`
	// Data source: eBPF, OTLP, or eBPF+OTLP.
	Source string `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	// Issues detected (human-readable descriptions).
	Issues []string `protobuf:"bytes,7,rep,name=issues,proto3" json:"issues,omitempty"`
	// Host resources (RFD 071).
	HostCpuUtilization    float64 `protobuf:"fixed64,8,opt,name=host_cpu_utilization,json=hostCpuUtilization,proto3" json:"host_cpu_utilization,omitempty"`            // CPU utilization percentage (max in time window)
	HostCpuUtilizationAvg float64 `protobuf:"fixed64,9,opt,name=host_cpu_utilization_avg,json=hostCpuUtilizationAvg,proto3" json:"host_cpu_utilization_avg,omitempty"` // CPU utilization percentage (average in time window)
	HostMemoryUsageGb     float64 `protobuf:"fixed64,10,opt,name=host_memory_usage_gb,json=hostMemoryUsageGb,proto3" json:"host_memory_usage_gb,omitempty"`            // Memory usage in GB (max in time window)
	HostMemoryLimitGb     float64 `protobuf:"fixed64,11,opt,name=host_memory_limit_gb,json=hostMemoryLimitGb,proto3" json:"host_memory_limit_gb,omitempty"`            // Memory limit in GB
	HostMemoryUtilization float64 `protobuf:"fixed64,12,opt,name=host_memory_utilization,json=hostMemoryUtilization,proto3" json:"host_memory_utilization,omitempty"`  // Memory utilization percentage (max in time window)
	AgentId               string  `protobuf:"bytes,13,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`                                                // Agent ID for correlation
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UnifiedSummaryResult) Reset() {
	*x = UnifiedSummaryResult{}
	mi := &file_coral_colony_v1_colony_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnifiedSummaryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnifiedSummaryResult) ProtoMessage() {}

func (x *UnifiedSummaryResult) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_colony_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnifiedSummaryResult.ProtoReflect.Descriptor instead.
func (*UnifiedSummaryResult) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_colony_proto_rawDescGZIP(), []int{13}
}

func (x *UnifiedSummaryResult) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *UnifiedSummaryResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UnifiedSummaryResult) GetRequestCount() int64 {
	if x != nil {
		return x.RequestCount
	}
	return 0
}

func (x *UnifiedSummaryResult) GetErrorRate() float64 {
	if x != nil {
		return x.ErrorRate
	}
	return 0
}

func (x *UnifiedSummaryResult) GetAvgLatencyMs() float64 {
	if x != nil {
		return x.AvgLatencyMs
	}
	return 0
}

func (x *UnifiedSummaryResult) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *UnifiedSummaryResult) GetIssues() []string {
	if x != nil {
		return x.Issues
	}
	return nil
}

func (x *UnifiedSummaryResult) GetHostCpuUtilization() float64 {
	if x != nil {
		return x.HostCpuUtilization
	}
	return 0
}

func (x *UnifiedSummaryResult) GetHostCpuUtilizationAvg() float64 {
	if x != nil {
		return x.HostCpuUtilizationAvg
	}
	return 0
}

func (x *UnifiedSummaryResult) GetHostMemoryUsageGb() float64 {
	if x != nil {
		return x.HostMemoryUsageGb
	}
	return 0
}

func (x *UnifiedSummaryResult) GetHostMemoryLimitGb() float64 {
	if x != nil {
		return x.HostMemoryLimitGb
	}
	return 0
}

func (x *UnifiedSummaryResult) GetHostMemoryUtilization() float64 {
	if x != nil {
		return x.HostMemoryUtilization
	}
	return 0
}

func (x *UnifiedSummaryResult) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type QueryUnifiedSummaryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Structured summary results.
	Summaries     []*UnifiedSummaryResult `protobuf:"bytes,1,rep,name=summaries,proto3" json:"summaries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryUnifiedSummaryResponse) Reset() {
	*x = QueryUnifiedSummaryResponse{}
	mi := &file_coral_colony_v1_colony_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUnifiedSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUnifiedSummaryResponse) ProtoMessage() {}

func (x *QueryUnifiedSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_colony_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUnifiedSummaryResponse.ProtoReflect.Descriptor instead.
func (*QueryUnifiedSummaryResponse) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_colony_proto_rawDescGZIP(), []int{14}
}

func (x *QueryUnifiedSummaryResponse) GetSummaries() []*UnifiedSummaryResult {
	if x != nil {
		return x.Summaries
	}
	return nil
}

type QueryUnifiedTracesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: filter by service.
	Service string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	// Time range (default: "1h").
	TimeRange string `protobuf:"bytes,2,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	// Optional: ebpf|telemetry|all (default: all).
	Source string `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	// Optional: specific trace ID.
	TraceId string `protobuf:"bytes,4,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// Optional: filter slow traces (milliseconds).
	MinDurationMs int32 `protobuf:"varint,5,opt,name=min_duration_ms,json=minDurationMs,proto3" json:"min_duration_ms,omitempty"`
	// Maximum traces to return.
	MaxTraces     int32 `protobuf:"varint,6,opt,name=max_traces,json=maxTraces,proto3" json:"max_traces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryUnifiedTracesRequest) Reset() {
	*x = QueryUnifiedTracesRequest{}
	mi := &file_coral_colony_v1_colony_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUnifiedTracesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUnifiedTracesRequest) ProtoMessage() {}

func (x *QueryUnifiedTracesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_colony_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUnifiedTracesRequest.ProtoReflect.Descriptor instead.
func (*QueryUnifiedTracesRequest) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_colony_proto_rawDescGZIP(), []int{15}
}

func (x *QueryUnifiedTracesRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *QueryUnifiedTracesRequest) GetTimeRange() string {
	if x != nil {
		return x.TimeRange
	}
	return ""
}

func (x *QueryUnifiedTracesRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *QueryUnifiedTracesRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *QueryUnifiedTracesRequest) GetMinDurationMs() int32 {
	if x != nil {
		return x.MinDurationMs
	}
	return 0
}

func (x *QueryUnifiedTracesRequest) GetMaxTraces() int32 {
	if x != nil {
		return x.MaxTraces
	}
	return 0
}

type QueryUnifiedTracesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Structured trace spans (eBPF + OTLP).
	Spans []*v11.EbpfTraceSpan `protobuf:"bytes,1,rep,name=spans,proto3" json:"spans,omitempty"`
	// Total traces returned.
	TotalTraces   int32 `protobuf:"varint,2,opt,name=total_traces,json=totalTraces,proto3" json:"total_traces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryUnifiedTracesResponse) Reset() {
	*x = QueryUnifiedTracesResponse{}
	mi := &file_coral_colony_v1_colony_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUnifiedTracesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUnifiedTracesResponse) ProtoMessage() {}

func (x *QueryUnifiedTracesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_colony_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUnifiedTracesResponse.ProtoReflect.Descriptor instead.
func (*QueryUnifiedTracesResponse) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_colony_proto_rawDescGZIP(), []int{16}
}

func (x *QueryUnifiedTracesResponse) GetSpans() []*v11.EbpfTraceSpan {
	if x != nil {
		return x.Spans
	}
	return nil
}

func (x *QueryUnifiedTracesResponse) GetTotalTraces() int32 {
	if x != nil {
		return x.TotalTraces
	}
	return 0
}

type QueryUnifiedMetricsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: filter by service.
	Service string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	// Time range (default: "1h").
	TimeRange string `protobuf:"bytes,2,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	// Optional: ebpf|telemetry|all (default: all).
	Source string `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	// Optional: http|grpc|sql|auto (default: auto).
	Protocol string `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// Optional: HTTP route filter.
	HttpRoute string `protobuf:"bytes,5,opt,name=http_route,json=httpRoute,proto3" json:"http_route,omitempty"`
	// Optional: HTTP method filter.
	HttpMethod string `protobuf:"bytes,6,opt,name=http_method,json=httpMethod,proto3" json:"http_method,omitempty"`
	// Optional: HTTP status code range filter.
	StatusCodeRange string `protobuf:"bytes,7,opt,name=status_code_range,json=statusCodeRange,proto3" json:"status_code_range,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QueryUnifiedMetricsRequest) Reset() {
	*x = QueryUnifiedMetricsRequest{}
	mi := &file_coral_colony_v1_colony_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUnifiedMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUnifiedMetricsRequest) ProtoMessage() {}

func (x *QueryUnifiedMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_colony_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUnifiedMetricsRequest.ProtoReflect.Descriptor instead.
func (*QueryUnifiedMetricsRequest) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_colony_proto_rawDescGZIP(), []int{17}
}

func (x *QueryUnifiedMetricsRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *QueryUnifiedMetricsRequest) GetTimeRange() string {
	if x != nil {
		return x.TimeRange
	}
	return ""
}

func (x *QueryUnifiedMetricsRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *QueryUnifiedMetricsRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *QueryUnifiedMetricsRequest) GetHttpRoute() string {
	if x != nil {
		return x.HttpRoute
	}
	return ""
}

func (x *QueryUnifiedMetricsRequest) GetHttpMethod() string {
	if x != nil {
		return x.HttpMethod
	}
	return ""
}

func (x *QueryUnifiedMetricsRequest) GetStatusCodeRange() string {
	if x != nil {
		return x.StatusCodeRange
	}
	return ""
}

type QueryUnifiedMetricsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Structured HTTP metrics (eBPF + OTLP).
	HttpMetrics []*v11.EbpfHttpMetric `protobuf:"bytes,1,rep,name=http_metrics,json=httpMetrics,proto3" json:"http_metrics,omitempty"`
	// Structured gRPC metrics (eBPF + OTLP).
	GrpcMetrics []*v11.EbpfGrpcMetric `protobuf:"bytes,2,rep,name=grpc_metrics,json=grpcMetrics,proto3" json:"grpc_metrics,omitempty"`
	// Structured SQL metrics (eBPF + OTLP).
	SqlMetrics []*v11.EbpfSqlMetric `protobuf:"bytes,3,rep,name=sql_metrics,json=sqlMetrics,proto3" json:"sql_metrics,omitempty"`
	// Total metrics returned.
	TotalMetrics  int32 `protobuf:"varint,4,opt,name=total_metrics,json=totalMetrics,proto3" json:"total_metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryUnifiedMetricsResponse) Reset() {
	*x = QueryUnifiedMetricsResponse{}
	mi := &file_coral_colony_v1_colony_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUnifiedMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUnifiedMetricsResponse) ProtoMessage() {}

func (x *QueryUnifiedMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_colony_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUnifiedMetricsResponse.ProtoReflect.Descriptor instead.
func (*QueryUnifiedMetricsResponse) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_colony_proto_rawDescGZIP(), []int{18}
}

func (x *QueryUnifiedMetricsResponse) GetHttpMetrics() []*v11.EbpfHttpMetric {
	if x != nil {
		return x.HttpMetrics
	}
	return nil
}

func (x *QueryUnifiedMetricsResponse) GetGrpcMetrics() []*v11.EbpfGrpcMetric {
	if x != nil {
		return x.GrpcMetrics
	}
	return nil
}

func (x *QueryUnifiedMetricsResponse) GetSqlMetrics() []*v11.EbpfSqlMetric {
	if x != nil {
		return x.SqlMetrics
	}
	return nil
}

func (x *QueryUnifiedMetricsResponse) GetTotalMetrics() int32 {
	if x != nil {
		return x.TotalMetrics
	}
	return 0
}

type QueryUnifiedLogsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: filter by service.
	Service string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	// Time range (default: "1h").
	TimeRange string `protobuf:"bytes,2,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	// Optional: debug|info|warn|error.
	Level string `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`
	// Optional: full-text search.
	Search string `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`
	// Maximum logs to return.
	MaxLogs       int32 `protobuf:"varint,5,opt,name=max_logs,json=maxLogs,proto3" json:"max_logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryUnifiedLogsRequest) Reset() {
	*x = QueryUnifiedLogsRequest{}
	mi := &file_coral_colony_v1_colony_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUnifiedLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUnifiedLogsRequest) ProtoMessage() {}

func (x *QueryUnifiedLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_colony_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUnifiedLogsRequest.ProtoReflect.Descriptor instead.
func (*QueryUnifiedLogsRequest) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_colony_proto_rawDescGZIP(), []int{19}
}

func (x *QueryUnifiedLogsRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *QueryUnifiedLogsRequest) GetTimeRange() string {
	if x != nil {
		return x.TimeRange
	}
	return ""
}

func (x *QueryUnifiedLogsRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *QueryUnifiedLogsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *QueryUnifiedLogsRequest) GetMaxLogs() int32 {
	if x != nil {
		return x.MaxLogs
	}
	return 0
}

type UnifiedLogEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timestamp (Unix milliseconds).
	Timestamp int64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Service name.
	ServiceName string `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	// Log level: debug, info, warn, error.
	Level string `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`
	// Log message.
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// Associated trace ID (if any).
	TraceId string `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// Additional attributes.
	Attributes    map[string]string `protobuf:"bytes,6,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnifiedLogEntry) Reset() {
	*x = UnifiedLogEntry{}
	mi := &file_coral_colony_v1_colony_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnifiedLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnifiedLogEntry) ProtoMessage() {}

func (x *UnifiedLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_colony_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnifiedLogEntry.ProtoReflect.Descriptor instead.
func (*UnifiedLogEntry) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_colony_proto_rawDescGZIP(), []int{20}
}

func (x *UnifiedLogEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *UnifiedLogEntry) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *UnifiedLogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *UnifiedLogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UnifiedLogEntry) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *UnifiedLogEntry) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type QueryUnifiedLogsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Structured log entries.
	Logs []*UnifiedLogEntry `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	// Total logs returned.
	TotalLogs     int32 `protobuf:"varint,2,opt,name=total_logs,json=totalLogs,proto3" json:"total_logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryUnifiedLogsResponse) Reset() {
	*x = QueryUnifiedLogsResponse{}
	mi := &file_coral_colony_v1_colony_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUnifiedLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUnifiedLogsResponse) ProtoMessage() {}

func (x *QueryUnifiedLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_colony_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUnifiedLogsResponse.ProtoReflect.Descriptor instead.
func (*QueryUnifiedLogsResponse) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_colony_proto_rawDescGZIP(), []int{21}
}

func (x *QueryUnifiedLogsResponse) GetLogs() []*UnifiedLogEntry {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *QueryUnifiedLogsResponse) GetTotalLogs() int32 {
	if x != nil {
		return x.TotalLogs
	}
	return 0
}

var File_coral_colony_v1_colony_proto protoreflect.FileDescriptor

const file_coral_colony_v1_colony_proto_rawDesc = "" +
	"\n" +
	"\x1ccoral/colony/v1/colony.proto\x12\x0fcoral.colony.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18coral/mesh/v1/auth.proto\x1a\x1acoral/agent/v1/agent.proto\x1a\x19coral/colony/v1/mcp.proto\"\x12\n" +
	"\x10GetStatusRequest\"\x99\x05\n" +
	"\x11GetStatusResponse\x12\x1b\n" +
	"\tcolony_id\x18\x01 \x01(\tR\bcolonyId\x12\x19\n" +
	"\bapp_name\x18\x02 \x01(\tR\aappName\x12 \n" +
	"\venvironment\x18\x03 \x01(\tR\venvironment\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x129\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12%\n" +
	"\x0euptime_seconds\x18\x06 \x01(\x03R\ruptimeSeconds\x12\x1f\n" +
	"\vagent_count\x18\a \x01(\x05R\n" +
	"agentCount\x12#\n" +
	"\rdashboard_url\x18\b \x01(\tR\fdashboardUrl\x12#\n" +
	"\rstorage_bytes\x18\t \x01(\x03R\fstorageBytes\x12%\n" +
	"\x0ewireguard_port\x18\n" +
	" \x01(\x05R\rwireguardPort\x120\n" +
	"\x14wireguard_public_key\x18\v \x01(\tR\x12wireguardPublicKey\x12/\n" +
	"\x13wireguard_endpoints\x18\f \x03(\tR\x12wireguardEndpoints\x12!\n" +
	"\fconnect_port\x18\r \x01(\x05R\vconnectPort\x12\x1b\n" +
	"\tmesh_ipv4\x18\x0e \x01(\tR\bmeshIpv4\x12\x1b\n" +
	"\tmesh_ipv6\x18\x0f \x01(\tR\bmeshIpv6\x12,\n" +
	"\x12active_agent_count\x18\x10 \x01(\x05R\x10activeAgentCount\x120\n" +
	"\x14degraded_agent_count\x18\x11 \x01(\x05R\x12degradedAgentCount\"\x13\n" +
	"\x11ListAgentsRequest\"D\n" +
	"\x12ListAgentsResponse\x12.\n" +
	"\x06agents\x18\x01 \x03(\v2\x16.coral.colony.v1.AgentR\x06agents\"\xe1\x02\n" +
	"\x05Agent\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12)\n" +
	"\x0ecomponent_name\x18\x02 \x01(\tB\x02\x18\x01R\rcomponentName\x12\x1b\n" +
	"\tmesh_ipv4\x18\x03 \x01(\tR\bmeshIpv4\x12\x1b\n" +
	"\tmesh_ipv6\x18\x04 \x01(\tR\bmeshIpv6\x127\n" +
	"\tlast_seen\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x126\n" +
	"\bservices\x18\a \x03(\v2\x1a.coral.mesh.v1.ServiceInfoR\bservices\x12O\n" +
	"\x0fruntime_context\x18\b \x01(\v2&.coral.agent.v1.RuntimeContextResponseR\x0eruntimeContext\"\x14\n" +
	"\x12GetTopologyRequest\"\xa1\x01\n" +
	"\x13GetTopologyResponse\x12\x1b\n" +
	"\tcolony_id\x18\x01 \x01(\tR\bcolonyId\x12.\n" +
	"\x06agents\x18\x02 \x03(\v2\x16.coral.colony.v1.AgentR\x06agents\x12=\n" +
	"\vconnections\x18\x03 \x03(\v2\x1b.coral.colony.v1.ConnectionR\vconnections\"o\n" +
	"\n" +
	"Connection\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12'\n" +
	"\x0fconnection_type\x18\x03 \x01(\tR\x0econnectionType\"?\n" +
	"\x19RequestCertificateRequest\x12\x10\n" +
	"\x03jwt\x18\x01 \x01(\tR\x03jwt\x12\x10\n" +
	"\x03csr\x18\x02 \x01(\fR\x03csr\"x\n" +
	"\x1aRequestCertificateResponse\x12 \n" +
	"\vcertificate\x18\x01 \x01(\fR\vcertificate\x12\x19\n" +
	"\bca_chain\x18\x02 \x01(\fR\acaChain\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\"W\n" +
	"\x18RevokeCertificateRequest\x12#\n" +
	"\rserial_number\x18\x01 \x01(\tR\fserialNumber\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"5\n" +
	"\x19RevokeCertificateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"U\n" +
	"\x1aQueryUnifiedSummaryRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x1d\n" +
	"\n" +
	"time_range\x18\x02 \x01(\tR\ttimeRange\"\x8b\x04\n" +
	"\x14UnifiedSummaryResult\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rrequest_count\x18\x03 \x01(\x03R\frequestCount\x12\x1d\n" +
	"\n" +
	"error_rate\x18\x04 \x01(\x01R\terrorRate\x12$\n" +
	"\x0eavg_latency_ms\x18\x05 \x01(\x01R\favgLatencyMs\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x12\x16\n" +
	"\x06issues\x18\a \x03(\tR\x06issues\x120\n" +
	"\x14host_cpu_utilization\x18\b \x01(\x01R\x12hostCpuUtilization\x127\n" +
	"\x18host_cpu_utilization_avg\x18\t \x01(\x01R\x15hostCpuUtilizationAvg\x12/\n" +
	"\x14host_memory_usage_gb\x18\n" +
	" \x01(\x01R\x11hostMemoryUsageGb\x12/\n" +
	"\x14host_memory_limit_gb\x18\v \x01(\x01R\x11hostMemoryLimitGb\x126\n" +
	"\x17host_memory_utilization\x18\f \x01(\x01R\x15hostMemoryUtilization\x12\x19\n" +
	"\bagent_id\x18\r \x01(\tR\aagentId\"b\n" +
	"\x1bQueryUnifiedSummaryResponse\x12C\n" +
	"\tsummaries\x18\x01 \x03(\v2%.coral.colony.v1.UnifiedSummaryResultR\tsummaries\"\xce\x01\n" +
	"\x19QueryUnifiedTracesRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x1d\n" +
	"\n" +
	"time_range\x18\x02 \x01(\tR\ttimeRange\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x19\n" +
	"\btrace_id\x18\x04 \x01(\tR\atraceId\x12&\n" +
	"\x0fmin_duration_ms\x18\x05 \x01(\x05R\rminDurationMs\x12\x1d\n" +
	"\n" +
	"max_traces\x18\x06 \x01(\x05R\tmaxTraces\"t\n" +
	"\x1aQueryUnifiedTracesResponse\x123\n" +
	"\x05spans\x18\x01 \x03(\v2\x1d.coral.agent.v1.EbpfTraceSpanR\x05spans\x12!\n" +
	"\ftotal_traces\x18\x02 \x01(\x05R\vtotalTraces\"\xf5\x01\n" +
	"\x1aQueryUnifiedMetricsRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x1d\n" +
	"\n" +
	"time_range\x18\x02 \x01(\tR\ttimeRange\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\x12\x1d\n" +
	"\n" +
	"http_route\x18\x05 \x01(\tR\thttpRoute\x12\x1f\n" +
	"\vhttp_method\x18\x06 \x01(\tR\n" +
	"httpMethod\x12*\n" +
	"\x11status_code_range\x18\a \x01(\tR\x0fstatusCodeRange\"\x88\x02\n" +
	"\x1bQueryUnifiedMetricsResponse\x12A\n" +
	"\fhttp_metrics\x18\x01 \x03(\v2\x1e.coral.agent.v1.EbpfHttpMetricR\vhttpMetrics\x12A\n" +
	"\fgrpc_metrics\x18\x02 \x03(\v2\x1e.coral.agent.v1.EbpfGrpcMetricR\vgrpcMetrics\x12>\n" +
	"\vsql_metrics\x18\x03 \x03(\v2\x1d.coral.agent.v1.EbpfSqlMetricR\n" +
	"sqlMetrics\x12#\n" +
	"\rtotal_metrics\x18\x04 \x01(\x05R\ftotalMetrics\"\x9b\x01\n" +
	"\x17QueryUnifiedLogsRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x1d\n" +
	"\n" +
	"time_range\x18\x02 \x01(\tR\ttimeRange\x12\x14\n" +
	"\x05level\x18\x03 \x01(\tR\x05level\x12\x16\n" +
	"\x06search\x18\x04 \x01(\tR\x06search\x12\x19\n" +
	"\bmax_logs\x18\x05 \x01(\x05R\amaxLogs\"\xae\x02\n" +
	"\x0fUnifiedLogEntry\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x14\n" +
	"\x05level\x18\x03 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId\x12P\n" +
	"\n" +
	"attributes\x18\x06 \x03(\v20.coral.colony.v1.UnifiedLogEntry.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"o\n" +
	"\x18QueryUnifiedLogsResponse\x124\n" +
	"\x04logs\x18\x01 \x03(\v2 .coral.colony.v1.UnifiedLogEntryR\x04logs\x12\x1d\n" +
	"\n" +
	"total_logs\x18\x02 \x01(\x05R\ttotalLogs2\xab\t\n" +
	"\rColonyService\x12R\n" +
	"\tGetStatus\x12!.coral.colony.v1.GetStatusRequest\x1a\".coral.colony.v1.GetStatusResponse\x12U\n" +
	"\n" +
	"ListAgents\x12\".coral.colony.v1.ListAgentsRequest\x1a#.coral.colony.v1.ListAgentsResponse\x12X\n" +
	"\vGetTopology\x12#.coral.colony.v1.GetTopologyRequest\x1a$.coral.colony.v1.GetTopologyResponse\x12p\n" +
	"\x13QueryUnifiedSummary\x12+.coral.colony.v1.QueryUnifiedSummaryRequest\x1a,.coral.colony.v1.QueryUnifiedSummaryResponse\x12m\n" +
	"\x12QueryUnifiedTraces\x12*.coral.colony.v1.QueryUnifiedTracesRequest\x1a+.coral.colony.v1.QueryUnifiedTracesResponse\x12p\n" +
	"\x13QueryUnifiedMetrics\x12+.coral.colony.v1.QueryUnifiedMetricsRequest\x1a,.coral.colony.v1.QueryUnifiedMetricsResponse\x12g\n" +
	"\x10QueryUnifiedLogs\x12(.coral.colony.v1.QueryUnifiedLogsRequest\x1a).coral.colony.v1.QueryUnifiedLogsResponse\x12O\n" +
	"\bCallTool\x12 .coral.colony.v1.CallToolRequest\x1a!.coral.colony.v1.CallToolResponse\x12Y\n" +
	"\n" +
	"StreamTool\x12\".coral.colony.v1.StreamToolRequest\x1a#.coral.colony.v1.StreamToolResponse(\x010\x01\x12R\n" +
	"\tListTools\x12!.coral.colony.v1.ListToolsRequest\x1a\".coral.colony.v1.ListToolsResponse\x12m\n" +
	"\x12RequestCertificate\x12*.coral.colony.v1.RequestCertificateRequest\x1a+.coral.colony.v1.RequestCertificateResponse\x12j\n" +
	"\x11RevokeCertificate\x12).coral.colony.v1.RevokeCertificateRequest\x1a*.coral.colony.v1.RevokeCertificateResponseB\xb6\x01\n" +
	"\x13com.coral.colony.v1B\vColonyProtoP\x01Z4github.com/coral-mesh/coral/coral/colony/v1;colonyv1\xa2\x02\x03CCX\xaa\x02\x0fCoral.Colony.V1\xca\x02\x0fCoral\\Colony\\V1\xe2\x02\x1bCoral\\Colony\\V1\\GPBMetadata\xea\x02\x11Coral::Colony::V1b\x06proto3"

var (
	file_coral_colony_v1_colony_proto_rawDescOnce sync.Once
	file_coral_colony_v1_colony_proto_rawDescData []byte
)

func file_coral_colony_v1_colony_proto_rawDescGZIP() []byte {
	file_coral_colony_v1_colony_proto_rawDescOnce.Do(func() {
		file_coral_colony_v1_colony_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coral_colony_v1_colony_proto_rawDesc), len(file_coral_colony_v1_colony_proto_rawDesc)))
	})
	return file_coral_colony_v1_colony_proto_rawDescData
}

var file_coral_colony_v1_colony_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_coral_colony_v1_colony_proto_goTypes = []any{
	(*GetStatusRequest)(nil),            // 0: coral.colony.v1.GetStatusRequest
	(*GetStatusResponse)(nil),           // 1: coral.colony.v1.GetStatusResponse
	(*ListAgentsRequest)(nil),           // 2: coral.colony.v1.ListAgentsRequest
	(*ListAgentsResponse)(nil),          // 3: coral.colony.v1.ListAgentsResponse
	(*Agent)(nil),                       // 4: coral.colony.v1.Agent
	(*GetTopologyRequest)(nil),          // 5: coral.colony.v1.GetTopologyRequest
	(*GetTopologyResponse)(nil),         // 6: coral.colony.v1.GetTopologyResponse
	(*Connection)(nil),                  // 7: coral.colony.v1.Connection
	(*RequestCertificateRequest)(nil),   // 8: coral.colony.v1.RequestCertificateRequest
	(*RequestCertificateResponse)(nil),  // 9: coral.colony.v1.RequestCertificateResponse
	(*RevokeCertificateRequest)(nil),    // 10: coral.colony.v1.RevokeCertificateRequest
	(*RevokeCertificateResponse)(nil),   // 11: coral.colony.v1.RevokeCertificateResponse
	(*QueryUnifiedSummaryRequest)(nil),  // 12: coral.colony.v1.QueryUnifiedSummaryRequest
	(*UnifiedSummaryResult)(nil),        // 13: coral.colony.v1.UnifiedSummaryResult
	(*QueryUnifiedSummaryResponse)(nil), // 14: coral.colony.v1.QueryUnifiedSummaryResponse
	(*QueryUnifiedTracesRequest)(nil),   // 15: coral.colony.v1.QueryUnifiedTracesRequest
	(*QueryUnifiedTracesResponse)(nil),  // 16: coral.colony.v1.QueryUnifiedTracesResponse
	(*QueryUnifiedMetricsRequest)(nil),  // 17: coral.colony.v1.QueryUnifiedMetricsRequest
	(*QueryUnifiedMetricsResponse)(nil), // 18: coral.colony.v1.QueryUnifiedMetricsResponse
	(*QueryUnifiedLogsRequest)(nil),     // 19: coral.colony.v1.QueryUnifiedLogsRequest
	(*UnifiedLogEntry)(nil),             // 20: coral.colony.v1.UnifiedLogEntry
	(*QueryUnifiedLogsResponse)(nil),    // 21: coral.colony.v1.QueryUnifiedLogsResponse
	nil,                                 // 22: coral.colony.v1.UnifiedLogEntry.AttributesEntry
	(*timestamppb.Timestamp)(nil),       // 23: google.protobuf.Timestamp
	(*v1.ServiceInfo)(nil),              // 24: coral.mesh.v1.ServiceInfo
	(*v11.RuntimeContextResponse)(nil),  // 25: coral.agent.v1.RuntimeContextResponse
	(*v11.EbpfTraceSpan)(nil),           // 26: coral.agent.v1.EbpfTraceSpan
	(*v11.EbpfHttpMetric)(nil),          // 27: coral.agent.v1.EbpfHttpMetric
	(*v11.EbpfGrpcMetric)(nil),          // 28: coral.agent.v1.EbpfGrpcMetric
	(*v11.EbpfSqlMetric)(nil),           // 29: coral.agent.v1.EbpfSqlMetric
	(*CallToolRequest)(nil),             // 30: coral.colony.v1.CallToolRequest
	(*StreamToolRequest)(nil),           // 31: coral.colony.v1.StreamToolRequest
	(*ListToolsRequest)(nil),            // 32: coral.colony.v1.ListToolsRequest
	(*CallToolResponse)(nil),            // 33: coral.colony.v1.CallToolResponse
	(*StreamToolResponse)(nil),          // 34: coral.colony.v1.StreamToolResponse
	(*ListToolsResponse)(nil),           // 35: coral.colony.v1.ListToolsResponse
}
var file_coral_colony_v1_colony_proto_depIdxs = []int32{
	23, // 0: coral.colony.v1.GetStatusResponse.started_at:type_name -> google.protobuf.Timestamp
	4,  // 1: coral.colony.v1.ListAgentsResponse.agents:type_name -> coral.colony.v1.Agent
	23, // 2: coral.colony.v1.Agent.last_seen:type_name -> google.protobuf.Timestamp
	24, // 3: coral.colony.v1.Agent.services:type_name -> coral.mesh.v1.ServiceInfo
	25, // 4: coral.colony.v1.Agent.runtime_context:type_name -> coral.agent.v1.RuntimeContextResponse
	4,  // 5: coral.colony.v1.GetTopologyResponse.agents:type_name -> coral.colony.v1.Agent
	7,  // 6: coral.colony.v1.GetTopologyResponse.connections:type_name -> coral.colony.v1.Connection
	13, // 7: coral.colony.v1.QueryUnifiedSummaryResponse.summaries:type_name -> coral.colony.v1.UnifiedSummaryResult
	26, // 8: coral.colony.v1.QueryUnifiedTracesResponse.spans:type_name -> coral.agent.v1.EbpfTraceSpan
	27, // 9: coral.colony.v1.QueryUnifiedMetricsResponse.http_metrics:type_name -> coral.agent.v1.EbpfHttpMetric
	28, // 10: coral.colony.v1.QueryUnifiedMetricsResponse.grpc_metrics:type_name -> coral.agent.v1.EbpfGrpcMetric
	29, // 11: coral.colony.v1.QueryUnifiedMetricsResponse.sql_metrics:type_name -> coral.agent.v1.EbpfSqlMetric
	22, // 12: coral.colony.v1.UnifiedLogEntry.attributes:type_name -> coral.colony.v1.UnifiedLogEntry.AttributesEntry
	20, // 13: coral.colony.v1.QueryUnifiedLogsResponse.logs:type_name -> coral.colony.v1.UnifiedLogEntry
	0,  // 14: coral.colony.v1.ColonyService.GetStatus:input_type -> coral.colony.v1.GetStatusRequest
	2,  // 15: coral.colony.v1.ColonyService.ListAgents:input_type -> coral.colony.v1.ListAgentsRequest
	5,  // 16: coral.colony.v1.ColonyService.GetTopology:input_type -> coral.colony.v1.GetTopologyRequest
	12, // 17: coral.colony.v1.ColonyService.QueryUnifiedSummary:input_type -> coral.colony.v1.QueryUnifiedSummaryRequest
	15, // 18: coral.colony.v1.ColonyService.QueryUnifiedTraces:input_type -> coral.colony.v1.QueryUnifiedTracesRequest
	17, // 19: coral.colony.v1.ColonyService.QueryUnifiedMetrics:input_type -> coral.colony.v1.QueryUnifiedMetricsRequest
	19, // 20: coral.colony.v1.ColonyService.QueryUnifiedLogs:input_type -> coral.colony.v1.QueryUnifiedLogsRequest
	30, // 21: coral.colony.v1.ColonyService.CallTool:input_type -> coral.colony.v1.CallToolRequest
	31, // 22: coral.colony.v1.ColonyService.StreamTool:input_type -> coral.colony.v1.StreamToolRequest
	32, // 23: coral.colony.v1.ColonyService.ListTools:input_type -> coral.colony.v1.ListToolsRequest
	8,  // 24: coral.colony.v1.ColonyService.RequestCertificate:input_type -> coral.colony.v1.RequestCertificateRequest
	10, // 25: coral.colony.v1.ColonyService.RevokeCertificate:input_type -> coral.colony.v1.RevokeCertificateRequest
	1,  // 26: coral.colony.v1.ColonyService.GetStatus:output_type -> coral.colony.v1.GetStatusResponse
	3,  // 27: coral.colony.v1.ColonyService.ListAgents:output_type -> coral.colony.v1.ListAgentsResponse
	6,  // 28: coral.colony.v1.ColonyService.GetTopology:output_type -> coral.colony.v1.GetTopologyResponse
	14, // 29: coral.colony.v1.ColonyService.QueryUnifiedSummary:output_type -> coral.colony.v1.QueryUnifiedSummaryResponse
	16, // 30: coral.colony.v1.ColonyService.QueryUnifiedTraces:output_type -> coral.colony.v1.QueryUnifiedTracesResponse
	18, // 31: coral.colony.v1.ColonyService.QueryUnifiedMetrics:output_type -> coral.colony.v1.QueryUnifiedMetricsResponse
	21, // 32: coral.colony.v1.ColonyService.QueryUnifiedLogs:output_type -> coral.colony.v1.QueryUnifiedLogsResponse
	33, // 33: coral.colony.v1.ColonyService.CallTool:output_type -> coral.colony.v1.CallToolResponse
	34, // 34: coral.colony.v1.ColonyService.StreamTool:output_type -> coral.colony.v1.StreamToolResponse
	35, // 35: coral.colony.v1.ColonyService.ListTools:output_type -> coral.colony.v1.ListToolsResponse
	9,  // 36: coral.colony.v1.ColonyService.RequestCertificate:output_type -> coral.colony.v1.RequestCertificateResponse
	11, // 37: coral.colony.v1.ColonyService.RevokeCertificate:output_type -> coral.colony.v1.RevokeCertificateResponse
	26, // [26:38] is the sub-list for method output_type
	14, // [14:26] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_coral_colony_v1_colony_proto_init() }
func file_coral_colony_v1_colony_proto_init() {
	if File_coral_colony_v1_colony_proto != nil {
		return
	}
	file_coral_colony_v1_mcp_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coral_colony_v1_colony_proto_rawDesc), len(file_coral_colony_v1_colony_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coral_colony_v1_colony_proto_goTypes,
		DependencyIndexes: file_coral_colony_v1_colony_proto_depIdxs,
		MessageInfos:      file_coral_colony_v1_colony_proto_msgTypes,
	}.Build()
	File_coral_colony_v1_colony_proto = out.File
	file_coral_colony_v1_colony_proto_goTypes = nil
	file_coral_colony_v1_colony_proto_depIdxs = nil
}
