// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: coral/colony/v1/colony.proto

package colonyv1

import (
	v11 "github.com/coral-io/coral/coral/agent/v1"
	v1 "github.com/coral-io/coral/coral/mesh/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_coral_colony_v1_colony_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_colony_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_colony_proto_rawDescGZIP(), []int{0}
}

type GetStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Colony identifier.
	ColonyId string `protobuf:"bytes,1,opt,name=colony_id,json=colonyId,proto3" json:"colony_id,omitempty"`
	// Application name.
	AppName string `protobuf:"bytes,2,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	// Environment (e.g., "production", "staging").
	Environment string `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"`
	// Status ("running", "degraded", "unhealthy").
	Status string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	// When the colony started.
	StartedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// Uptime in seconds.
	UptimeSeconds int64 `protobuf:"varint,6,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	// Number of connected agents.
	AgentCount int32 `protobuf:"varint,7,opt,name=agent_count,json=agentCount,proto3" json:"agent_count,omitempty"`
	// Dashboard URL.
	DashboardUrl string `protobuf:"bytes,8,opt,name=dashboard_url,json=dashboardUrl,proto3" json:"dashboard_url,omitempty"`
	// Storage size in bytes.
	StorageBytes int64 `protobuf:"varint,9,opt,name=storage_bytes,json=storageBytes,proto3" json:"storage_bytes,omitempty"`
	// Network endpoint information.
	// WireGuard listen port (UDP).
	WireguardPort int32 `protobuf:"varint,10,opt,name=wireguard_port,json=wireguardPort,proto3" json:"wireguard_port,omitempty"`
	// WireGuard public key.
	WireguardPublicKey string `protobuf:"bytes,11,opt,name=wireguard_public_key,json=wireguardPublicKey,proto3" json:"wireguard_public_key,omitempty"`
	// WireGuard registered endpoints (e.g., ":51820").
	WireguardEndpoints []string `protobuf:"bytes,12,rep,name=wireguard_endpoints,json=wireguardEndpoints,proto3" json:"wireguard_endpoints,omitempty"`
	// Buf Connect service port (TCP).
	ConnectPort int32 `protobuf:"varint,13,opt,name=connect_port,json=connectPort,proto3" json:"connect_port,omitempty"`
	// Colony mesh IPv4 address.
	MeshIpv4 string `protobuf:"bytes,14,opt,name=mesh_ipv4,json=meshIpv4,proto3" json:"mesh_ipv4,omitempty"`
	// Colony mesh IPv6 address.
	MeshIpv6      string `protobuf:"bytes,15,opt,name=mesh_ipv6,json=meshIpv6,proto3" json:"mesh_ipv6,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_coral_colony_v1_colony_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_colony_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_colony_proto_rawDescGZIP(), []int{1}
}

func (x *GetStatusResponse) GetColonyId() string {
	if x != nil {
		return x.ColonyId
	}
	return ""
}

func (x *GetStatusResponse) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *GetStatusResponse) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *GetStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetStatusResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *GetStatusResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *GetStatusResponse) GetAgentCount() int32 {
	if x != nil {
		return x.AgentCount
	}
	return 0
}

func (x *GetStatusResponse) GetDashboardUrl() string {
	if x != nil {
		return x.DashboardUrl
	}
	return ""
}

func (x *GetStatusResponse) GetStorageBytes() int64 {
	if x != nil {
		return x.StorageBytes
	}
	return 0
}

func (x *GetStatusResponse) GetWireguardPort() int32 {
	if x != nil {
		return x.WireguardPort
	}
	return 0
}

func (x *GetStatusResponse) GetWireguardPublicKey() string {
	if x != nil {
		return x.WireguardPublicKey
	}
	return ""
}

func (x *GetStatusResponse) GetWireguardEndpoints() []string {
	if x != nil {
		return x.WireguardEndpoints
	}
	return nil
}

func (x *GetStatusResponse) GetConnectPort() int32 {
	if x != nil {
		return x.ConnectPort
	}
	return 0
}

func (x *GetStatusResponse) GetMeshIpv4() string {
	if x != nil {
		return x.MeshIpv4
	}
	return ""
}

func (x *GetStatusResponse) GetMeshIpv6() string {
	if x != nil {
		return x.MeshIpv6
	}
	return ""
}

type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_coral_colony_v1_colony_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_colony_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_colony_proto_rawDescGZIP(), []int{2}
}

type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*Agent               `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_coral_colony_v1_colony_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_colony_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_colony_proto_rawDescGZIP(), []int{3}
}

func (x *ListAgentsResponse) GetAgents() []*Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

type Agent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent identifier.
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// DEPRECATED: Component name (single-service mode).
	// Use 'services' field for multi-service agents.
	//
	// Deprecated: Marked as deprecated in coral/colony/v1/colony.proto.
	ComponentName string `protobuf:"bytes,2,opt,name=component_name,json=componentName,proto3" json:"component_name,omitempty"`
	// Mesh IPv4 address.
	MeshIpv4 string `protobuf:"bytes,3,opt,name=mesh_ipv4,json=meshIpv4,proto3" json:"mesh_ipv4,omitempty"`
	// Mesh IPv6 address.
	MeshIpv6 string `protobuf:"bytes,4,opt,name=mesh_ipv6,json=meshIpv6,proto3" json:"mesh_ipv6,omitempty"`
	// Last seen timestamp.
	LastSeen *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	// Status ("healthy", "degraded", "unhealthy").
	Status string `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	// Services monitored by this agent (RFD 011).
	Services []*v1.ServiceInfo `protobuf:"bytes,7,rep,name=services,proto3" json:"services,omitempty"`
	// NEW: Runtime context (RFD 018).
	RuntimeContext *v11.RuntimeContextResponse `protobuf:"bytes,8,opt,name=runtime_context,json=runtimeContext,proto3" json:"runtime_context,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Agent) Reset() {
	*x = Agent{}
	mi := &file_coral_colony_v1_colony_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_colony_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_colony_proto_rawDescGZIP(), []int{4}
}

func (x *Agent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// Deprecated: Marked as deprecated in coral/colony/v1/colony.proto.
func (x *Agent) GetComponentName() string {
	if x != nil {
		return x.ComponentName
	}
	return ""
}

func (x *Agent) GetMeshIpv4() string {
	if x != nil {
		return x.MeshIpv4
	}
	return ""
}

func (x *Agent) GetMeshIpv6() string {
	if x != nil {
		return x.MeshIpv6
	}
	return ""
}

func (x *Agent) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *Agent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Agent) GetServices() []*v1.ServiceInfo {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *Agent) GetRuntimeContext() *v11.RuntimeContextResponse {
	if x != nil {
		return x.RuntimeContext
	}
	return nil
}

type GetTopologyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopologyRequest) Reset() {
	*x = GetTopologyRequest{}
	mi := &file_coral_colony_v1_colony_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopologyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopologyRequest) ProtoMessage() {}

func (x *GetTopologyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_colony_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopologyRequest.ProtoReflect.Descriptor instead.
func (*GetTopologyRequest) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_colony_proto_rawDescGZIP(), []int{5}
}

type GetTopologyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Colony identifier.
	ColonyId string `protobuf:"bytes,1,opt,name=colony_id,json=colonyId,proto3" json:"colony_id,omitempty"`
	// List of agents.
	Agents []*Agent `protobuf:"bytes,2,rep,name=agents,proto3" json:"agents,omitempty"`
	// List of connections between components.
	Connections   []*Connection `protobuf:"bytes,3,rep,name=connections,proto3" json:"connections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopologyResponse) Reset() {
	*x = GetTopologyResponse{}
	mi := &file_coral_colony_v1_colony_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopologyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopologyResponse) ProtoMessage() {}

func (x *GetTopologyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_colony_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopologyResponse.ProtoReflect.Descriptor instead.
func (*GetTopologyResponse) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_colony_proto_rawDescGZIP(), []int{6}
}

func (x *GetTopologyResponse) GetColonyId() string {
	if x != nil {
		return x.ColonyId
	}
	return ""
}

func (x *GetTopologyResponse) GetAgents() []*Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

func (x *GetTopologyResponse) GetConnections() []*Connection {
	if x != nil {
		return x.Connections
	}
	return nil
}

type Connection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Source component ID.
	SourceId string `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	// Target component ID.
	TargetId string `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	// Connection type ("http", "grpc", "database", etc.).
	ConnectionType string `protobuf:"bytes,3,opt,name=connection_type,json=connectionType,proto3" json:"connection_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Connection) Reset() {
	*x = Connection{}
	mi := &file_coral_colony_v1_colony_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connection) ProtoMessage() {}

func (x *Connection) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_colony_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connection.ProtoReflect.Descriptor instead.
func (*Connection) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_colony_proto_rawDescGZIP(), []int{7}
}

func (x *Connection) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *Connection) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *Connection) GetConnectionType() string {
	if x != nil {
		return x.ConnectionType
	}
	return ""
}

var File_coral_colony_v1_colony_proto protoreflect.FileDescriptor

const file_coral_colony_v1_colony_proto_rawDesc = "" +
	"\n" +
	"\x1ccoral/colony/v1/colony.proto\x12\x0fcoral.colony.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18coral/mesh/v1/auth.proto\x1a\x1acoral/agent/v1/agent.proto\"\x12\n" +
	"\x10GetStatusRequest\"\xb9\x04\n" +
	"\x11GetStatusResponse\x12\x1b\n" +
	"\tcolony_id\x18\x01 \x01(\tR\bcolonyId\x12\x19\n" +
	"\bapp_name\x18\x02 \x01(\tR\aappName\x12 \n" +
	"\venvironment\x18\x03 \x01(\tR\venvironment\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x129\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12%\n" +
	"\x0euptime_seconds\x18\x06 \x01(\x03R\ruptimeSeconds\x12\x1f\n" +
	"\vagent_count\x18\a \x01(\x05R\n" +
	"agentCount\x12#\n" +
	"\rdashboard_url\x18\b \x01(\tR\fdashboardUrl\x12#\n" +
	"\rstorage_bytes\x18\t \x01(\x03R\fstorageBytes\x12%\n" +
	"\x0ewireguard_port\x18\n" +
	" \x01(\x05R\rwireguardPort\x120\n" +
	"\x14wireguard_public_key\x18\v \x01(\tR\x12wireguardPublicKey\x12/\n" +
	"\x13wireguard_endpoints\x18\f \x03(\tR\x12wireguardEndpoints\x12!\n" +
	"\fconnect_port\x18\r \x01(\x05R\vconnectPort\x12\x1b\n" +
	"\tmesh_ipv4\x18\x0e \x01(\tR\bmeshIpv4\x12\x1b\n" +
	"\tmesh_ipv6\x18\x0f \x01(\tR\bmeshIpv6\"\x13\n" +
	"\x11ListAgentsRequest\"D\n" +
	"\x12ListAgentsResponse\x12.\n" +
	"\x06agents\x18\x01 \x03(\v2\x16.coral.colony.v1.AgentR\x06agents\"\xe1\x02\n" +
	"\x05Agent\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12)\n" +
	"\x0ecomponent_name\x18\x02 \x01(\tB\x02\x18\x01R\rcomponentName\x12\x1b\n" +
	"\tmesh_ipv4\x18\x03 \x01(\tR\bmeshIpv4\x12\x1b\n" +
	"\tmesh_ipv6\x18\x04 \x01(\tR\bmeshIpv6\x127\n" +
	"\tlast_seen\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x126\n" +
	"\bservices\x18\a \x03(\v2\x1a.coral.mesh.v1.ServiceInfoR\bservices\x12O\n" +
	"\x0fruntime_context\x18\b \x01(\v2&.coral.agent.v1.RuntimeContextResponseR\x0eruntimeContext\"\x14\n" +
	"\x12GetTopologyRequest\"\xa1\x01\n" +
	"\x13GetTopologyResponse\x12\x1b\n" +
	"\tcolony_id\x18\x01 \x01(\tR\bcolonyId\x12.\n" +
	"\x06agents\x18\x02 \x03(\v2\x16.coral.colony.v1.AgentR\x06agents\x12=\n" +
	"\vconnections\x18\x03 \x03(\v2\x1b.coral.colony.v1.ConnectionR\vconnections\"o\n" +
	"\n" +
	"Connection\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12'\n" +
	"\x0fconnection_type\x18\x03 \x01(\tR\x0econnectionType2\x94\x02\n" +
	"\rColonyService\x12R\n" +
	"\tGetStatus\x12!.coral.colony.v1.GetStatusRequest\x1a\".coral.colony.v1.GetStatusResponse\x12U\n" +
	"\n" +
	"ListAgents\x12\".coral.colony.v1.ListAgentsRequest\x1a#.coral.colony.v1.ListAgentsResponse\x12X\n" +
	"\vGetTopology\x12#.coral.colony.v1.GetTopologyRequest\x1a$.coral.colony.v1.GetTopologyResponseB\xb4\x01\n" +
	"\x13com.coral.colony.v1B\vColonyProtoP\x01Z2github.com/coral-io/coral/coral/colony/v1;colonyv1\xa2\x02\x03CCX\xaa\x02\x0fCoral.Colony.V1\xca\x02\x0fCoral\\Colony\\V1\xe2\x02\x1bCoral\\Colony\\V1\\GPBMetadata\xea\x02\x11Coral::Colony::V1b\x06proto3"

var (
	file_coral_colony_v1_colony_proto_rawDescOnce sync.Once
	file_coral_colony_v1_colony_proto_rawDescData []byte
)

func file_coral_colony_v1_colony_proto_rawDescGZIP() []byte {
	file_coral_colony_v1_colony_proto_rawDescOnce.Do(func() {
		file_coral_colony_v1_colony_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coral_colony_v1_colony_proto_rawDesc), len(file_coral_colony_v1_colony_proto_rawDesc)))
	})
	return file_coral_colony_v1_colony_proto_rawDescData
}

var file_coral_colony_v1_colony_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_coral_colony_v1_colony_proto_goTypes = []any{
	(*GetStatusRequest)(nil),           // 0: coral.colony.v1.GetStatusRequest
	(*GetStatusResponse)(nil),          // 1: coral.colony.v1.GetStatusResponse
	(*ListAgentsRequest)(nil),          // 2: coral.colony.v1.ListAgentsRequest
	(*ListAgentsResponse)(nil),         // 3: coral.colony.v1.ListAgentsResponse
	(*Agent)(nil),                      // 4: coral.colony.v1.Agent
	(*GetTopologyRequest)(nil),         // 5: coral.colony.v1.GetTopologyRequest
	(*GetTopologyResponse)(nil),        // 6: coral.colony.v1.GetTopologyResponse
	(*Connection)(nil),                 // 7: coral.colony.v1.Connection
	(*timestamppb.Timestamp)(nil),      // 8: google.protobuf.Timestamp
	(*v1.ServiceInfo)(nil),             // 9: coral.mesh.v1.ServiceInfo
	(*v11.RuntimeContextResponse)(nil), // 10: coral.agent.v1.RuntimeContextResponse
}
var file_coral_colony_v1_colony_proto_depIdxs = []int32{
	8,  // 0: coral.colony.v1.GetStatusResponse.started_at:type_name -> google.protobuf.Timestamp
	4,  // 1: coral.colony.v1.ListAgentsResponse.agents:type_name -> coral.colony.v1.Agent
	8,  // 2: coral.colony.v1.Agent.last_seen:type_name -> google.protobuf.Timestamp
	9,  // 3: coral.colony.v1.Agent.services:type_name -> coral.mesh.v1.ServiceInfo
	10, // 4: coral.colony.v1.Agent.runtime_context:type_name -> coral.agent.v1.RuntimeContextResponse
	4,  // 5: coral.colony.v1.GetTopologyResponse.agents:type_name -> coral.colony.v1.Agent
	7,  // 6: coral.colony.v1.GetTopologyResponse.connections:type_name -> coral.colony.v1.Connection
	0,  // 7: coral.colony.v1.ColonyService.GetStatus:input_type -> coral.colony.v1.GetStatusRequest
	2,  // 8: coral.colony.v1.ColonyService.ListAgents:input_type -> coral.colony.v1.ListAgentsRequest
	5,  // 9: coral.colony.v1.ColonyService.GetTopology:input_type -> coral.colony.v1.GetTopologyRequest
	1,  // 10: coral.colony.v1.ColonyService.GetStatus:output_type -> coral.colony.v1.GetStatusResponse
	3,  // 11: coral.colony.v1.ColonyService.ListAgents:output_type -> coral.colony.v1.ListAgentsResponse
	6,  // 12: coral.colony.v1.ColonyService.GetTopology:output_type -> coral.colony.v1.GetTopologyResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_coral_colony_v1_colony_proto_init() }
func file_coral_colony_v1_colony_proto_init() {
	if File_coral_colony_v1_colony_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coral_colony_v1_colony_proto_rawDesc), len(file_coral_colony_v1_colony_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coral_colony_v1_colony_proto_goTypes,
		DependencyIndexes: file_coral_colony_v1_colony_proto_depIdxs,
		MessageInfos:      file_coral_colony_v1_colony_proto_msgTypes,
	}.Build()
	File_coral_colony_v1_colony_proto = out.File
	file_coral_colony_v1_colony_proto_goTypes = nil
	file_coral_colony_v1_colony_proto_depIdxs = nil
}
