// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: coral/colony/v1/debug.proto

package colonyv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	v1 "github.com/coral-mesh/coral/coral/mesh/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AttachUprobeRequest initiates a debug session on a specific function.
type AttachUprobeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	FunctionName  string                 `protobuf:"bytes,2,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	Duration      *durationpb.Duration   `protobuf:"bytes,3,opt,name=duration,proto3" json:"duration,omitempty"` // Default: 60s, Max: 600s
	Config        *v1.UprobeConfig       `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	AgentId       string                 `protobuf:"bytes,5,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // Manual override (until service discovery integration)
	SdkAddr       string                 `protobuf:"bytes,6,opt,name=sdk_addr,json=sdkAddr,proto3" json:"sdk_addr,omitempty"` // Manual override (until service discovery integration)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachUprobeRequest) Reset() {
	*x = AttachUprobeRequest{}
	mi := &file_coral_colony_v1_debug_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachUprobeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachUprobeRequest) ProtoMessage() {}

func (x *AttachUprobeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_debug_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachUprobeRequest.ProtoReflect.Descriptor instead.
func (*AttachUprobeRequest) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_debug_proto_rawDescGZIP(), []int{0}
}

func (x *AttachUprobeRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *AttachUprobeRequest) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *AttachUprobeRequest) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *AttachUprobeRequest) GetConfig() *v1.UprobeConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *AttachUprobeRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AttachUprobeRequest) GetSdkAddr() string {
	if x != nil {
		return x.SdkAddr
	}
	return ""
}

// AttachUprobeResponse confirms debug session creation.
type AttachUprobeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachUprobeResponse) Reset() {
	*x = AttachUprobeResponse{}
	mi := &file_coral_colony_v1_debug_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachUprobeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachUprobeResponse) ProtoMessage() {}

func (x *AttachUprobeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_debug_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachUprobeResponse.ProtoReflect.Descriptor instead.
func (*AttachUprobeResponse) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_debug_proto_rawDescGZIP(), []int{1}
}

func (x *AttachUprobeResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AttachUprobeResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *AttachUprobeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AttachUprobeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// DetachUprobeRequest stops a debug session early.
type DetachUprobeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetachUprobeRequest) Reset() {
	*x = DetachUprobeRequest{}
	mi := &file_coral_colony_v1_debug_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetachUprobeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachUprobeRequest) ProtoMessage() {}

func (x *DetachUprobeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_debug_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachUprobeRequest.ProtoReflect.Descriptor instead.
func (*DetachUprobeRequest) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_debug_proto_rawDescGZIP(), []int{2}
}

func (x *DetachUprobeRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// DetachUprobeResponse confirms session termination.
type DetachUprobeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetachUprobeResponse) Reset() {
	*x = DetachUprobeResponse{}
	mi := &file_coral_colony_v1_debug_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetachUprobeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachUprobeResponse) ProtoMessage() {}

func (x *DetachUprobeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_debug_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachUprobeResponse.ProtoReflect.Descriptor instead.
func (*DetachUprobeResponse) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_debug_proto_rawDescGZIP(), []int{3}
}

func (x *DetachUprobeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DetachUprobeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// QueryUprobeEventsRequest retrieves events from a debug session.
type QueryUprobeEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	MaxEvents     int32                  `protobuf:"varint,4,opt,name=max_events,json=maxEvents,proto3" json:"max_events,omitempty"` // Pagination
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryUprobeEventsRequest) Reset() {
	*x = QueryUprobeEventsRequest{}
	mi := &file_coral_colony_v1_debug_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUprobeEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUprobeEventsRequest) ProtoMessage() {}

func (x *QueryUprobeEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_debug_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUprobeEventsRequest.ProtoReflect.Descriptor instead.
func (*QueryUprobeEventsRequest) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_debug_proto_rawDescGZIP(), []int{4}
}

func (x *QueryUprobeEventsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *QueryUprobeEventsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *QueryUprobeEventsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *QueryUprobeEventsRequest) GetMaxEvents() int32 {
	if x != nil {
		return x.MaxEvents
	}
	return 0
}

// QueryUprobeEventsResponse returns captured events.
type QueryUprobeEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*v1.UprobeEvent      `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"` // Pagination indicator
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryUprobeEventsResponse) Reset() {
	*x = QueryUprobeEventsResponse{}
	mi := &file_coral_colony_v1_debug_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUprobeEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUprobeEventsResponse) ProtoMessage() {}

func (x *QueryUprobeEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_debug_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUprobeEventsResponse.ProtoReflect.Descriptor instead.
func (*QueryUprobeEventsResponse) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_debug_proto_rawDescGZIP(), []int{5}
}

func (x *QueryUprobeEventsResponse) GetEvents() []*v1.UprobeEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *QueryUprobeEventsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// ListDebugSessionsRequest retrieves active debug sessions.
type ListDebugSessionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional filter by service name.
	ServiceName string `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	// Optional filter by status.
	Status        string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDebugSessionsRequest) Reset() {
	*x = ListDebugSessionsRequest{}
	mi := &file_coral_colony_v1_debug_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDebugSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDebugSessionsRequest) ProtoMessage() {}

func (x *ListDebugSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_debug_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDebugSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListDebugSessionsRequest) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_debug_proto_rawDescGZIP(), []int{6}
}

func (x *ListDebugSessionsRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ListDebugSessionsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// ListDebugSessionsResponse returns active sessions.
type ListDebugSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*DebugSession        `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDebugSessionsResponse) Reset() {
	*x = ListDebugSessionsResponse{}
	mi := &file_coral_colony_v1_debug_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDebugSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDebugSessionsResponse) ProtoMessage() {}

func (x *ListDebugSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_debug_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDebugSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListDebugSessionsResponse) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_debug_proto_rawDescGZIP(), []int{7}
}

func (x *ListDebugSessionsResponse) GetSessions() []*DebugSession {
	if x != nil {
		return x.Sessions
	}
	return nil
}

// DebugSession represents an active or completed debug session.
type DebugSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	FunctionName  string                 `protobuf:"bytes,3,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	AgentId       string                 `protobuf:"bytes,4,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`                              // "active", "expired", "stopped"
	RequestedBy   string                 `protobuf:"bytes,8,opt,name=requested_by,json=requestedBy,proto3" json:"requested_by,omitempty"` // User who initiated session
	EventCount    int32                  `protobuf:"varint,9,opt,name=event_count,json=eventCount,proto3" json:"event_count,omitempty"`   // Number of events collected
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugSession) Reset() {
	*x = DebugSession{}
	mi := &file_coral_colony_v1_debug_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugSession) ProtoMessage() {}

func (x *DebugSession) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_debug_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugSession.ProtoReflect.Descriptor instead.
func (*DebugSession) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_debug_proto_rawDescGZIP(), []int{8}
}

func (x *DebugSession) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DebugSession) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *DebugSession) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *DebugSession) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *DebugSession) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *DebugSession) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *DebugSession) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DebugSession) GetRequestedBy() string {
	if x != nil {
		return x.RequestedBy
	}
	return ""
}

func (x *DebugSession) GetEventCount() int32 {
	if x != nil {
		return x.EventCount
	}
	return 0
}

var File_coral_colony_v1_debug_proto protoreflect.FileDescriptor

const file_coral_colony_v1_debug_proto_rawDesc = "" +
	"\n" +
	"\x1bcoral/colony/v1/debug.proto\x12\x0fcoral.colony.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x18coral/mesh/v1/ebpf.proto\"\xff\x01\n" +
	"\x13AttachUprobeRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12#\n" +
	"\rfunction_name\x18\x02 \x01(\tR\ffunctionName\x125\n" +
	"\bduration\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\bduration\x123\n" +
	"\x06config\x18\x04 \x01(\v2\x1b.coral.mesh.v1.UprobeConfigR\x06config\x12\x19\n" +
	"\bagent_id\x18\x05 \x01(\tR\aagentId\x12\x19\n" +
	"\bsdk_addr\x18\x06 \x01(\tR\asdkAddr\"\xa0\x01\n" +
	"\x14AttachUprobeResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"4\n" +
	"\x13DetachUprobeRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"F\n" +
	"\x14DetachUprobeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xca\x01\n" +
	"\x18QueryUprobeEventsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x1d\n" +
	"\n" +
	"max_events\x18\x04 \x01(\x05R\tmaxEvents\"j\n" +
	"\x19QueryUprobeEventsResponse\x122\n" +
	"\x06events\x18\x01 \x03(\v2\x1a.coral.mesh.v1.UprobeEventR\x06events\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"U\n" +
	"\x18ListDebugSessionsRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"V\n" +
	"\x19ListDebugSessionsResponse\x129\n" +
	"\bsessions\x18\x01 \x03(\v2\x1d.coral.colony.v1.DebugSessionR\bsessions\"\xe2\x02\n" +
	"\fDebugSession\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12#\n" +
	"\rfunction_name\x18\x03 \x01(\tR\ffunctionName\x12\x19\n" +
	"\bagent_id\x18\x04 \x01(\tR\aagentId\x129\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12!\n" +
	"\frequested_by\x18\b \x01(\tR\vrequestedBy\x12\x1f\n" +
	"\vevent_count\x18\t \x01(\x05R\n" +
	"eventCount2\xa0\x03\n" +
	"\fDebugService\x12[\n" +
	"\fAttachUprobe\x12$.coral.colony.v1.AttachUprobeRequest\x1a%.coral.colony.v1.AttachUprobeResponse\x12[\n" +
	"\fDetachUprobe\x12$.coral.colony.v1.DetachUprobeRequest\x1a%.coral.colony.v1.DetachUprobeResponse\x12j\n" +
	"\x11QueryUprobeEvents\x12).coral.colony.v1.QueryUprobeEventsRequest\x1a*.coral.colony.v1.QueryUprobeEventsResponse\x12j\n" +
	"\x11ListDebugSessions\x12).coral.colony.v1.ListDebugSessionsRequest\x1a*.coral.colony.v1.ListDebugSessionsResponseB\xb5\x01\n" +
	"\x13com.coral.colony.v1B\n" +
	"DebugProtoP\x01Z4github.com/coral-mesh/coral/coral/colony/v1;colonyv1\xa2\x02\x03CCX\xaa\x02\x0fCoral.Colony.V1\xca\x02\x0fCoral\\Colony\\V1\xe2\x02\x1bCoral\\Colony\\V1\\GPBMetadata\xea\x02\x11Coral::Colony::V1b\x06proto3"

var (
	file_coral_colony_v1_debug_proto_rawDescOnce sync.Once
	file_coral_colony_v1_debug_proto_rawDescData []byte
)

func file_coral_colony_v1_debug_proto_rawDescGZIP() []byte {
	file_coral_colony_v1_debug_proto_rawDescOnce.Do(func() {
		file_coral_colony_v1_debug_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coral_colony_v1_debug_proto_rawDesc), len(file_coral_colony_v1_debug_proto_rawDesc)))
	})
	return file_coral_colony_v1_debug_proto_rawDescData
}

var file_coral_colony_v1_debug_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_coral_colony_v1_debug_proto_goTypes = []any{
	(*AttachUprobeRequest)(nil),       // 0: coral.colony.v1.AttachUprobeRequest
	(*AttachUprobeResponse)(nil),      // 1: coral.colony.v1.AttachUprobeResponse
	(*DetachUprobeRequest)(nil),       // 2: coral.colony.v1.DetachUprobeRequest
	(*DetachUprobeResponse)(nil),      // 3: coral.colony.v1.DetachUprobeResponse
	(*QueryUprobeEventsRequest)(nil),  // 4: coral.colony.v1.QueryUprobeEventsRequest
	(*QueryUprobeEventsResponse)(nil), // 5: coral.colony.v1.QueryUprobeEventsResponse
	(*ListDebugSessionsRequest)(nil),  // 6: coral.colony.v1.ListDebugSessionsRequest
	(*ListDebugSessionsResponse)(nil), // 7: coral.colony.v1.ListDebugSessionsResponse
	(*DebugSession)(nil),              // 8: coral.colony.v1.DebugSession
	(*durationpb.Duration)(nil),       // 9: google.protobuf.Duration
	(*v1.UprobeConfig)(nil),           // 10: coral.mesh.v1.UprobeConfig
	(*timestamppb.Timestamp)(nil),     // 11: google.protobuf.Timestamp
	(*v1.UprobeEvent)(nil),            // 12: coral.mesh.v1.UprobeEvent
}
var file_coral_colony_v1_debug_proto_depIdxs = []int32{
	9,  // 0: coral.colony.v1.AttachUprobeRequest.duration:type_name -> google.protobuf.Duration
	10, // 1: coral.colony.v1.AttachUprobeRequest.config:type_name -> coral.mesh.v1.UprobeConfig
	11, // 2: coral.colony.v1.AttachUprobeResponse.expires_at:type_name -> google.protobuf.Timestamp
	11, // 3: coral.colony.v1.QueryUprobeEventsRequest.start_time:type_name -> google.protobuf.Timestamp
	11, // 4: coral.colony.v1.QueryUprobeEventsRequest.end_time:type_name -> google.protobuf.Timestamp
	12, // 5: coral.colony.v1.QueryUprobeEventsResponse.events:type_name -> coral.mesh.v1.UprobeEvent
	8,  // 6: coral.colony.v1.ListDebugSessionsResponse.sessions:type_name -> coral.colony.v1.DebugSession
	11, // 7: coral.colony.v1.DebugSession.started_at:type_name -> google.protobuf.Timestamp
	11, // 8: coral.colony.v1.DebugSession.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 9: coral.colony.v1.DebugService.AttachUprobe:input_type -> coral.colony.v1.AttachUprobeRequest
	2,  // 10: coral.colony.v1.DebugService.DetachUprobe:input_type -> coral.colony.v1.DetachUprobeRequest
	4,  // 11: coral.colony.v1.DebugService.QueryUprobeEvents:input_type -> coral.colony.v1.QueryUprobeEventsRequest
	6,  // 12: coral.colony.v1.DebugService.ListDebugSessions:input_type -> coral.colony.v1.ListDebugSessionsRequest
	1,  // 13: coral.colony.v1.DebugService.AttachUprobe:output_type -> coral.colony.v1.AttachUprobeResponse
	3,  // 14: coral.colony.v1.DebugService.DetachUprobe:output_type -> coral.colony.v1.DetachUprobeResponse
	5,  // 15: coral.colony.v1.DebugService.QueryUprobeEvents:output_type -> coral.colony.v1.QueryUprobeEventsResponse
	7,  // 16: coral.colony.v1.DebugService.ListDebugSessions:output_type -> coral.colony.v1.ListDebugSessionsResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_coral_colony_v1_debug_proto_init() }
func file_coral_colony_v1_debug_proto_init() {
	if File_coral_colony_v1_debug_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coral_colony_v1_debug_proto_rawDesc), len(file_coral_colony_v1_debug_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coral_colony_v1_debug_proto_goTypes,
		DependencyIndexes: file_coral_colony_v1_debug_proto_depIdxs,
		MessageInfos:      file_coral_colony_v1_debug_proto_msgTypes,
	}.Build()
	File_coral_colony_v1_debug_proto = out.File
	file_coral_colony_v1_debug_proto_goTypes = nil
	file_coral_colony_v1_debug_proto_depIdxs = nil
}
