// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: coral/colony/v1/debug.proto

package colonyv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	v1 "github.com/coral-mesh/coral/coral/mesh/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AttachUprobeRequest initiates a debug session on a specific function.
type AttachUprobeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	FunctionName  string                 `protobuf:"bytes,2,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	Duration      *durationpb.Duration   `protobuf:"bytes,3,opt,name=duration,proto3" json:"duration,omitempty"` // Default: 60s, Max: 600s
	Config        *v1.UprobeConfig       `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	AgentId       string                 `protobuf:"bytes,5,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // Manual override (until service discovery integration)
	SdkAddr       string                 `protobuf:"bytes,6,opt,name=sdk_addr,json=sdkAddr,proto3" json:"sdk_addr,omitempty"` // Manual override (until service discovery integration)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachUprobeRequest) Reset() {
	*x = AttachUprobeRequest{}
	mi := &file_coral_colony_v1_debug_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachUprobeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachUprobeRequest) ProtoMessage() {}

func (x *AttachUprobeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_debug_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachUprobeRequest.ProtoReflect.Descriptor instead.
func (*AttachUprobeRequest) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_debug_proto_rawDescGZIP(), []int{0}
}

func (x *AttachUprobeRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *AttachUprobeRequest) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *AttachUprobeRequest) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *AttachUprobeRequest) GetConfig() *v1.UprobeConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *AttachUprobeRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AttachUprobeRequest) GetSdkAddr() string {
	if x != nil {
		return x.SdkAddr
	}
	return ""
}

// AttachUprobeResponse confirms debug session creation.
type AttachUprobeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachUprobeResponse) Reset() {
	*x = AttachUprobeResponse{}
	mi := &file_coral_colony_v1_debug_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachUprobeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachUprobeResponse) ProtoMessage() {}

func (x *AttachUprobeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_debug_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachUprobeResponse.ProtoReflect.Descriptor instead.
func (*AttachUprobeResponse) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_debug_proto_rawDescGZIP(), []int{1}
}

func (x *AttachUprobeResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AttachUprobeResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *AttachUprobeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AttachUprobeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// DetachUprobeRequest stops a debug session early.
type DetachUprobeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetachUprobeRequest) Reset() {
	*x = DetachUprobeRequest{}
	mi := &file_coral_colony_v1_debug_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetachUprobeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachUprobeRequest) ProtoMessage() {}

func (x *DetachUprobeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_debug_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachUprobeRequest.ProtoReflect.Descriptor instead.
func (*DetachUprobeRequest) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_debug_proto_rawDescGZIP(), []int{2}
}

func (x *DetachUprobeRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// DetachUprobeResponse confirms session termination.
type DetachUprobeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetachUprobeResponse) Reset() {
	*x = DetachUprobeResponse{}
	mi := &file_coral_colony_v1_debug_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetachUprobeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachUprobeResponse) ProtoMessage() {}

func (x *DetachUprobeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_debug_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachUprobeResponse.ProtoReflect.Descriptor instead.
func (*DetachUprobeResponse) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_debug_proto_rawDescGZIP(), []int{3}
}

func (x *DetachUprobeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DetachUprobeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// QueryUprobeEventsRequest retrieves events from a debug session.
type QueryUprobeEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	MaxEvents     int32                  `protobuf:"varint,4,opt,name=max_events,json=maxEvents,proto3" json:"max_events,omitempty"` // Pagination
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryUprobeEventsRequest) Reset() {
	*x = QueryUprobeEventsRequest{}
	mi := &file_coral_colony_v1_debug_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUprobeEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUprobeEventsRequest) ProtoMessage() {}

func (x *QueryUprobeEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_debug_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUprobeEventsRequest.ProtoReflect.Descriptor instead.
func (*QueryUprobeEventsRequest) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_debug_proto_rawDescGZIP(), []int{4}
}

func (x *QueryUprobeEventsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *QueryUprobeEventsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *QueryUprobeEventsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *QueryUprobeEventsRequest) GetMaxEvents() int32 {
	if x != nil {
		return x.MaxEvents
	}
	return 0
}

// QueryUprobeEventsResponse returns captured events.
type QueryUprobeEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*v1.UprobeEvent      `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"` // Pagination indicator
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryUprobeEventsResponse) Reset() {
	*x = QueryUprobeEventsResponse{}
	mi := &file_coral_colony_v1_debug_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUprobeEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUprobeEventsResponse) ProtoMessage() {}

func (x *QueryUprobeEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_debug_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUprobeEventsResponse.ProtoReflect.Descriptor instead.
func (*QueryUprobeEventsResponse) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_debug_proto_rawDescGZIP(), []int{5}
}

func (x *QueryUprobeEventsResponse) GetEvents() []*v1.UprobeEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *QueryUprobeEventsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// ListDebugSessionsRequest retrieves active debug sessions.
type ListDebugSessionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional filter by service name.
	ServiceName string `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	// Optional filter by status.
	Status        string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDebugSessionsRequest) Reset() {
	*x = ListDebugSessionsRequest{}
	mi := &file_coral_colony_v1_debug_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDebugSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDebugSessionsRequest) ProtoMessage() {}

func (x *ListDebugSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_debug_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDebugSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListDebugSessionsRequest) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_debug_proto_rawDescGZIP(), []int{6}
}

func (x *ListDebugSessionsRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ListDebugSessionsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// ListDebugSessionsResponse returns active sessions.
type ListDebugSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*DebugSession        `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDebugSessionsResponse) Reset() {
	*x = ListDebugSessionsResponse{}
	mi := &file_coral_colony_v1_debug_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDebugSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDebugSessionsResponse) ProtoMessage() {}

func (x *ListDebugSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_debug_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDebugSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListDebugSessionsResponse) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_debug_proto_rawDescGZIP(), []int{7}
}

func (x *ListDebugSessionsResponse) GetSessions() []*DebugSession {
	if x != nil {
		return x.Sessions
	}
	return nil
}

// DebugSession represents an active or completed debug session.
type DebugSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	FunctionName  string                 `protobuf:"bytes,3,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	AgentId       string                 `protobuf:"bytes,4,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`                              // "active", "expired", "stopped"
	RequestedBy   string                 `protobuf:"bytes,8,opt,name=requested_by,json=requestedBy,proto3" json:"requested_by,omitempty"` // User who initiated session
	EventCount    int32                  `protobuf:"varint,9,opt,name=event_count,json=eventCount,proto3" json:"event_count,omitempty"`   // Number of events collected
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugSession) Reset() {
	*x = DebugSession{}
	mi := &file_coral_colony_v1_debug_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugSession) ProtoMessage() {}

func (x *DebugSession) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_debug_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugSession.ProtoReflect.Descriptor instead.
func (*DebugSession) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_debug_proto_rawDescGZIP(), []int{8}
}

func (x *DebugSession) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DebugSession) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *DebugSession) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *DebugSession) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *DebugSession) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *DebugSession) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *DebugSession) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DebugSession) GetRequestedBy() string {
	if x != nil {
		return x.RequestedBy
	}
	return ""
}

func (x *DebugSession) GetEventCount() int32 {
	if x != nil {
		return x.EventCount
	}
	return 0
}

// TraceRequestPathRequest initiates a request path trace.
type TraceRequestPathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Duration      *durationpb.Duration   `protobuf:"bytes,3,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceRequestPathRequest) Reset() {
	*x = TraceRequestPathRequest{}
	mi := &file_coral_colony_v1_debug_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceRequestPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceRequestPathRequest) ProtoMessage() {}

func (x *TraceRequestPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_debug_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceRequestPathRequest.ProtoReflect.Descriptor instead.
func (*TraceRequestPathRequest) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_debug_proto_rawDescGZIP(), []int{9}
}

func (x *TraceRequestPathRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *TraceRequestPathRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *TraceRequestPathRequest) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

// TraceRequestPathResponse returns the trace session details.
type TraceRequestPathResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Path      string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// Call tree and bottleneck analysis would be returned here or queried later.
	// For now, we just return the session ID as it's an async process.
	Success       bool   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Error         string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceRequestPathResponse) Reset() {
	*x = TraceRequestPathResponse{}
	mi := &file_coral_colony_v1_debug_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceRequestPathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceRequestPathResponse) ProtoMessage() {}

func (x *TraceRequestPathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_debug_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceRequestPathResponse.ProtoReflect.Descriptor instead.
func (*TraceRequestPathResponse) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_debug_proto_rawDescGZIP(), []int{10}
}

func (x *TraceRequestPathResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TraceRequestPathResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *TraceRequestPathResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TraceRequestPathResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// GetDebugResultsRequest retrieves aggregated results for a session.
type GetDebugResultsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`                              // "summary", "full", "histogram"
	ServiceName   string                 `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"` // Optional, for routing if needed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDebugResultsRequest) Reset() {
	*x = GetDebugResultsRequest{}
	mi := &file_coral_colony_v1_debug_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDebugResultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDebugResultsRequest) ProtoMessage() {}

func (x *GetDebugResultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_debug_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDebugResultsRequest.ProtoReflect.Descriptor instead.
func (*GetDebugResultsRequest) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_debug_proto_rawDescGZIP(), []int{11}
}

func (x *GetDebugResultsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetDebugResultsRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *GetDebugResultsRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

// GetDebugResultsResponse returns the aggregated results.
type GetDebugResultsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Function      string                 `protobuf:"bytes,2,opt,name=function,proto3" json:"function,omitempty"`
	Duration      *durationpb.Duration   `protobuf:"bytes,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Statistics    *DebugStatistics       `protobuf:"bytes,4,opt,name=statistics,proto3" json:"statistics,omitempty"`
	SlowOutliers  []*SlowOutlier         `protobuf:"bytes,5,rep,name=slow_outliers,json=slowOutliers,proto3" json:"slow_outliers,omitempty"`
	CallTree      *CallTree              `protobuf:"bytes,6,opt,name=call_tree,json=callTree,proto3" json:"call_tree,omitempty"` // Hierarchical call tree from uprobe events
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDebugResultsResponse) Reset() {
	*x = GetDebugResultsResponse{}
	mi := &file_coral_colony_v1_debug_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDebugResultsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDebugResultsResponse) ProtoMessage() {}

func (x *GetDebugResultsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_debug_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDebugResultsResponse.ProtoReflect.Descriptor instead.
func (*GetDebugResultsResponse) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_debug_proto_rawDescGZIP(), []int{12}
}

func (x *GetDebugResultsResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetDebugResultsResponse) GetFunction() string {
	if x != nil {
		return x.Function
	}
	return ""
}

func (x *GetDebugResultsResponse) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *GetDebugResultsResponse) GetStatistics() *DebugStatistics {
	if x != nil {
		return x.Statistics
	}
	return nil
}

func (x *GetDebugResultsResponse) GetSlowOutliers() []*SlowOutlier {
	if x != nil {
		return x.SlowOutliers
	}
	return nil
}

func (x *GetDebugResultsResponse) GetCallTree() *CallTree {
	if x != nil {
		return x.CallTree
	}
	return nil
}

type DebugStatistics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalCalls    int64                  `protobuf:"varint,1,opt,name=total_calls,json=totalCalls,proto3" json:"total_calls,omitempty"`
	DurationP50   *durationpb.Duration   `protobuf:"bytes,2,opt,name=duration_p50,json=durationP50,proto3" json:"duration_p50,omitempty"`
	DurationP95   *durationpb.Duration   `protobuf:"bytes,3,opt,name=duration_p95,json=durationP95,proto3" json:"duration_p95,omitempty"`
	DurationP99   *durationpb.Duration   `protobuf:"bytes,4,opt,name=duration_p99,json=durationP99,proto3" json:"duration_p99,omitempty"`
	DurationMax   *durationpb.Duration   `protobuf:"bytes,5,opt,name=duration_max,json=durationMax,proto3" json:"duration_max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugStatistics) Reset() {
	*x = DebugStatistics{}
	mi := &file_coral_colony_v1_debug_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugStatistics) ProtoMessage() {}

func (x *DebugStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_debug_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugStatistics.ProtoReflect.Descriptor instead.
func (*DebugStatistics) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_debug_proto_rawDescGZIP(), []int{13}
}

func (x *DebugStatistics) GetTotalCalls() int64 {
	if x != nil {
		return x.TotalCalls
	}
	return 0
}

func (x *DebugStatistics) GetDurationP50() *durationpb.Duration {
	if x != nil {
		return x.DurationP50
	}
	return nil
}

func (x *DebugStatistics) GetDurationP95() *durationpb.Duration {
	if x != nil {
		return x.DurationP95
	}
	return nil
}

func (x *DebugStatistics) GetDurationP99() *durationpb.Duration {
	if x != nil {
		return x.DurationP99
	}
	return nil
}

func (x *DebugStatistics) GetDurationMax() *durationpb.Duration {
	if x != nil {
		return x.DurationMax
	}
	return nil
}

type SlowOutlier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Duration      *durationpb.Duration   `protobuf:"bytes,1,opt,name=duration,proto3" json:"duration,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlowOutlier) Reset() {
	*x = SlowOutlier{}
	mi := &file_coral_colony_v1_debug_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlowOutlier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlowOutlier) ProtoMessage() {}

func (x *SlowOutlier) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_debug_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlowOutlier.ProtoReflect.Descriptor instead.
func (*SlowOutlier) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_debug_proto_rawDescGZIP(), []int{14}
}

func (x *SlowOutlier) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *SlowOutlier) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *SlowOutlier) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// CallTree represents the root of a hierarchical call tree.
type CallTree struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Root             *CallTreeNode          `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	TotalInvocations int64                  `protobuf:"varint,2,opt,name=total_invocations,json=totalInvocations,proto3" json:"total_invocations,omitempty"` // Number of complete call trees captured
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CallTree) Reset() {
	*x = CallTree{}
	mi := &file_coral_colony_v1_debug_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallTree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallTree) ProtoMessage() {}

func (x *CallTree) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_debug_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallTree.ProtoReflect.Descriptor instead.
func (*CallTree) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_debug_proto_rawDescGZIP(), []int{15}
}

func (x *CallTree) GetRoot() *CallTreeNode {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *CallTree) GetTotalInvocations() int64 {
	if x != nil {
		return x.TotalInvocations
	}
	return 0
}

// CallTreeNode represents a node in the call tree hierarchy.
type CallTreeNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FunctionName  string                 `protobuf:"bytes,1,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	TotalDuration *durationpb.Duration   `protobuf:"bytes,2,opt,name=total_duration,json=totalDuration,proto3" json:"total_duration,omitempty"` // Total time including children
	SelfDuration  *durationpb.Duration   `protobuf:"bytes,3,opt,name=self_duration,json=selfDuration,proto3" json:"self_duration,omitempty"`    // Time in this function only
	CallCount     int64                  `protobuf:"varint,4,opt,name=call_count,json=callCount,proto3" json:"call_count,omitempty"`            // Number of times this function was called
	Children      []*CallTreeNode        `protobuf:"bytes,5,rep,name=children,proto3" json:"children,omitempty"`                                // Child function calls
	IsSlow        bool                   `protobuf:"varint,6,opt,name=is_slow,json=isSlow,proto3" json:"is_slow,omitempty"`                     // Exceeds P95 threshold
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallTreeNode) Reset() {
	*x = CallTreeNode{}
	mi := &file_coral_colony_v1_debug_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallTreeNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallTreeNode) ProtoMessage() {}

func (x *CallTreeNode) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_debug_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallTreeNode.ProtoReflect.Descriptor instead.
func (*CallTreeNode) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_debug_proto_rawDescGZIP(), []int{16}
}

func (x *CallTreeNode) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *CallTreeNode) GetTotalDuration() *durationpb.Duration {
	if x != nil {
		return x.TotalDuration
	}
	return nil
}

func (x *CallTreeNode) GetSelfDuration() *durationpb.Duration {
	if x != nil {
		return x.SelfDuration
	}
	return nil
}

func (x *CallTreeNode) GetCallCount() int64 {
	if x != nil {
		return x.CallCount
	}
	return 0
}

func (x *CallTreeNode) GetChildren() []*CallTreeNode {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *CallTreeNode) GetIsSlow() bool {
	if x != nil {
		return x.IsSlow
	}
	return false
}

var File_coral_colony_v1_debug_proto protoreflect.FileDescriptor

const file_coral_colony_v1_debug_proto_rawDesc = "" +
	"\n" +
	"\x1bcoral/colony/v1/debug.proto\x12\x0fcoral.colony.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x18coral/mesh/v1/ebpf.proto\"\xff\x01\n" +
	"\x13AttachUprobeRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12#\n" +
	"\rfunction_name\x18\x02 \x01(\tR\ffunctionName\x125\n" +
	"\bduration\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\bduration\x123\n" +
	"\x06config\x18\x04 \x01(\v2\x1b.coral.mesh.v1.UprobeConfigR\x06config\x12\x19\n" +
	"\bagent_id\x18\x05 \x01(\tR\aagentId\x12\x19\n" +
	"\bsdk_addr\x18\x06 \x01(\tR\asdkAddr\"\xa0\x01\n" +
	"\x14AttachUprobeResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"4\n" +
	"\x13DetachUprobeRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"F\n" +
	"\x14DetachUprobeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xca\x01\n" +
	"\x18QueryUprobeEventsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x1d\n" +
	"\n" +
	"max_events\x18\x04 \x01(\x05R\tmaxEvents\"j\n" +
	"\x19QueryUprobeEventsResponse\x122\n" +
	"\x06events\x18\x01 \x03(\v2\x1a.coral.mesh.v1.UprobeEventR\x06events\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"U\n" +
	"\x18ListDebugSessionsRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"V\n" +
	"\x19ListDebugSessionsResponse\x129\n" +
	"\bsessions\x18\x01 \x03(\v2\x1d.coral.colony.v1.DebugSessionR\bsessions\"\xe2\x02\n" +
	"\fDebugSession\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12#\n" +
	"\rfunction_name\x18\x03 \x01(\tR\ffunctionName\x12\x19\n" +
	"\bagent_id\x18\x04 \x01(\tR\aagentId\x129\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12!\n" +
	"\frequested_by\x18\b \x01(\tR\vrequestedBy\x12\x1f\n" +
	"\vevent_count\x18\t \x01(\x05R\n" +
	"eventCount\"\x87\x01\n" +
	"\x17TraceRequestPathRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x125\n" +
	"\bduration\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\bduration\"}\n" +
	"\x18TraceRequestPathResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"r\n" +
	"\x16GetDebugResultsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\"\xc8\x02\n" +
	"\x17GetDebugResultsResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bfunction\x18\x02 \x01(\tR\bfunction\x125\n" +
	"\bduration\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\bduration\x12@\n" +
	"\n" +
	"statistics\x18\x04 \x01(\v2 .coral.colony.v1.DebugStatisticsR\n" +
	"statistics\x12A\n" +
	"\rslow_outliers\x18\x05 \x03(\v2\x1c.coral.colony.v1.SlowOutlierR\fslowOutliers\x126\n" +
	"\tcall_tree\x18\x06 \x01(\v2\x19.coral.colony.v1.CallTreeR\bcallTree\"\xaa\x02\n" +
	"\x0fDebugStatistics\x12\x1f\n" +
	"\vtotal_calls\x18\x01 \x01(\x03R\n" +
	"totalCalls\x12<\n" +
	"\fduration_p50\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\vdurationP50\x12<\n" +
	"\fduration_p95\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\vdurationP95\x12<\n" +
	"\fduration_p99\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\vdurationP99\x12<\n" +
	"\fduration_max\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\vdurationMax\"\xfb\x01\n" +
	"\vSlowOutlier\x125\n" +
	"\bduration\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\bduration\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12@\n" +
	"\x06labels\x18\x03 \x03(\v2(.coral.colony.v1.SlowOutlier.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"j\n" +
	"\bCallTree\x121\n" +
	"\x04root\x18\x01 \x01(\v2\x1d.coral.colony.v1.CallTreeNodeR\x04root\x12+\n" +
	"\x11total_invocations\x18\x02 \x01(\x03R\x10totalInvocations\"\xa8\x02\n" +
	"\fCallTreeNode\x12#\n" +
	"\rfunction_name\x18\x01 \x01(\tR\ffunctionName\x12@\n" +
	"\x0etotal_duration\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\rtotalDuration\x12>\n" +
	"\rself_duration\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\fselfDuration\x12\x1d\n" +
	"\n" +
	"call_count\x18\x04 \x01(\x03R\tcallCount\x129\n" +
	"\bchildren\x18\x05 \x03(\v2\x1d.coral.colony.v1.CallTreeNodeR\bchildren\x12\x17\n" +
	"\ais_slow\x18\x06 \x01(\bR\x06isSlow2\xef\x04\n" +
	"\fDebugService\x12[\n" +
	"\fAttachUprobe\x12$.coral.colony.v1.AttachUprobeRequest\x1a%.coral.colony.v1.AttachUprobeResponse\x12[\n" +
	"\fDetachUprobe\x12$.coral.colony.v1.DetachUprobeRequest\x1a%.coral.colony.v1.DetachUprobeResponse\x12j\n" +
	"\x11QueryUprobeEvents\x12).coral.colony.v1.QueryUprobeEventsRequest\x1a*.coral.colony.v1.QueryUprobeEventsResponse\x12j\n" +
	"\x11ListDebugSessions\x12).coral.colony.v1.ListDebugSessionsRequest\x1a*.coral.colony.v1.ListDebugSessionsResponse\x12g\n" +
	"\x10TraceRequestPath\x12(.coral.colony.v1.TraceRequestPathRequest\x1a).coral.colony.v1.TraceRequestPathResponse\x12d\n" +
	"\x0fGetDebugResults\x12'.coral.colony.v1.GetDebugResultsRequest\x1a(.coral.colony.v1.GetDebugResultsResponseB\xb5\x01\n" +
	"\x13com.coral.colony.v1B\n" +
	"DebugProtoP\x01Z4github.com/coral-mesh/coral/coral/colony/v1;colonyv1\xa2\x02\x03CCX\xaa\x02\x0fCoral.Colony.V1\xca\x02\x0fCoral\\Colony\\V1\xe2\x02\x1bCoral\\Colony\\V1\\GPBMetadata\xea\x02\x11Coral::Colony::V1b\x06proto3"

var (
	file_coral_colony_v1_debug_proto_rawDescOnce sync.Once
	file_coral_colony_v1_debug_proto_rawDescData []byte
)

func file_coral_colony_v1_debug_proto_rawDescGZIP() []byte {
	file_coral_colony_v1_debug_proto_rawDescOnce.Do(func() {
		file_coral_colony_v1_debug_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coral_colony_v1_debug_proto_rawDesc), len(file_coral_colony_v1_debug_proto_rawDesc)))
	})
	return file_coral_colony_v1_debug_proto_rawDescData
}

var file_coral_colony_v1_debug_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_coral_colony_v1_debug_proto_goTypes = []any{
	(*AttachUprobeRequest)(nil),       // 0: coral.colony.v1.AttachUprobeRequest
	(*AttachUprobeResponse)(nil),      // 1: coral.colony.v1.AttachUprobeResponse
	(*DetachUprobeRequest)(nil),       // 2: coral.colony.v1.DetachUprobeRequest
	(*DetachUprobeResponse)(nil),      // 3: coral.colony.v1.DetachUprobeResponse
	(*QueryUprobeEventsRequest)(nil),  // 4: coral.colony.v1.QueryUprobeEventsRequest
	(*QueryUprobeEventsResponse)(nil), // 5: coral.colony.v1.QueryUprobeEventsResponse
	(*ListDebugSessionsRequest)(nil),  // 6: coral.colony.v1.ListDebugSessionsRequest
	(*ListDebugSessionsResponse)(nil), // 7: coral.colony.v1.ListDebugSessionsResponse
	(*DebugSession)(nil),              // 8: coral.colony.v1.DebugSession
	(*TraceRequestPathRequest)(nil),   // 9: coral.colony.v1.TraceRequestPathRequest
	(*TraceRequestPathResponse)(nil),  // 10: coral.colony.v1.TraceRequestPathResponse
	(*GetDebugResultsRequest)(nil),    // 11: coral.colony.v1.GetDebugResultsRequest
	(*GetDebugResultsResponse)(nil),   // 12: coral.colony.v1.GetDebugResultsResponse
	(*DebugStatistics)(nil),           // 13: coral.colony.v1.DebugStatistics
	(*SlowOutlier)(nil),               // 14: coral.colony.v1.SlowOutlier
	(*CallTree)(nil),                  // 15: coral.colony.v1.CallTree
	(*CallTreeNode)(nil),              // 16: coral.colony.v1.CallTreeNode
	nil,                               // 17: coral.colony.v1.SlowOutlier.LabelsEntry
	(*durationpb.Duration)(nil),       // 18: google.protobuf.Duration
	(*v1.UprobeConfig)(nil),           // 19: coral.mesh.v1.UprobeConfig
	(*timestamppb.Timestamp)(nil),     // 20: google.protobuf.Timestamp
	(*v1.UprobeEvent)(nil),            // 21: coral.mesh.v1.UprobeEvent
}
var file_coral_colony_v1_debug_proto_depIdxs = []int32{
	18, // 0: coral.colony.v1.AttachUprobeRequest.duration:type_name -> google.protobuf.Duration
	19, // 1: coral.colony.v1.AttachUprobeRequest.config:type_name -> coral.mesh.v1.UprobeConfig
	20, // 2: coral.colony.v1.AttachUprobeResponse.expires_at:type_name -> google.protobuf.Timestamp
	20, // 3: coral.colony.v1.QueryUprobeEventsRequest.start_time:type_name -> google.protobuf.Timestamp
	20, // 4: coral.colony.v1.QueryUprobeEventsRequest.end_time:type_name -> google.protobuf.Timestamp
	21, // 5: coral.colony.v1.QueryUprobeEventsResponse.events:type_name -> coral.mesh.v1.UprobeEvent
	8,  // 6: coral.colony.v1.ListDebugSessionsResponse.sessions:type_name -> coral.colony.v1.DebugSession
	20, // 7: coral.colony.v1.DebugSession.started_at:type_name -> google.protobuf.Timestamp
	20, // 8: coral.colony.v1.DebugSession.expires_at:type_name -> google.protobuf.Timestamp
	18, // 9: coral.colony.v1.TraceRequestPathRequest.duration:type_name -> google.protobuf.Duration
	18, // 10: coral.colony.v1.GetDebugResultsResponse.duration:type_name -> google.protobuf.Duration
	13, // 11: coral.colony.v1.GetDebugResultsResponse.statistics:type_name -> coral.colony.v1.DebugStatistics
	14, // 12: coral.colony.v1.GetDebugResultsResponse.slow_outliers:type_name -> coral.colony.v1.SlowOutlier
	15, // 13: coral.colony.v1.GetDebugResultsResponse.call_tree:type_name -> coral.colony.v1.CallTree
	18, // 14: coral.colony.v1.DebugStatistics.duration_p50:type_name -> google.protobuf.Duration
	18, // 15: coral.colony.v1.DebugStatistics.duration_p95:type_name -> google.protobuf.Duration
	18, // 16: coral.colony.v1.DebugStatistics.duration_p99:type_name -> google.protobuf.Duration
	18, // 17: coral.colony.v1.DebugStatistics.duration_max:type_name -> google.protobuf.Duration
	18, // 18: coral.colony.v1.SlowOutlier.duration:type_name -> google.protobuf.Duration
	20, // 19: coral.colony.v1.SlowOutlier.timestamp:type_name -> google.protobuf.Timestamp
	17, // 20: coral.colony.v1.SlowOutlier.labels:type_name -> coral.colony.v1.SlowOutlier.LabelsEntry
	16, // 21: coral.colony.v1.CallTree.root:type_name -> coral.colony.v1.CallTreeNode
	18, // 22: coral.colony.v1.CallTreeNode.total_duration:type_name -> google.protobuf.Duration
	18, // 23: coral.colony.v1.CallTreeNode.self_duration:type_name -> google.protobuf.Duration
	16, // 24: coral.colony.v1.CallTreeNode.children:type_name -> coral.colony.v1.CallTreeNode
	0,  // 25: coral.colony.v1.DebugService.AttachUprobe:input_type -> coral.colony.v1.AttachUprobeRequest
	2,  // 26: coral.colony.v1.DebugService.DetachUprobe:input_type -> coral.colony.v1.DetachUprobeRequest
	4,  // 27: coral.colony.v1.DebugService.QueryUprobeEvents:input_type -> coral.colony.v1.QueryUprobeEventsRequest
	6,  // 28: coral.colony.v1.DebugService.ListDebugSessions:input_type -> coral.colony.v1.ListDebugSessionsRequest
	9,  // 29: coral.colony.v1.DebugService.TraceRequestPath:input_type -> coral.colony.v1.TraceRequestPathRequest
	11, // 30: coral.colony.v1.DebugService.GetDebugResults:input_type -> coral.colony.v1.GetDebugResultsRequest
	1,  // 31: coral.colony.v1.DebugService.AttachUprobe:output_type -> coral.colony.v1.AttachUprobeResponse
	3,  // 32: coral.colony.v1.DebugService.DetachUprobe:output_type -> coral.colony.v1.DetachUprobeResponse
	5,  // 33: coral.colony.v1.DebugService.QueryUprobeEvents:output_type -> coral.colony.v1.QueryUprobeEventsResponse
	7,  // 34: coral.colony.v1.DebugService.ListDebugSessions:output_type -> coral.colony.v1.ListDebugSessionsResponse
	10, // 35: coral.colony.v1.DebugService.TraceRequestPath:output_type -> coral.colony.v1.TraceRequestPathResponse
	12, // 36: coral.colony.v1.DebugService.GetDebugResults:output_type -> coral.colony.v1.GetDebugResultsResponse
	31, // [31:37] is the sub-list for method output_type
	25, // [25:31] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_coral_colony_v1_debug_proto_init() }
func file_coral_colony_v1_debug_proto_init() {
	if File_coral_colony_v1_debug_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coral_colony_v1_debug_proto_rawDesc), len(file_coral_colony_v1_debug_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coral_colony_v1_debug_proto_goTypes,
		DependencyIndexes: file_coral_colony_v1_debug_proto_depIdxs,
		MessageInfos:      file_coral_colony_v1_debug_proto_msgTypes,
	}.Build()
	File_coral_colony_v1_debug_proto = out.File
	file_coral_colony_v1_debug_proto_goTypes = nil
	file_coral_colony_v1_debug_proto_depIdxs = nil
}
