// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: coral/colony/v1/mcp.proto

package colonyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CallToolRequest is sent from CLI/proxy to colony to execute an MCP tool.
type CallToolRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tool name (e.g., "coral_query_beyla_http_metrics").
	ToolName string `protobuf:"bytes,1,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	// Tool arguments as JSON string.
	// The JSON structure depends on the specific tool being called.
	ArgumentsJson string `protobuf:"bytes,2,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallToolRequest) Reset() {
	*x = CallToolRequest{}
	mi := &file_coral_colony_v1_mcp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallToolRequest) ProtoMessage() {}

func (x *CallToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_mcp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallToolRequest.ProtoReflect.Descriptor instead.
func (*CallToolRequest) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_mcp_proto_rawDescGZIP(), []int{0}
}

func (x *CallToolRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *CallToolRequest) GetArgumentsJson() string {
	if x != nil {
		return x.ArgumentsJson
	}
	return ""
}

// CallToolResponse contains the result of executing an MCP tool.
type CallToolResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Result from the tool (formatted text for LLM consumption).
	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	// Error message if the tool failed.
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Whether the tool executed successfully.
	Success       bool `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallToolResponse) Reset() {
	*x = CallToolResponse{}
	mi := &file_coral_colony_v1_mcp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallToolResponse) ProtoMessage() {}

func (x *CallToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_mcp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallToolResponse.ProtoReflect.Descriptor instead.
func (*CallToolResponse) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_mcp_proto_rawDescGZIP(), []int{1}
}

func (x *CallToolResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *CallToolResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CallToolResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// StreamToolRequest is sent for streaming tool execution (bidirectional).
type StreamToolRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tool name.
	ToolName string `protobuf:"bytes,1,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	// Tool arguments as JSON string.
	ArgumentsJson string `protobuf:"bytes,2,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamToolRequest) Reset() {
	*x = StreamToolRequest{}
	mi := &file_coral_colony_v1_mcp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamToolRequest) ProtoMessage() {}

func (x *StreamToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_mcp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamToolRequest.ProtoReflect.Descriptor instead.
func (*StreamToolRequest) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_mcp_proto_rawDescGZIP(), []int{2}
}

func (x *StreamToolRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *StreamToolRequest) GetArgumentsJson() string {
	if x != nil {
		return x.ArgumentsJson
	}
	return ""
}

// StreamToolResponse contains streaming chunks from tool execution.
type StreamToolResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Partial result chunk.
	Chunk string `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	// Whether this is the final chunk.
	IsFinal bool `protobuf:"varint,2,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	// Error message if failed.
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamToolResponse) Reset() {
	*x = StreamToolResponse{}
	mi := &file_coral_colony_v1_mcp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamToolResponse) ProtoMessage() {}

func (x *StreamToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_mcp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamToolResponse.ProtoReflect.Descriptor instead.
func (*StreamToolResponse) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_mcp_proto_rawDescGZIP(), []int{3}
}

func (x *StreamToolResponse) GetChunk() string {
	if x != nil {
		return x.Chunk
	}
	return ""
}

func (x *StreamToolResponse) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *StreamToolResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ListToolsRequest is sent to get the list of available MCP tools.
type ListToolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsRequest) Reset() {
	*x = ListToolsRequest{}
	mi := &file_coral_colony_v1_mcp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsRequest) ProtoMessage() {}

func (x *ListToolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_mcp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsRequest.ProtoReflect.Descriptor instead.
func (*ListToolsRequest) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_mcp_proto_rawDescGZIP(), []int{4}
}

// ListToolsResponse contains the list of available tools.
type ListToolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tools         []*ToolInfo            `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsResponse) Reset() {
	*x = ListToolsResponse{}
	mi := &file_coral_colony_v1_mcp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsResponse) ProtoMessage() {}

func (x *ListToolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_mcp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsResponse.ProtoReflect.Descriptor instead.
func (*ListToolsResponse) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_mcp_proto_rawDescGZIP(), []int{5}
}

func (x *ListToolsResponse) GetTools() []*ToolInfo {
	if x != nil {
		return x.Tools
	}
	return nil
}

// ToolInfo describes an MCP tool.
type ToolInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tool name (e.g., "coral_query_beyla_http_metrics").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Tool description.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Whether the tool is enabled.
	Enabled bool `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Input schema as JSON string (JSON Schema format).
	// This defines the parameters the tool accepts.
	InputSchemaJson string `protobuf:"bytes,4,opt,name=input_schema_json,json=inputSchemaJson,proto3" json:"input_schema_json,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ToolInfo) Reset() {
	*x = ToolInfo{}
	mi := &file_coral_colony_v1_mcp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolInfo) ProtoMessage() {}

func (x *ToolInfo) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_mcp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolInfo.ProtoReflect.Descriptor instead.
func (*ToolInfo) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_mcp_proto_rawDescGZIP(), []int{6}
}

func (x *ToolInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolInfo) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ToolInfo) GetInputSchemaJson() string {
	if x != nil {
		return x.InputSchemaJson
	}
	return ""
}

var File_coral_colony_v1_mcp_proto protoreflect.FileDescriptor

const file_coral_colony_v1_mcp_proto_rawDesc = "" +
	"\n" +
	"\x19coral/colony/v1/mcp.proto\x12\x0fcoral.colony.v1\"U\n" +
	"\x0fCallToolRequest\x12\x1b\n" +
	"\ttool_name\x18\x01 \x01(\tR\btoolName\x12%\n" +
	"\x0earguments_json\x18\x02 \x01(\tR\rargumentsJson\"Z\n" +
	"\x10CallToolResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"W\n" +
	"\x11StreamToolRequest\x12\x1b\n" +
	"\ttool_name\x18\x01 \x01(\tR\btoolName\x12%\n" +
	"\x0earguments_json\x18\x02 \x01(\tR\rargumentsJson\"[\n" +
	"\x12StreamToolResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\tR\x05chunk\x12\x19\n" +
	"\bis_final\x18\x02 \x01(\bR\aisFinal\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x12\n" +
	"\x10ListToolsRequest\"D\n" +
	"\x11ListToolsResponse\x12/\n" +
	"\x05tools\x18\x01 \x03(\v2\x19.coral.colony.v1.ToolInfoR\x05tools\"\x86\x01\n" +
	"\bToolInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\x12*\n" +
	"\x11input_schema_json\x18\x04 \x01(\tR\x0finputSchemaJsonB\xb1\x01\n" +
	"\x13com.coral.colony.v1B\bMcpProtoP\x01Z2github.com/coral-io/coral/coral/colony/v1;colonyv1\xa2\x02\x03CCX\xaa\x02\x0fCoral.Colony.V1\xca\x02\x0fCoral\\Colony\\V1\xe2\x02\x1bCoral\\Colony\\V1\\GPBMetadata\xea\x02\x11Coral::Colony::V1b\x06proto3"

var (
	file_coral_colony_v1_mcp_proto_rawDescOnce sync.Once
	file_coral_colony_v1_mcp_proto_rawDescData []byte
)

func file_coral_colony_v1_mcp_proto_rawDescGZIP() []byte {
	file_coral_colony_v1_mcp_proto_rawDescOnce.Do(func() {
		file_coral_colony_v1_mcp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coral_colony_v1_mcp_proto_rawDesc), len(file_coral_colony_v1_mcp_proto_rawDesc)))
	})
	return file_coral_colony_v1_mcp_proto_rawDescData
}

var file_coral_colony_v1_mcp_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_coral_colony_v1_mcp_proto_goTypes = []any{
	(*CallToolRequest)(nil),    // 0: coral.colony.v1.CallToolRequest
	(*CallToolResponse)(nil),   // 1: coral.colony.v1.CallToolResponse
	(*StreamToolRequest)(nil),  // 2: coral.colony.v1.StreamToolRequest
	(*StreamToolResponse)(nil), // 3: coral.colony.v1.StreamToolResponse
	(*ListToolsRequest)(nil),   // 4: coral.colony.v1.ListToolsRequest
	(*ListToolsResponse)(nil),  // 5: coral.colony.v1.ListToolsResponse
	(*ToolInfo)(nil),           // 6: coral.colony.v1.ToolInfo
}
var file_coral_colony_v1_mcp_proto_depIdxs = []int32{
	6, // 0: coral.colony.v1.ListToolsResponse.tools:type_name -> coral.colony.v1.ToolInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_coral_colony_v1_mcp_proto_init() }
func file_coral_colony_v1_mcp_proto_init() {
	if File_coral_colony_v1_mcp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coral_colony_v1_mcp_proto_rawDesc), len(file_coral_colony_v1_mcp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_coral_colony_v1_mcp_proto_goTypes,
		DependencyIndexes: file_coral_colony_v1_mcp_proto_depIdxs,
		MessageInfos:      file_coral_colony_v1_mcp_proto_msgTypes,
	}.Build()
	File_coral_colony_v1_mcp_proto = out.File
	file_coral_colony_v1_mcp_proto_goTypes = nil
	file_coral_colony_v1_mcp_proto_depIdxs = nil
}
