// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: coral/colony/v1/queries.proto

package colonyv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	v1 "github.com/coral-mesh/coral/coral/agent/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Type of performance regression detected (RFD 074).
type RegressionType int32

const (
	// Function not in baseline top-K.
	RegressionType_REGRESSION_TYPE_NEW_HOTSPOT RegressionType = 0
	// Function increased >10 percentage points.
	RegressionType_REGRESSION_TYPE_INCREASED_HOTSPOT RegressionType = 1
	// Function decreased >10 percentage points (optimization).
	RegressionType_REGRESSION_TYPE_DECREASED_HOTSPOT RegressionType = 2
)

// Enum value maps for RegressionType.
var (
	RegressionType_name = map[int32]string{
		0: "REGRESSION_TYPE_NEW_HOTSPOT",
		1: "REGRESSION_TYPE_INCREASED_HOTSPOT",
		2: "REGRESSION_TYPE_DECREASED_HOTSPOT",
	}
	RegressionType_value = map[string]int32{
		"REGRESSION_TYPE_NEW_HOTSPOT":       0,
		"REGRESSION_TYPE_INCREASED_HOTSPOT": 1,
		"REGRESSION_TYPE_DECREASED_HOTSPOT": 2,
	}
)

func (x RegressionType) Enum() *RegressionType {
	p := new(RegressionType)
	*p = x
	return p
}

func (x RegressionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegressionType) Descriptor() protoreflect.EnumDescriptor {
	return file_coral_colony_v1_queries_proto_enumTypes[0].Descriptor()
}

func (RegressionType) Type() protoreflect.EnumType {
	return &file_coral_colony_v1_queries_proto_enumTypes[0]
}

func (x RegressionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegressionType.Descriptor instead.
func (RegressionType) EnumDescriptor() ([]byte, []int) {
	return file_coral_colony_v1_queries_proto_rawDescGZIP(), []int{0}
}

// ServiceSource indicates where service information originated (RFD 084).
type ServiceSource int32

const (
	ServiceSource_SERVICE_SOURCE_UNSPECIFIED ServiceSource = 0
	// Service is explicitly registered via ConnectService API.
	ServiceSource_SERVICE_SOURCE_REGISTERED ServiceSource = 1
	// Service is auto-observed from telemetry data only.
	ServiceSource_SERVICE_SOURCE_OBSERVED ServiceSource = 2
	// Service is verified (both registered AND has telemetry data).
	ServiceSource_SERVICE_SOURCE_VERIFIED ServiceSource = 3
)

// Enum value maps for ServiceSource.
var (
	ServiceSource_name = map[int32]string{
		0: "SERVICE_SOURCE_UNSPECIFIED",
		1: "SERVICE_SOURCE_REGISTERED",
		2: "SERVICE_SOURCE_OBSERVED",
		3: "SERVICE_SOURCE_VERIFIED",
	}
	ServiceSource_value = map[string]int32{
		"SERVICE_SOURCE_UNSPECIFIED": 0,
		"SERVICE_SOURCE_REGISTERED":  1,
		"SERVICE_SOURCE_OBSERVED":    2,
		"SERVICE_SOURCE_VERIFIED":    3,
	}
)

func (x ServiceSource) Enum() *ServiceSource {
	p := new(ServiceSource)
	*p = x
	return p
}

func (x ServiceSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceSource) Descriptor() protoreflect.EnumDescriptor {
	return file_coral_colony_v1_queries_proto_enumTypes[1].Descriptor()
}

func (ServiceSource) Type() protoreflect.EnumType {
	return &file_coral_colony_v1_queries_proto_enumTypes[1]
}

func (x ServiceSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceSource.Descriptor instead.
func (ServiceSource) EnumDescriptor() ([]byte, []int) {
	return file_coral_colony_v1_queries_proto_rawDescGZIP(), []int{1}
}

// ServiceStatus indicates the current registration and health status (RFD 084).
type ServiceStatus int32

const (
	ServiceStatus_SERVICE_STATUS_UNSPECIFIED ServiceStatus = 0
	// Service is registered and passing health checks.
	ServiceStatus_SERVICE_STATUS_ACTIVE ServiceStatus = 1
	// Service is registered but health checks are failing.
	ServiceStatus_SERVICE_STATUS_UNHEALTHY ServiceStatus = 2
	// Service is no longer registered but has recent telemetry.
	ServiceStatus_SERVICE_STATUS_DISCONNECTED ServiceStatus = 3
	// Service is only observed from telemetry, never explicitly registered.
	ServiceStatus_SERVICE_STATUS_OBSERVED_ONLY ServiceStatus = 4
)

// Enum value maps for ServiceStatus.
var (
	ServiceStatus_name = map[int32]string{
		0: "SERVICE_STATUS_UNSPECIFIED",
		1: "SERVICE_STATUS_ACTIVE",
		2: "SERVICE_STATUS_UNHEALTHY",
		3: "SERVICE_STATUS_DISCONNECTED",
		4: "SERVICE_STATUS_OBSERVED_ONLY",
	}
	ServiceStatus_value = map[string]int32{
		"SERVICE_STATUS_UNSPECIFIED":   0,
		"SERVICE_STATUS_ACTIVE":        1,
		"SERVICE_STATUS_UNHEALTHY":     2,
		"SERVICE_STATUS_DISCONNECTED":  3,
		"SERVICE_STATUS_OBSERVED_ONLY": 4,
	}
)

func (x ServiceStatus) Enum() *ServiceStatus {
	p := new(ServiceStatus)
	*p = x
	return p
}

func (x ServiceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_coral_colony_v1_queries_proto_enumTypes[2].Descriptor()
}

func (ServiceStatus) Type() protoreflect.EnumType {
	return &file_coral_colony_v1_queries_proto_enumTypes[2]
}

func (x ServiceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceStatus.Descriptor instead.
func (ServiceStatus) EnumDescriptor() ([]byte, []int) {
	return file_coral_colony_v1_queries_proto_rawDescGZIP(), []int{2}
}

type QueryUnifiedSummaryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: specific service or all services.
	Service string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	// Time range (e.g., "5m", "1h").
	TimeRange string `protobuf:"bytes,2,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	// Include CPU profiling hotspots in summary (RFD 074). Default: true.
	IncludeProfiling bool `protobuf:"varint,3,opt,name=include_profiling,json=includeProfiling,proto3" json:"include_profiling,omitempty"`
	// Number of top CPU hotspots to include (RFD 074). Default: 5, max: 20.
	TopKHotspots  int32 `protobuf:"varint,4,opt,name=top_k_hotspots,json=topKHotspots,proto3" json:"top_k_hotspots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryUnifiedSummaryRequest) Reset() {
	*x = QueryUnifiedSummaryRequest{}
	mi := &file_coral_colony_v1_queries_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUnifiedSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUnifiedSummaryRequest) ProtoMessage() {}

func (x *QueryUnifiedSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_queries_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUnifiedSummaryRequest.ProtoReflect.Descriptor instead.
func (*QueryUnifiedSummaryRequest) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_queries_proto_rawDescGZIP(), []int{0}
}

func (x *QueryUnifiedSummaryRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *QueryUnifiedSummaryRequest) GetTimeRange() string {
	if x != nil {
		return x.TimeRange
	}
	return ""
}

func (x *QueryUnifiedSummaryRequest) GetIncludeProfiling() bool {
	if x != nil {
		return x.IncludeProfiling
	}
	return false
}

func (x *QueryUnifiedSummaryRequest) GetTopKHotspots() int32 {
	if x != nil {
		return x.TopKHotspots
	}
	return 0
}

type UnifiedSummaryResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Service name.
	ServiceName string `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	// Health status: healthy, degraded, critical.
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// Total requests/spans.
	RequestCount int64 `protobuf:"varint,3,opt,name=request_count,json=requestCount,proto3" json:"request_count,omitempty"`
	// Error rate as percentage (0-100).
	ErrorRate float64 `protobuf:"fixed64,4,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"`
	// Average latency in milliseconds.
	AvgLatencyMs float64 `protobuf:"fixed64,5,opt,name=avg_latency_ms,json=avgLatencyMs,proto3" json:"avg_latency_ms,omitempty"`
	// Data source: eBPF, OTLP, or eBPF+OTLP.
	Source string `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	// Issues detected (human-readable descriptions).
	Issues []string `protobuf:"bytes,7,rep,name=issues,proto3" json:"issues,omitempty"`
	// Host resources (RFD 071).
	HostCpuUtilization    float64 `protobuf:"fixed64,8,opt,name=host_cpu_utilization,json=hostCpuUtilization,proto3" json:"host_cpu_utilization,omitempty"`            // CPU utilization percentage (max in time window)
	HostCpuUtilizationAvg float64 `protobuf:"fixed64,9,opt,name=host_cpu_utilization_avg,json=hostCpuUtilizationAvg,proto3" json:"host_cpu_utilization_avg,omitempty"` // CPU utilization percentage (average in time window)
	HostMemoryUsageGb     float64 `protobuf:"fixed64,10,opt,name=host_memory_usage_gb,json=hostMemoryUsageGb,proto3" json:"host_memory_usage_gb,omitempty"`            // Memory usage in GB (max in time window)
	HostMemoryLimitGb     float64 `protobuf:"fixed64,11,opt,name=host_memory_limit_gb,json=hostMemoryLimitGb,proto3" json:"host_memory_limit_gb,omitempty"`            // Memory limit in GB
	HostMemoryUtilization float64 `protobuf:"fixed64,12,opt,name=host_memory_utilization,json=hostMemoryUtilization,proto3" json:"host_memory_utilization,omitempty"`  // Memory utilization percentage (max in time window)
	AgentId               string  `protobuf:"bytes,13,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`                                                // Agent ID for correlation
	// CPU profiling summary (RFD 074).
	ProfilingSummary *ProfilingSummary `protobuf:"bytes,14,opt,name=profiling_summary,json=profilingSummary,proto3" json:"profiling_summary,omitempty"`
	// Deployment context (RFD 074).
	Deployment *DeploymentContext `protobuf:"bytes,15,opt,name=deployment,proto3" json:"deployment,omitempty"`
	// Regression indicators compared to previous deployment (RFD 074).
	Regressions   []*RegressionIndicator `protobuf:"bytes,16,rep,name=regressions,proto3" json:"regressions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnifiedSummaryResult) Reset() {
	*x = UnifiedSummaryResult{}
	mi := &file_coral_colony_v1_queries_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnifiedSummaryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnifiedSummaryResult) ProtoMessage() {}

func (x *UnifiedSummaryResult) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_queries_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnifiedSummaryResult.ProtoReflect.Descriptor instead.
func (*UnifiedSummaryResult) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_queries_proto_rawDescGZIP(), []int{1}
}

func (x *UnifiedSummaryResult) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *UnifiedSummaryResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UnifiedSummaryResult) GetRequestCount() int64 {
	if x != nil {
		return x.RequestCount
	}
	return 0
}

func (x *UnifiedSummaryResult) GetErrorRate() float64 {
	if x != nil {
		return x.ErrorRate
	}
	return 0
}

func (x *UnifiedSummaryResult) GetAvgLatencyMs() float64 {
	if x != nil {
		return x.AvgLatencyMs
	}
	return 0
}

func (x *UnifiedSummaryResult) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *UnifiedSummaryResult) GetIssues() []string {
	if x != nil {
		return x.Issues
	}
	return nil
}

func (x *UnifiedSummaryResult) GetHostCpuUtilization() float64 {
	if x != nil {
		return x.HostCpuUtilization
	}
	return 0
}

func (x *UnifiedSummaryResult) GetHostCpuUtilizationAvg() float64 {
	if x != nil {
		return x.HostCpuUtilizationAvg
	}
	return 0
}

func (x *UnifiedSummaryResult) GetHostMemoryUsageGb() float64 {
	if x != nil {
		return x.HostMemoryUsageGb
	}
	return 0
}

func (x *UnifiedSummaryResult) GetHostMemoryLimitGb() float64 {
	if x != nil {
		return x.HostMemoryLimitGb
	}
	return 0
}

func (x *UnifiedSummaryResult) GetHostMemoryUtilization() float64 {
	if x != nil {
		return x.HostMemoryUtilization
	}
	return 0
}

func (x *UnifiedSummaryResult) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *UnifiedSummaryResult) GetProfilingSummary() *ProfilingSummary {
	if x != nil {
		return x.ProfilingSummary
	}
	return nil
}

func (x *UnifiedSummaryResult) GetDeployment() *DeploymentContext {
	if x != nil {
		return x.Deployment
	}
	return nil
}

func (x *UnifiedSummaryResult) GetRegressions() []*RegressionIndicator {
	if x != nil {
		return x.Regressions
	}
	return nil
}

type QueryUnifiedSummaryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Structured summary results.
	Summaries     []*UnifiedSummaryResult `protobuf:"bytes,1,rep,name=summaries,proto3" json:"summaries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryUnifiedSummaryResponse) Reset() {
	*x = QueryUnifiedSummaryResponse{}
	mi := &file_coral_colony_v1_queries_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUnifiedSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUnifiedSummaryResponse) ProtoMessage() {}

func (x *QueryUnifiedSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_queries_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUnifiedSummaryResponse.ProtoReflect.Descriptor instead.
func (*QueryUnifiedSummaryResponse) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_queries_proto_rawDescGZIP(), []int{2}
}

func (x *QueryUnifiedSummaryResponse) GetSummaries() []*UnifiedSummaryResult {
	if x != nil {
		return x.Summaries
	}
	return nil
}

// CPU profiling summary with top-K hotspots (RFD 074).
type ProfilingSummary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Top CPU hotspots ordered by sample count.
	TopCpuHotspots []*CPUHotspot `protobuf:"bytes,1,rep,name=top_cpu_hotspots,json=topCpuHotspots,proto3" json:"top_cpu_hotspots,omitempty"`
	// Total samples across all stacks in the time range.
	TotalSamples uint64 `protobuf:"varint,2,opt,name=total_samples,json=totalSamples,proto3" json:"total_samples,omitempty"`
	// Human-readable sampling period (e.g., "5m").
	SamplingPeriod string `protobuf:"bytes,3,opt,name=sampling_period,json=samplingPeriod,proto3" json:"sampling_period,omitempty"`
	// Build ID of the profiled binary.
	BuildId string `protobuf:"bytes,4,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	// Memory profiling hotspots (RFD 077).
	TopMemoryHotspots []*MemoryHotspot `protobuf:"bytes,5,rep,name=top_memory_hotspots,json=topMemoryHotspots,proto3" json:"top_memory_hotspots,omitempty"`
	// Total allocation bytes in the time range.
	TotalAllocBytes int64 `protobuf:"varint,6,opt,name=total_alloc_bytes,json=totalAllocBytes,proto3" json:"total_alloc_bytes,omitempty"`
	// Total allocation objects in the time range.
	TotalAllocObjects int64 `protobuf:"varint,7,opt,name=total_alloc_objects,json=totalAllocObjects,proto3" json:"total_alloc_objects,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ProfilingSummary) Reset() {
	*x = ProfilingSummary{}
	mi := &file_coral_colony_v1_queries_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfilingSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfilingSummary) ProtoMessage() {}

func (x *ProfilingSummary) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_queries_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfilingSummary.ProtoReflect.Descriptor instead.
func (*ProfilingSummary) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_queries_proto_rawDescGZIP(), []int{3}
}

func (x *ProfilingSummary) GetTopCpuHotspots() []*CPUHotspot {
	if x != nil {
		return x.TopCpuHotspots
	}
	return nil
}

func (x *ProfilingSummary) GetTotalSamples() uint64 {
	if x != nil {
		return x.TotalSamples
	}
	return 0
}

func (x *ProfilingSummary) GetSamplingPeriod() string {
	if x != nil {
		return x.SamplingPeriod
	}
	return ""
}

func (x *ProfilingSummary) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *ProfilingSummary) GetTopMemoryHotspots() []*MemoryHotspot {
	if x != nil {
		return x.TopMemoryHotspots
	}
	return nil
}

func (x *ProfilingSummary) GetTotalAllocBytes() int64 {
	if x != nil {
		return x.TotalAllocBytes
	}
	return 0
}

func (x *ProfilingSummary) GetTotalAllocObjects() int64 {
	if x != nil {
		return x.TotalAllocObjects
	}
	return 0
}

// A single memory allocation hotspot from profiling data (RFD 077).
type MemoryHotspot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 1-based rank (most allocations first).
	Rank int32 `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`
	// Stack frames from root to leaf.
	Frames []string `protobuf:"bytes,2,rep,name=frames,proto3" json:"frames,omitempty"`
	// Percentage of total allocation bytes.
	Percentage float64 `protobuf:"fixed64,3,opt,name=percentage,proto3" json:"percentage,omitempty"`
	// Allocation bytes for this stack.
	AllocBytes int64 `protobuf:"varint,4,opt,name=alloc_bytes,json=allocBytes,proto3" json:"alloc_bytes,omitempty"`
	// Allocation object count for this stack.
	AllocObjects  int64 `protobuf:"varint,5,opt,name=alloc_objects,json=allocObjects,proto3" json:"alloc_objects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryHotspot) Reset() {
	*x = MemoryHotspot{}
	mi := &file_coral_colony_v1_queries_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryHotspot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryHotspot) ProtoMessage() {}

func (x *MemoryHotspot) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_queries_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryHotspot.ProtoReflect.Descriptor instead.
func (*MemoryHotspot) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_queries_proto_rawDescGZIP(), []int{4}
}

func (x *MemoryHotspot) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *MemoryHotspot) GetFrames() []string {
	if x != nil {
		return x.Frames
	}
	return nil
}

func (x *MemoryHotspot) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *MemoryHotspot) GetAllocBytes() int64 {
	if x != nil {
		return x.AllocBytes
	}
	return 0
}

func (x *MemoryHotspot) GetAllocObjects() int64 {
	if x != nil {
		return x.AllocObjects
	}
	return 0
}

// A single CPU hotspot from profiling data (RFD 074).
type CPUHotspot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 1-based rank (hottest first).
	Rank int32 `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`
	// Stack frames from root to leaf.
	Frames []string `protobuf:"bytes,2,rep,name=frames,proto3" json:"frames,omitempty"`
	// Percentage of total CPU time.
	Percentage float64 `protobuf:"fixed64,3,opt,name=percentage,proto3" json:"percentage,omitempty"`
	// Raw sample count.
	SampleCount uint64 `protobuf:"varint,4,opt,name=sample_count,json=sampleCount,proto3" json:"sample_count,omitempty"`
	// Category hint for LLM interpretation (e.g., "business_logic", "gc", "crypto").
	// Future: May become an enum once categorization is validated across languages.
	Category      string `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CPUHotspot) Reset() {
	*x = CPUHotspot{}
	mi := &file_coral_colony_v1_queries_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPUHotspot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPUHotspot) ProtoMessage() {}

func (x *CPUHotspot) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_queries_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPUHotspot.ProtoReflect.Descriptor instead.
func (*CPUHotspot) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_queries_proto_rawDescGZIP(), []int{5}
}

func (x *CPUHotspot) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *CPUHotspot) GetFrames() []string {
	if x != nil {
		return x.Frames
	}
	return nil
}

func (x *CPUHotspot) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *CPUHotspot) GetSampleCount() uint64 {
	if x != nil {
		return x.SampleCount
	}
	return 0
}

func (x *CPUHotspot) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

// Deployment context for correlation with profiling data (RFD 074).
type DeploymentContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Build ID of the currently deployed binary.
	BuildId string `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	// When this build was first seen.
	DeployedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=deployed_at,json=deployedAt,proto3" json:"deployed_at,omitempty"`
	// Human-readable age (e.g., "2h15m").
	Age           string `protobuf:"bytes,3,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeploymentContext) Reset() {
	*x = DeploymentContext{}
	mi := &file_coral_colony_v1_queries_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentContext) ProtoMessage() {}

func (x *DeploymentContext) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_queries_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentContext.ProtoReflect.Descriptor instead.
func (*DeploymentContext) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_queries_proto_rawDescGZIP(), []int{6}
}

func (x *DeploymentContext) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *DeploymentContext) GetDeployedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeployedAt
	}
	return nil
}

func (x *DeploymentContext) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

// Regression indicator comparing current vs baseline deployment (RFD 074).
type RegressionIndicator struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type of regression detected.
	Type RegressionType `protobuf:"varint,1,opt,name=type,proto3,enum=coral.colony.v1.RegressionType" json:"type,omitempty"`
	// Human-readable description of the regression.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Percentage in the baseline deployment.
	BaselinePercentage float64 `protobuf:"fixed64,3,opt,name=baseline_percentage,json=baselinePercentage,proto3" json:"baseline_percentage,omitempty"`
	// Percentage in the current deployment.
	CurrentPercentage float64 `protobuf:"fixed64,4,opt,name=current_percentage,json=currentPercentage,proto3" json:"current_percentage,omitempty"`
	// Percentage point change (current - baseline).
	Delta         float64 `protobuf:"fixed64,5,opt,name=delta,proto3" json:"delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegressionIndicator) Reset() {
	*x = RegressionIndicator{}
	mi := &file_coral_colony_v1_queries_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegressionIndicator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegressionIndicator) ProtoMessage() {}

func (x *RegressionIndicator) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_queries_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegressionIndicator.ProtoReflect.Descriptor instead.
func (*RegressionIndicator) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_queries_proto_rawDescGZIP(), []int{7}
}

func (x *RegressionIndicator) GetType() RegressionType {
	if x != nil {
		return x.Type
	}
	return RegressionType_REGRESSION_TYPE_NEW_HOTSPOT
}

func (x *RegressionIndicator) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegressionIndicator) GetBaselinePercentage() float64 {
	if x != nil {
		return x.BaselinePercentage
	}
	return 0
}

func (x *RegressionIndicator) GetCurrentPercentage() float64 {
	if x != nil {
		return x.CurrentPercentage
	}
	return 0
}

func (x *RegressionIndicator) GetDelta() float64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

type QueryUnifiedTracesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: filter by service.
	Service string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	// Time range (default: "1h").
	TimeRange string `protobuf:"bytes,2,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	// Optional: ebpf|telemetry|all (default: all).
	Source string `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	// Optional: specific trace ID.
	TraceId string `protobuf:"bytes,4,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// Optional: filter slow traces (milliseconds).
	MinDurationMs int32 `protobuf:"varint,5,opt,name=min_duration_ms,json=minDurationMs,proto3" json:"min_duration_ms,omitempty"`
	// Maximum traces to return.
	MaxTraces     int32 `protobuf:"varint,6,opt,name=max_traces,json=maxTraces,proto3" json:"max_traces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryUnifiedTracesRequest) Reset() {
	*x = QueryUnifiedTracesRequest{}
	mi := &file_coral_colony_v1_queries_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUnifiedTracesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUnifiedTracesRequest) ProtoMessage() {}

func (x *QueryUnifiedTracesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_queries_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUnifiedTracesRequest.ProtoReflect.Descriptor instead.
func (*QueryUnifiedTracesRequest) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_queries_proto_rawDescGZIP(), []int{8}
}

func (x *QueryUnifiedTracesRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *QueryUnifiedTracesRequest) GetTimeRange() string {
	if x != nil {
		return x.TimeRange
	}
	return ""
}

func (x *QueryUnifiedTracesRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *QueryUnifiedTracesRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *QueryUnifiedTracesRequest) GetMinDurationMs() int32 {
	if x != nil {
		return x.MinDurationMs
	}
	return 0
}

func (x *QueryUnifiedTracesRequest) GetMaxTraces() int32 {
	if x != nil {
		return x.MaxTraces
	}
	return 0
}

type QueryUnifiedTracesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Structured trace spans (eBPF + OTLP).
	Spans []*v1.EbpfTraceSpan `protobuf:"bytes,1,rep,name=spans,proto3" json:"spans,omitempty"`
	// Total traces returned.
	TotalTraces   int32 `protobuf:"varint,2,opt,name=total_traces,json=totalTraces,proto3" json:"total_traces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryUnifiedTracesResponse) Reset() {
	*x = QueryUnifiedTracesResponse{}
	mi := &file_coral_colony_v1_queries_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUnifiedTracesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUnifiedTracesResponse) ProtoMessage() {}

func (x *QueryUnifiedTracesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_queries_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUnifiedTracesResponse.ProtoReflect.Descriptor instead.
func (*QueryUnifiedTracesResponse) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_queries_proto_rawDescGZIP(), []int{9}
}

func (x *QueryUnifiedTracesResponse) GetSpans() []*v1.EbpfTraceSpan {
	if x != nil {
		return x.Spans
	}
	return nil
}

func (x *QueryUnifiedTracesResponse) GetTotalTraces() int32 {
	if x != nil {
		return x.TotalTraces
	}
	return 0
}

type QueryUnifiedMetricsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: filter by service.
	Service string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	// Time range (default: "1h").
	TimeRange string `protobuf:"bytes,2,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	// Optional: ebpf|telemetry|all (default: all).
	Source string `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	// Optional: http|grpc|sql|auto (default: auto).
	Protocol string `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// Optional: HTTP route filter.
	HttpRoute string `protobuf:"bytes,5,opt,name=http_route,json=httpRoute,proto3" json:"http_route,omitempty"`
	// Optional: HTTP method filter.
	HttpMethod string `protobuf:"bytes,6,opt,name=http_method,json=httpMethod,proto3" json:"http_method,omitempty"`
	// Optional: HTTP status code range filter.
	StatusCodeRange string `protobuf:"bytes,7,opt,name=status_code_range,json=statusCodeRange,proto3" json:"status_code_range,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QueryUnifiedMetricsRequest) Reset() {
	*x = QueryUnifiedMetricsRequest{}
	mi := &file_coral_colony_v1_queries_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUnifiedMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUnifiedMetricsRequest) ProtoMessage() {}

func (x *QueryUnifiedMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_queries_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUnifiedMetricsRequest.ProtoReflect.Descriptor instead.
func (*QueryUnifiedMetricsRequest) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_queries_proto_rawDescGZIP(), []int{10}
}

func (x *QueryUnifiedMetricsRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *QueryUnifiedMetricsRequest) GetTimeRange() string {
	if x != nil {
		return x.TimeRange
	}
	return ""
}

func (x *QueryUnifiedMetricsRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *QueryUnifiedMetricsRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *QueryUnifiedMetricsRequest) GetHttpRoute() string {
	if x != nil {
		return x.HttpRoute
	}
	return ""
}

func (x *QueryUnifiedMetricsRequest) GetHttpMethod() string {
	if x != nil {
		return x.HttpMethod
	}
	return ""
}

func (x *QueryUnifiedMetricsRequest) GetStatusCodeRange() string {
	if x != nil {
		return x.StatusCodeRange
	}
	return ""
}

type QueryUnifiedMetricsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Structured HTTP metrics (eBPF + OTLP).
	HttpMetrics []*v1.EbpfHttpMetric `protobuf:"bytes,1,rep,name=http_metrics,json=httpMetrics,proto3" json:"http_metrics,omitempty"`
	// Structured gRPC metrics (eBPF + OTLP).
	GrpcMetrics []*v1.EbpfGrpcMetric `protobuf:"bytes,2,rep,name=grpc_metrics,json=grpcMetrics,proto3" json:"grpc_metrics,omitempty"`
	// Structured SQL metrics (eBPF + OTLP).
	SqlMetrics []*v1.EbpfSqlMetric `protobuf:"bytes,3,rep,name=sql_metrics,json=sqlMetrics,proto3" json:"sql_metrics,omitempty"`
	// Total metrics returned.
	TotalMetrics  int32 `protobuf:"varint,4,opt,name=total_metrics,json=totalMetrics,proto3" json:"total_metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryUnifiedMetricsResponse) Reset() {
	*x = QueryUnifiedMetricsResponse{}
	mi := &file_coral_colony_v1_queries_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUnifiedMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUnifiedMetricsResponse) ProtoMessage() {}

func (x *QueryUnifiedMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_queries_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUnifiedMetricsResponse.ProtoReflect.Descriptor instead.
func (*QueryUnifiedMetricsResponse) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_queries_proto_rawDescGZIP(), []int{11}
}

func (x *QueryUnifiedMetricsResponse) GetHttpMetrics() []*v1.EbpfHttpMetric {
	if x != nil {
		return x.HttpMetrics
	}
	return nil
}

func (x *QueryUnifiedMetricsResponse) GetGrpcMetrics() []*v1.EbpfGrpcMetric {
	if x != nil {
		return x.GrpcMetrics
	}
	return nil
}

func (x *QueryUnifiedMetricsResponse) GetSqlMetrics() []*v1.EbpfSqlMetric {
	if x != nil {
		return x.SqlMetrics
	}
	return nil
}

func (x *QueryUnifiedMetricsResponse) GetTotalMetrics() int32 {
	if x != nil {
		return x.TotalMetrics
	}
	return 0
}

type QueryUnifiedLogsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: filter by service.
	Service string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	// Time range (default: "1h").
	TimeRange string `protobuf:"bytes,2,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	// Optional: debug|info|warn|error.
	Level string `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`
	// Optional: full-text search.
	Search string `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`
	// Maximum logs to return.
	MaxLogs       int32 `protobuf:"varint,5,opt,name=max_logs,json=maxLogs,proto3" json:"max_logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryUnifiedLogsRequest) Reset() {
	*x = QueryUnifiedLogsRequest{}
	mi := &file_coral_colony_v1_queries_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUnifiedLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUnifiedLogsRequest) ProtoMessage() {}

func (x *QueryUnifiedLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_queries_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUnifiedLogsRequest.ProtoReflect.Descriptor instead.
func (*QueryUnifiedLogsRequest) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_queries_proto_rawDescGZIP(), []int{12}
}

func (x *QueryUnifiedLogsRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *QueryUnifiedLogsRequest) GetTimeRange() string {
	if x != nil {
		return x.TimeRange
	}
	return ""
}

func (x *QueryUnifiedLogsRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *QueryUnifiedLogsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *QueryUnifiedLogsRequest) GetMaxLogs() int32 {
	if x != nil {
		return x.MaxLogs
	}
	return 0
}

type UnifiedLogEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timestamp (Unix milliseconds).
	Timestamp int64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Service name.
	ServiceName string `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	// Log level: debug, info, warn, error.
	Level string `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`
	// Log message.
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// Associated trace ID (if any).
	TraceId string `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// Additional attributes.
	Attributes    map[string]string `protobuf:"bytes,6,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnifiedLogEntry) Reset() {
	*x = UnifiedLogEntry{}
	mi := &file_coral_colony_v1_queries_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnifiedLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnifiedLogEntry) ProtoMessage() {}

func (x *UnifiedLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_queries_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnifiedLogEntry.ProtoReflect.Descriptor instead.
func (*UnifiedLogEntry) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_queries_proto_rawDescGZIP(), []int{13}
}

func (x *UnifiedLogEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *UnifiedLogEntry) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *UnifiedLogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *UnifiedLogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UnifiedLogEntry) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *UnifiedLogEntry) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type QueryUnifiedLogsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Structured log entries.
	Logs []*UnifiedLogEntry `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	// Total logs returned.
	TotalLogs     int32 `protobuf:"varint,2,opt,name=total_logs,json=totalLogs,proto3" json:"total_logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryUnifiedLogsResponse) Reset() {
	*x = QueryUnifiedLogsResponse{}
	mi := &file_coral_colony_v1_queries_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUnifiedLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUnifiedLogsResponse) ProtoMessage() {}

func (x *QueryUnifiedLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_queries_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUnifiedLogsResponse.ProtoReflect.Descriptor instead.
func (*QueryUnifiedLogsResponse) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_queries_proto_rawDescGZIP(), []int{14}
}

func (x *QueryUnifiedLogsResponse) GetLogs() []*UnifiedLogEntry {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *QueryUnifiedLogsResponse) GetTotalLogs() int32 {
	if x != nil {
		return x.TotalLogs
	}
	return 0
}

type ListServicesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional namespace filter.
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Time range for telemetry-based discovery (e.g., "1h", "24h").
	// Defaults to "1h" if not specified.
	// Only affects telemetry-observed services (RFD 084).
	TimeRange string `protobuf:"bytes,2,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	// Filter by service source (RFD 084).
	// If unspecified, returns all services regardless of source.
	SourceFilter  *ServiceSource `protobuf:"varint,3,opt,name=source_filter,json=sourceFilter,proto3,enum=coral.colony.v1.ServiceSource,oneof" json:"source_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesRequest) Reset() {
	*x = ListServicesRequest{}
	mi := &file_coral_colony_v1_queries_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesRequest) ProtoMessage() {}

func (x *ListServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_queries_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesRequest.ProtoReflect.Descriptor instead.
func (*ListServicesRequest) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_queries_proto_rawDescGZIP(), []int{15}
}

func (x *ListServicesRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ListServicesRequest) GetTimeRange() string {
	if x != nil {
		return x.TimeRange
	}
	return ""
}

func (x *ListServicesRequest) GetSourceFilter() ServiceSource {
	if x != nil && x.SourceFilter != nil {
		return *x.SourceFilter
	}
	return ServiceSource_SERVICE_SOURCE_UNSPECIFIED
}

type ListServicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*ServiceSummary      `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesResponse) Reset() {
	*x = ListServicesResponse{}
	mi := &file_coral_colony_v1_queries_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesResponse) ProtoMessage() {}

func (x *ListServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_queries_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesResponse.ProtoReflect.Descriptor instead.
func (*ListServicesResponse) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_queries_proto_rawDescGZIP(), []int{16}
}

func (x *ListServicesResponse) GetServices() []*ServiceSummary {
	if x != nil {
		return x.Services
	}
	return nil
}

type ServiceSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	InstanceCount int32                  `protobuf:"varint,3,opt,name=instance_count,json=instanceCount,proto3" json:"instance_count,omitempty"`
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	// Indicates where this service information came from (RFD 084).
	Source ServiceSource `protobuf:"varint,5,opt,name=source,proto3,enum=coral.colony.v1.ServiceSource" json:"source,omitempty"`
	// Current registration and health status (if applicable) (RFD 084).
	// Only set when source includes SERVICE_SOURCE_REGISTERED.
	Status *ServiceStatus `protobuf:"varint,6,opt,name=status,proto3,enum=coral.colony.v1.ServiceStatus,oneof" json:"status,omitempty"`
	// Agent ID where service is registered (if applicable) (RFD 084).
	// Only set when source includes SERVICE_SOURCE_REGISTERED.
	AgentId       *string `protobuf:"bytes,7,opt,name=agent_id,json=agentId,proto3,oneof" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceSummary) Reset() {
	*x = ServiceSummary{}
	mi := &file_coral_colony_v1_queries_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceSummary) ProtoMessage() {}

func (x *ServiceSummary) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_queries_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceSummary.ProtoReflect.Descriptor instead.
func (*ServiceSummary) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_queries_proto_rawDescGZIP(), []int{17}
}

func (x *ServiceSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceSummary) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ServiceSummary) GetInstanceCount() int32 {
	if x != nil {
		return x.InstanceCount
	}
	return 0
}

func (x *ServiceSummary) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *ServiceSummary) GetSource() ServiceSource {
	if x != nil {
		return x.Source
	}
	return ServiceSource_SERVICE_SOURCE_UNSPECIFIED
}

func (x *ServiceSummary) GetStatus() ServiceStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ServiceStatus_SERVICE_STATUS_UNSPECIFIED
}

func (x *ServiceSummary) GetAgentId() string {
	if x != nil && x.AgentId != nil {
		return *x.AgentId
	}
	return ""
}

type GetMetricPercentileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Service name.
	Service string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	// Metric name (e.g., "http.server.duration").
	Metric string `protobuf:"bytes,2,opt,name=metric,proto3" json:"metric,omitempty"`
	// Percentile (0.0-1.0, e.g., 0.99 for P99).
	Percentile float64 `protobuf:"fixed64,3,opt,name=percentile,proto3" json:"percentile,omitempty"`
	// Time range in milliseconds (default: 1 hour).
	TimeRangeMs   int64 `protobuf:"varint,4,opt,name=time_range_ms,json=timeRangeMs,proto3" json:"time_range_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricPercentileRequest) Reset() {
	*x = GetMetricPercentileRequest{}
	mi := &file_coral_colony_v1_queries_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricPercentileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricPercentileRequest) ProtoMessage() {}

func (x *GetMetricPercentileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_queries_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricPercentileRequest.ProtoReflect.Descriptor instead.
func (*GetMetricPercentileRequest) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_queries_proto_rawDescGZIP(), []int{18}
}

func (x *GetMetricPercentileRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *GetMetricPercentileRequest) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *GetMetricPercentileRequest) GetPercentile() float64 {
	if x != nil {
		return x.Percentile
	}
	return 0
}

func (x *GetMetricPercentileRequest) GetTimeRangeMs() int64 {
	if x != nil {
		return x.TimeRangeMs
	}
	return 0
}

type GetMetricPercentileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Percentile value in the metric's native unit.
	Value float64 `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	// Unit (e.g., "nanoseconds", "bytes").
	Unit string `protobuf:"bytes,2,opt,name=unit,proto3" json:"unit,omitempty"`
	// Timestamp of the query.
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricPercentileResponse) Reset() {
	*x = GetMetricPercentileResponse{}
	mi := &file_coral_colony_v1_queries_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricPercentileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricPercentileResponse) ProtoMessage() {}

func (x *GetMetricPercentileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_queries_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricPercentileResponse.ProtoReflect.Descriptor instead.
func (*GetMetricPercentileResponse) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_queries_proto_rawDescGZIP(), []int{19}
}

func (x *GetMetricPercentileResponse) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *GetMetricPercentileResponse) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *GetMetricPercentileResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type GetServiceActivityRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Service name.
	Service string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	// Time range in milliseconds (default: 1 hour).
	TimeRangeMs   int64 `protobuf:"varint,2,opt,name=time_range_ms,json=timeRangeMs,proto3" json:"time_range_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceActivityRequest) Reset() {
	*x = GetServiceActivityRequest{}
	mi := &file_coral_colony_v1_queries_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceActivityRequest) ProtoMessage() {}

func (x *GetServiceActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_queries_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceActivityRequest.ProtoReflect.Descriptor instead.
func (*GetServiceActivityRequest) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_queries_proto_rawDescGZIP(), []int{20}
}

func (x *GetServiceActivityRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *GetServiceActivityRequest) GetTimeRangeMs() int64 {
	if x != nil {
		return x.TimeRangeMs
	}
	return 0
}

type GetServiceActivityResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Service name.
	ServiceName string `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	// Total request count.
	RequestCount int64 `protobuf:"varint,2,opt,name=request_count,json=requestCount,proto3" json:"request_count,omitempty"`
	// Error count (status >= 400).
	ErrorCount int64 `protobuf:"varint,3,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`
	// Error rate (0.0-1.0).
	ErrorRate float64 `protobuf:"fixed64,4,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"`
	// Timestamp of the query.
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceActivityResponse) Reset() {
	*x = GetServiceActivityResponse{}
	mi := &file_coral_colony_v1_queries_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceActivityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceActivityResponse) ProtoMessage() {}

func (x *GetServiceActivityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_queries_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceActivityResponse.ProtoReflect.Descriptor instead.
func (*GetServiceActivityResponse) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_queries_proto_rawDescGZIP(), []int{21}
}

func (x *GetServiceActivityResponse) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *GetServiceActivityResponse) GetRequestCount() int64 {
	if x != nil {
		return x.RequestCount
	}
	return 0
}

func (x *GetServiceActivityResponse) GetErrorCount() int64 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

func (x *GetServiceActivityResponse) GetErrorRate() float64 {
	if x != nil {
		return x.ErrorRate
	}
	return 0
}

func (x *GetServiceActivityResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ListServiceActivityRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Time range in milliseconds (default: 1 hour).
	TimeRangeMs   int64 `protobuf:"varint,1,opt,name=time_range_ms,json=timeRangeMs,proto3" json:"time_range_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServiceActivityRequest) Reset() {
	*x = ListServiceActivityRequest{}
	mi := &file_coral_colony_v1_queries_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServiceActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServiceActivityRequest) ProtoMessage() {}

func (x *ListServiceActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_queries_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServiceActivityRequest.ProtoReflect.Descriptor instead.
func (*ListServiceActivityRequest) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_queries_proto_rawDescGZIP(), []int{22}
}

func (x *ListServiceActivityRequest) GetTimeRangeMs() int64 {
	if x != nil {
		return x.TimeRangeMs
	}
	return 0
}

type ListServiceActivityResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Activity stats for all services.
	Services      []*ServiceActivity `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServiceActivityResponse) Reset() {
	*x = ListServiceActivityResponse{}
	mi := &file_coral_colony_v1_queries_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServiceActivityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServiceActivityResponse) ProtoMessage() {}

func (x *ListServiceActivityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_queries_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServiceActivityResponse.ProtoReflect.Descriptor instead.
func (*ListServiceActivityResponse) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_queries_proto_rawDescGZIP(), []int{23}
}

func (x *ListServiceActivityResponse) GetServices() []*ServiceActivity {
	if x != nil {
		return x.Services
	}
	return nil
}

type ServiceActivity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Service name.
	ServiceName string `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	// Total request count.
	RequestCount int64 `protobuf:"varint,2,opt,name=request_count,json=requestCount,proto3" json:"request_count,omitempty"`
	// Error count (status >= 400).
	ErrorCount int64 `protobuf:"varint,3,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`
	// Error rate (0.0-1.0).
	ErrorRate     float64 `protobuf:"fixed64,4,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceActivity) Reset() {
	*x = ServiceActivity{}
	mi := &file_coral_colony_v1_queries_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceActivity) ProtoMessage() {}

func (x *ServiceActivity) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_queries_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceActivity.ProtoReflect.Descriptor instead.
func (*ServiceActivity) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_queries_proto_rawDescGZIP(), []int{24}
}

func (x *ServiceActivity) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceActivity) GetRequestCount() int64 {
	if x != nil {
		return x.RequestCount
	}
	return 0
}

func (x *ServiceActivity) GetErrorCount() int64 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

func (x *ServiceActivity) GetErrorRate() float64 {
	if x != nil {
		return x.ErrorRate
	}
	return 0
}

type ExecuteQueryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SQL query string.
	Sql string `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
	// Optional: maximum rows to return (default: 1000).
	MaxRows       int32 `protobuf:"varint,2,opt,name=max_rows,json=maxRows,proto3" json:"max_rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteQueryRequest) Reset() {
	*x = ExecuteQueryRequest{}
	mi := &file_coral_colony_v1_queries_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteQueryRequest) ProtoMessage() {}

func (x *ExecuteQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_queries_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteQueryRequest.ProtoReflect.Descriptor instead.
func (*ExecuteQueryRequest) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_queries_proto_rawDescGZIP(), []int{25}
}

func (x *ExecuteQueryRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *ExecuteQueryRequest) GetMaxRows() int32 {
	if x != nil {
		return x.MaxRows
	}
	return 0
}

type ExecuteQueryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Query results as rows.
	Rows []*QueryRow `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	// Total rows returned.
	RowCount int32 `protobuf:"varint,2,opt,name=row_count,json=rowCount,proto3" json:"row_count,omitempty"`
	// Column names.
	Columns       []string `protobuf:"bytes,3,rep,name=columns,proto3" json:"columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteQueryResponse) Reset() {
	*x = ExecuteQueryResponse{}
	mi := &file_coral_colony_v1_queries_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteQueryResponse) ProtoMessage() {}

func (x *ExecuteQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_queries_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteQueryResponse.ProtoReflect.Descriptor instead.
func (*ExecuteQueryResponse) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_queries_proto_rawDescGZIP(), []int{26}
}

func (x *ExecuteQueryResponse) GetRows() []*QueryRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *ExecuteQueryResponse) GetRowCount() int32 {
	if x != nil {
		return x.RowCount
	}
	return 0
}

func (x *ExecuteQueryResponse) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

type QueryRow struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Column values (stringified).
	Values        []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRow) Reset() {
	*x = QueryRow{}
	mi := &file_coral_colony_v1_queries_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRow) ProtoMessage() {}

func (x *QueryRow) ProtoReflect() protoreflect.Message {
	mi := &file_coral_colony_v1_queries_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRow.ProtoReflect.Descriptor instead.
func (*QueryRow) Descriptor() ([]byte, []int) {
	return file_coral_colony_v1_queries_proto_rawDescGZIP(), []int{27}
}

func (x *QueryRow) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_coral_colony_v1_queries_proto protoreflect.FileDescriptor

const file_coral_colony_v1_queries_proto_rawDesc = "" +
	"\n" +
	"\x1dcoral/colony/v1/queries.proto\x12\x0fcoral.colony.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1acoral/agent/v1/agent.proto\"\xa8\x01\n" +
	"\x1aQueryUnifiedSummaryRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x1d\n" +
	"\n" +
	"time_range\x18\x02 \x01(\tR\ttimeRange\x12+\n" +
	"\x11include_profiling\x18\x03 \x01(\bR\x10includeProfiling\x12$\n" +
	"\x0etop_k_hotspots\x18\x04 \x01(\x05R\ftopKHotspots\"\xe7\x05\n" +
	"\x14UnifiedSummaryResult\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rrequest_count\x18\x03 \x01(\x03R\frequestCount\x12\x1d\n" +
	"\n" +
	"error_rate\x18\x04 \x01(\x01R\terrorRate\x12$\n" +
	"\x0eavg_latency_ms\x18\x05 \x01(\x01R\favgLatencyMs\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x12\x16\n" +
	"\x06issues\x18\a \x03(\tR\x06issues\x120\n" +
	"\x14host_cpu_utilization\x18\b \x01(\x01R\x12hostCpuUtilization\x127\n" +
	"\x18host_cpu_utilization_avg\x18\t \x01(\x01R\x15hostCpuUtilizationAvg\x12/\n" +
	"\x14host_memory_usage_gb\x18\n" +
	" \x01(\x01R\x11hostMemoryUsageGb\x12/\n" +
	"\x14host_memory_limit_gb\x18\v \x01(\x01R\x11hostMemoryLimitGb\x126\n" +
	"\x17host_memory_utilization\x18\f \x01(\x01R\x15hostMemoryUtilization\x12\x19\n" +
	"\bagent_id\x18\r \x01(\tR\aagentId\x12N\n" +
	"\x11profiling_summary\x18\x0e \x01(\v2!.coral.colony.v1.ProfilingSummaryR\x10profilingSummary\x12B\n" +
	"\n" +
	"deployment\x18\x0f \x01(\v2\".coral.colony.v1.DeploymentContextR\n" +
	"deployment\x12F\n" +
	"\vregressions\x18\x10 \x03(\v2$.coral.colony.v1.RegressionIndicatorR\vregressions\"b\n" +
	"\x1bQueryUnifiedSummaryResponse\x12C\n" +
	"\tsummaries\x18\x01 \x03(\v2%.coral.colony.v1.UnifiedSummaryResultR\tsummaries\"\xee\x02\n" +
	"\x10ProfilingSummary\x12E\n" +
	"\x10top_cpu_hotspots\x18\x01 \x03(\v2\x1b.coral.colony.v1.CPUHotspotR\x0etopCpuHotspots\x12#\n" +
	"\rtotal_samples\x18\x02 \x01(\x04R\ftotalSamples\x12'\n" +
	"\x0fsampling_period\x18\x03 \x01(\tR\x0esamplingPeriod\x12\x19\n" +
	"\bbuild_id\x18\x04 \x01(\tR\abuildId\x12N\n" +
	"\x13top_memory_hotspots\x18\x05 \x03(\v2\x1e.coral.colony.v1.MemoryHotspotR\x11topMemoryHotspots\x12*\n" +
	"\x11total_alloc_bytes\x18\x06 \x01(\x03R\x0ftotalAllocBytes\x12.\n" +
	"\x13total_alloc_objects\x18\a \x01(\x03R\x11totalAllocObjects\"\xa1\x01\n" +
	"\rMemoryHotspot\x12\x12\n" +
	"\x04rank\x18\x01 \x01(\x05R\x04rank\x12\x16\n" +
	"\x06frames\x18\x02 \x03(\tR\x06frames\x12\x1e\n" +
	"\n" +
	"percentage\x18\x03 \x01(\x01R\n" +
	"percentage\x12\x1f\n" +
	"\valloc_bytes\x18\x04 \x01(\x03R\n" +
	"allocBytes\x12#\n" +
	"\ralloc_objects\x18\x05 \x01(\x03R\fallocObjects\"\x97\x01\n" +
	"\n" +
	"CPUHotspot\x12\x12\n" +
	"\x04rank\x18\x01 \x01(\x05R\x04rank\x12\x16\n" +
	"\x06frames\x18\x02 \x03(\tR\x06frames\x12\x1e\n" +
	"\n" +
	"percentage\x18\x03 \x01(\x01R\n" +
	"percentage\x12!\n" +
	"\fsample_count\x18\x04 \x01(\x04R\vsampleCount\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\"}\n" +
	"\x11DeploymentContext\x12\x19\n" +
	"\bbuild_id\x18\x01 \x01(\tR\abuildId\x12;\n" +
	"\vdeployed_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"deployedAt\x12\x10\n" +
	"\x03age\x18\x03 \x01(\tR\x03age\"\xda\x01\n" +
	"\x13RegressionIndicator\x123\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1f.coral.colony.v1.RegressionTypeR\x04type\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12/\n" +
	"\x13baseline_percentage\x18\x03 \x01(\x01R\x12baselinePercentage\x12-\n" +
	"\x12current_percentage\x18\x04 \x01(\x01R\x11currentPercentage\x12\x14\n" +
	"\x05delta\x18\x05 \x01(\x01R\x05delta\"\xce\x01\n" +
	"\x19QueryUnifiedTracesRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x1d\n" +
	"\n" +
	"time_range\x18\x02 \x01(\tR\ttimeRange\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x19\n" +
	"\btrace_id\x18\x04 \x01(\tR\atraceId\x12&\n" +
	"\x0fmin_duration_ms\x18\x05 \x01(\x05R\rminDurationMs\x12\x1d\n" +
	"\n" +
	"max_traces\x18\x06 \x01(\x05R\tmaxTraces\"t\n" +
	"\x1aQueryUnifiedTracesResponse\x123\n" +
	"\x05spans\x18\x01 \x03(\v2\x1d.coral.agent.v1.EbpfTraceSpanR\x05spans\x12!\n" +
	"\ftotal_traces\x18\x02 \x01(\x05R\vtotalTraces\"\xf5\x01\n" +
	"\x1aQueryUnifiedMetricsRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x1d\n" +
	"\n" +
	"time_range\x18\x02 \x01(\tR\ttimeRange\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\x12\x1d\n" +
	"\n" +
	"http_route\x18\x05 \x01(\tR\thttpRoute\x12\x1f\n" +
	"\vhttp_method\x18\x06 \x01(\tR\n" +
	"httpMethod\x12*\n" +
	"\x11status_code_range\x18\a \x01(\tR\x0fstatusCodeRange\"\x88\x02\n" +
	"\x1bQueryUnifiedMetricsResponse\x12A\n" +
	"\fhttp_metrics\x18\x01 \x03(\v2\x1e.coral.agent.v1.EbpfHttpMetricR\vhttpMetrics\x12A\n" +
	"\fgrpc_metrics\x18\x02 \x03(\v2\x1e.coral.agent.v1.EbpfGrpcMetricR\vgrpcMetrics\x12>\n" +
	"\vsql_metrics\x18\x03 \x03(\v2\x1d.coral.agent.v1.EbpfSqlMetricR\n" +
	"sqlMetrics\x12#\n" +
	"\rtotal_metrics\x18\x04 \x01(\x05R\ftotalMetrics\"\x9b\x01\n" +
	"\x17QueryUnifiedLogsRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x1d\n" +
	"\n" +
	"time_range\x18\x02 \x01(\tR\ttimeRange\x12\x14\n" +
	"\x05level\x18\x03 \x01(\tR\x05level\x12\x16\n" +
	"\x06search\x18\x04 \x01(\tR\x06search\x12\x19\n" +
	"\bmax_logs\x18\x05 \x01(\x05R\amaxLogs\"\xae\x02\n" +
	"\x0fUnifiedLogEntry\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x14\n" +
	"\x05level\x18\x03 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId\x12P\n" +
	"\n" +
	"attributes\x18\x06 \x03(\v20.coral.colony.v1.UnifiedLogEntry.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"o\n" +
	"\x18QueryUnifiedLogsResponse\x124\n" +
	"\x04logs\x18\x01 \x03(\v2 .coral.colony.v1.UnifiedLogEntryR\x04logs\x12\x1d\n" +
	"\n" +
	"total_logs\x18\x02 \x01(\x05R\ttotalLogs\"\xae\x01\n" +
	"\x13ListServicesRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1d\n" +
	"\n" +
	"time_range\x18\x02 \x01(\tR\ttimeRange\x12H\n" +
	"\rsource_filter\x18\x03 \x01(\x0e2\x1e.coral.colony.v1.ServiceSourceH\x00R\fsourceFilter\x88\x01\x01B\x10\n" +
	"\x0e_source_filter\"S\n" +
	"\x14ListServicesResponse\x12;\n" +
	"\bservices\x18\x01 \x03(\v2\x1f.coral.colony.v1.ServiceSummaryR\bservices\"\xcf\x02\n" +
	"\x0eServiceSummary\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12%\n" +
	"\x0einstance_count\x18\x03 \x01(\x05R\rinstanceCount\x127\n" +
	"\tlast_seen\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x126\n" +
	"\x06source\x18\x05 \x01(\x0e2\x1e.coral.colony.v1.ServiceSourceR\x06source\x12;\n" +
	"\x06status\x18\x06 \x01(\x0e2\x1e.coral.colony.v1.ServiceStatusH\x00R\x06status\x88\x01\x01\x12\x1e\n" +
	"\bagent_id\x18\a \x01(\tH\x01R\aagentId\x88\x01\x01B\t\n" +
	"\a_statusB\v\n" +
	"\t_agent_id\"\x92\x01\n" +
	"\x1aGetMetricPercentileRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x16\n" +
	"\x06metric\x18\x02 \x01(\tR\x06metric\x12\x1e\n" +
	"\n" +
	"percentile\x18\x03 \x01(\x01R\n" +
	"percentile\x12\"\n" +
	"\rtime_range_ms\x18\x04 \x01(\x03R\vtimeRangeMs\"\x81\x01\n" +
	"\x1bGetMetricPercentileResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\x12\x12\n" +
	"\x04unit\x18\x02 \x01(\tR\x04unit\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"Y\n" +
	"\x19GetServiceActivityRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\"\n" +
	"\rtime_range_ms\x18\x02 \x01(\x03R\vtimeRangeMs\"\xde\x01\n" +
	"\x1aGetServiceActivityResponse\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12#\n" +
	"\rrequest_count\x18\x02 \x01(\x03R\frequestCount\x12\x1f\n" +
	"\verror_count\x18\x03 \x01(\x03R\n" +
	"errorCount\x12\x1d\n" +
	"\n" +
	"error_rate\x18\x04 \x01(\x01R\terrorRate\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"@\n" +
	"\x1aListServiceActivityRequest\x12\"\n" +
	"\rtime_range_ms\x18\x01 \x01(\x03R\vtimeRangeMs\"[\n" +
	"\x1bListServiceActivityResponse\x12<\n" +
	"\bservices\x18\x01 \x03(\v2 .coral.colony.v1.ServiceActivityR\bservices\"\x99\x01\n" +
	"\x0fServiceActivity\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12#\n" +
	"\rrequest_count\x18\x02 \x01(\x03R\frequestCount\x12\x1f\n" +
	"\verror_count\x18\x03 \x01(\x03R\n" +
	"errorCount\x12\x1d\n" +
	"\n" +
	"error_rate\x18\x04 \x01(\x01R\terrorRate\"B\n" +
	"\x13ExecuteQueryRequest\x12\x10\n" +
	"\x03sql\x18\x01 \x01(\tR\x03sql\x12\x19\n" +
	"\bmax_rows\x18\x02 \x01(\x05R\amaxRows\"|\n" +
	"\x14ExecuteQueryResponse\x12-\n" +
	"\x04rows\x18\x01 \x03(\v2\x19.coral.colony.v1.QueryRowR\x04rows\x12\x1b\n" +
	"\trow_count\x18\x02 \x01(\x05R\browCount\x12\x18\n" +
	"\acolumns\x18\x03 \x03(\tR\acolumns\"\"\n" +
	"\bQueryRow\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values*\x7f\n" +
	"\x0eRegressionType\x12\x1f\n" +
	"\x1bREGRESSION_TYPE_NEW_HOTSPOT\x10\x00\x12%\n" +
	"!REGRESSION_TYPE_INCREASED_HOTSPOT\x10\x01\x12%\n" +
	"!REGRESSION_TYPE_DECREASED_HOTSPOT\x10\x02*\x88\x01\n" +
	"\rServiceSource\x12\x1e\n" +
	"\x1aSERVICE_SOURCE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19SERVICE_SOURCE_REGISTERED\x10\x01\x12\x1b\n" +
	"\x17SERVICE_SOURCE_OBSERVED\x10\x02\x12\x1b\n" +
	"\x17SERVICE_SOURCE_VERIFIED\x10\x03*\xab\x01\n" +
	"\rServiceStatus\x12\x1e\n" +
	"\x1aSERVICE_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SERVICE_STATUS_ACTIVE\x10\x01\x12\x1c\n" +
	"\x18SERVICE_STATUS_UNHEALTHY\x10\x02\x12\x1f\n" +
	"\x1bSERVICE_STATUS_DISCONNECTED\x10\x03\x12 \n" +
	"\x1cSERVICE_STATUS_OBSERVED_ONLY\x10\x04B\xb7\x01\n" +
	"\x13com.coral.colony.v1B\fQueriesProtoP\x01Z4github.com/coral-mesh/coral/coral/colony/v1;colonyv1\xa2\x02\x03CCX\xaa\x02\x0fCoral.Colony.V1\xca\x02\x0fCoral\\Colony\\V1\xe2\x02\x1bCoral\\Colony\\V1\\GPBMetadata\xea\x02\x11Coral::Colony::V1b\x06proto3"

var (
	file_coral_colony_v1_queries_proto_rawDescOnce sync.Once
	file_coral_colony_v1_queries_proto_rawDescData []byte
)

func file_coral_colony_v1_queries_proto_rawDescGZIP() []byte {
	file_coral_colony_v1_queries_proto_rawDescOnce.Do(func() {
		file_coral_colony_v1_queries_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coral_colony_v1_queries_proto_rawDesc), len(file_coral_colony_v1_queries_proto_rawDesc)))
	})
	return file_coral_colony_v1_queries_proto_rawDescData
}

var file_coral_colony_v1_queries_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_coral_colony_v1_queries_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_coral_colony_v1_queries_proto_goTypes = []any{
	(RegressionType)(0),                 // 0: coral.colony.v1.RegressionType
	(ServiceSource)(0),                  // 1: coral.colony.v1.ServiceSource
	(ServiceStatus)(0),                  // 2: coral.colony.v1.ServiceStatus
	(*QueryUnifiedSummaryRequest)(nil),  // 3: coral.colony.v1.QueryUnifiedSummaryRequest
	(*UnifiedSummaryResult)(nil),        // 4: coral.colony.v1.UnifiedSummaryResult
	(*QueryUnifiedSummaryResponse)(nil), // 5: coral.colony.v1.QueryUnifiedSummaryResponse
	(*ProfilingSummary)(nil),            // 6: coral.colony.v1.ProfilingSummary
	(*MemoryHotspot)(nil),               // 7: coral.colony.v1.MemoryHotspot
	(*CPUHotspot)(nil),                  // 8: coral.colony.v1.CPUHotspot
	(*DeploymentContext)(nil),           // 9: coral.colony.v1.DeploymentContext
	(*RegressionIndicator)(nil),         // 10: coral.colony.v1.RegressionIndicator
	(*QueryUnifiedTracesRequest)(nil),   // 11: coral.colony.v1.QueryUnifiedTracesRequest
	(*QueryUnifiedTracesResponse)(nil),  // 12: coral.colony.v1.QueryUnifiedTracesResponse
	(*QueryUnifiedMetricsRequest)(nil),  // 13: coral.colony.v1.QueryUnifiedMetricsRequest
	(*QueryUnifiedMetricsResponse)(nil), // 14: coral.colony.v1.QueryUnifiedMetricsResponse
	(*QueryUnifiedLogsRequest)(nil),     // 15: coral.colony.v1.QueryUnifiedLogsRequest
	(*UnifiedLogEntry)(nil),             // 16: coral.colony.v1.UnifiedLogEntry
	(*QueryUnifiedLogsResponse)(nil),    // 17: coral.colony.v1.QueryUnifiedLogsResponse
	(*ListServicesRequest)(nil),         // 18: coral.colony.v1.ListServicesRequest
	(*ListServicesResponse)(nil),        // 19: coral.colony.v1.ListServicesResponse
	(*ServiceSummary)(nil),              // 20: coral.colony.v1.ServiceSummary
	(*GetMetricPercentileRequest)(nil),  // 21: coral.colony.v1.GetMetricPercentileRequest
	(*GetMetricPercentileResponse)(nil), // 22: coral.colony.v1.GetMetricPercentileResponse
	(*GetServiceActivityRequest)(nil),   // 23: coral.colony.v1.GetServiceActivityRequest
	(*GetServiceActivityResponse)(nil),  // 24: coral.colony.v1.GetServiceActivityResponse
	(*ListServiceActivityRequest)(nil),  // 25: coral.colony.v1.ListServiceActivityRequest
	(*ListServiceActivityResponse)(nil), // 26: coral.colony.v1.ListServiceActivityResponse
	(*ServiceActivity)(nil),             // 27: coral.colony.v1.ServiceActivity
	(*ExecuteQueryRequest)(nil),         // 28: coral.colony.v1.ExecuteQueryRequest
	(*ExecuteQueryResponse)(nil),        // 29: coral.colony.v1.ExecuteQueryResponse
	(*QueryRow)(nil),                    // 30: coral.colony.v1.QueryRow
	nil,                                 // 31: coral.colony.v1.UnifiedLogEntry.AttributesEntry
	(*timestamppb.Timestamp)(nil),       // 32: google.protobuf.Timestamp
	(*v1.EbpfTraceSpan)(nil),            // 33: coral.agent.v1.EbpfTraceSpan
	(*v1.EbpfHttpMetric)(nil),           // 34: coral.agent.v1.EbpfHttpMetric
	(*v1.EbpfGrpcMetric)(nil),           // 35: coral.agent.v1.EbpfGrpcMetric
	(*v1.EbpfSqlMetric)(nil),            // 36: coral.agent.v1.EbpfSqlMetric
}
var file_coral_colony_v1_queries_proto_depIdxs = []int32{
	6,  // 0: coral.colony.v1.UnifiedSummaryResult.profiling_summary:type_name -> coral.colony.v1.ProfilingSummary
	9,  // 1: coral.colony.v1.UnifiedSummaryResult.deployment:type_name -> coral.colony.v1.DeploymentContext
	10, // 2: coral.colony.v1.UnifiedSummaryResult.regressions:type_name -> coral.colony.v1.RegressionIndicator
	4,  // 3: coral.colony.v1.QueryUnifiedSummaryResponse.summaries:type_name -> coral.colony.v1.UnifiedSummaryResult
	8,  // 4: coral.colony.v1.ProfilingSummary.top_cpu_hotspots:type_name -> coral.colony.v1.CPUHotspot
	7,  // 5: coral.colony.v1.ProfilingSummary.top_memory_hotspots:type_name -> coral.colony.v1.MemoryHotspot
	32, // 6: coral.colony.v1.DeploymentContext.deployed_at:type_name -> google.protobuf.Timestamp
	0,  // 7: coral.colony.v1.RegressionIndicator.type:type_name -> coral.colony.v1.RegressionType
	33, // 8: coral.colony.v1.QueryUnifiedTracesResponse.spans:type_name -> coral.agent.v1.EbpfTraceSpan
	34, // 9: coral.colony.v1.QueryUnifiedMetricsResponse.http_metrics:type_name -> coral.agent.v1.EbpfHttpMetric
	35, // 10: coral.colony.v1.QueryUnifiedMetricsResponse.grpc_metrics:type_name -> coral.agent.v1.EbpfGrpcMetric
	36, // 11: coral.colony.v1.QueryUnifiedMetricsResponse.sql_metrics:type_name -> coral.agent.v1.EbpfSqlMetric
	31, // 12: coral.colony.v1.UnifiedLogEntry.attributes:type_name -> coral.colony.v1.UnifiedLogEntry.AttributesEntry
	16, // 13: coral.colony.v1.QueryUnifiedLogsResponse.logs:type_name -> coral.colony.v1.UnifiedLogEntry
	1,  // 14: coral.colony.v1.ListServicesRequest.source_filter:type_name -> coral.colony.v1.ServiceSource
	20, // 15: coral.colony.v1.ListServicesResponse.services:type_name -> coral.colony.v1.ServiceSummary
	32, // 16: coral.colony.v1.ServiceSummary.last_seen:type_name -> google.protobuf.Timestamp
	1,  // 17: coral.colony.v1.ServiceSummary.source:type_name -> coral.colony.v1.ServiceSource
	2,  // 18: coral.colony.v1.ServiceSummary.status:type_name -> coral.colony.v1.ServiceStatus
	32, // 19: coral.colony.v1.GetMetricPercentileResponse.timestamp:type_name -> google.protobuf.Timestamp
	32, // 20: coral.colony.v1.GetServiceActivityResponse.timestamp:type_name -> google.protobuf.Timestamp
	27, // 21: coral.colony.v1.ListServiceActivityResponse.services:type_name -> coral.colony.v1.ServiceActivity
	30, // 22: coral.colony.v1.ExecuteQueryResponse.rows:type_name -> coral.colony.v1.QueryRow
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_coral_colony_v1_queries_proto_init() }
func file_coral_colony_v1_queries_proto_init() {
	if File_coral_colony_v1_queries_proto != nil {
		return
	}
	file_coral_colony_v1_queries_proto_msgTypes[15].OneofWrappers = []any{}
	file_coral_colony_v1_queries_proto_msgTypes[17].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coral_colony_v1_queries_proto_rawDesc), len(file_coral_colony_v1_queries_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_coral_colony_v1_queries_proto_goTypes,
		DependencyIndexes: file_coral_colony_v1_queries_proto_depIdxs,
		EnumInfos:         file_coral_colony_v1_queries_proto_enumTypes,
		MessageInfos:      file_coral_colony_v1_queries_proto_msgTypes,
	}.Build()
	File_coral_colony_v1_queries_proto = out.File
	file_coral_colony_v1_queries_proto_goTypes = nil
	file_coral_colony_v1_queries_proto_depIdxs = nil
}
