// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: coral/sdk/v1/debug.proto

package sdkv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetFunctionMetadataRequest requests metadata for a specific function.
type GetFunctionMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FunctionName  string                 `protobuf:"bytes,1,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"` // Fully qualified: "github.com/myapp/pkg.ValidateCard"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFunctionMetadataRequest) Reset() {
	*x = GetFunctionMetadataRequest{}
	mi := &file_coral_sdk_v1_debug_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFunctionMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFunctionMetadataRequest) ProtoMessage() {}

func (x *GetFunctionMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coral_sdk_v1_debug_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFunctionMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetFunctionMetadataRequest) Descriptor() ([]byte, []int) {
	return file_coral_sdk_v1_debug_proto_rawDescGZIP(), []int{0}
}

func (x *GetFunctionMetadataRequest) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

// GetFunctionMetadataResponse returns function metadata or error.
type GetFunctionMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Metadata      *FunctionMetadata      `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFunctionMetadataResponse) Reset() {
	*x = GetFunctionMetadataResponse{}
	mi := &file_coral_sdk_v1_debug_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFunctionMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFunctionMetadataResponse) ProtoMessage() {}

func (x *GetFunctionMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coral_sdk_v1_debug_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFunctionMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetFunctionMetadataResponse) Descriptor() ([]byte, []int) {
	return file_coral_sdk_v1_debug_proto_rawDescGZIP(), []int{1}
}

func (x *GetFunctionMetadataResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetFunctionMetadataResponse) GetMetadata() *FunctionMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetFunctionMetadataResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// FunctionMetadata contains all information needed for uprobe attachment.
type FunctionMetadata struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Name       string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                               // Fully qualified name
	BinaryPath string                 `protobuf:"bytes,2,opt,name=binary_path,json=binaryPath,proto3" json:"binary_path,omitempty"` // Path to executable
	Offset     uint64                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`                          // Function offset in binary
	Pid        uint32                 `protobuf:"varint,4,opt,name=pid,proto3" json:"pid,omitempty"`                                // Process ID
	// Argument metadata (from DWARF debug info).
	Arguments     []*ArgumentMetadata    `protobuf:"bytes,5,rep,name=arguments,proto3" json:"arguments,omitempty"`
	ReturnValues  []*ReturnValueMetadata `protobuf:"bytes,6,rep,name=return_values,json=returnValues,proto3" json:"return_values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionMetadata) Reset() {
	*x = FunctionMetadata{}
	mi := &file_coral_sdk_v1_debug_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionMetadata) ProtoMessage() {}

func (x *FunctionMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_coral_sdk_v1_debug_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionMetadata.ProtoReflect.Descriptor instead.
func (*FunctionMetadata) Descriptor() ([]byte, []int) {
	return file_coral_sdk_v1_debug_proto_rawDescGZIP(), []int{2}
}

func (x *FunctionMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionMetadata) GetBinaryPath() string {
	if x != nil {
		return x.BinaryPath
	}
	return ""
}

func (x *FunctionMetadata) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FunctionMetadata) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *FunctionMetadata) GetArguments() []*ArgumentMetadata {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *FunctionMetadata) GetReturnValues() []*ReturnValueMetadata {
	if x != nil {
		return x.ReturnValues
	}
	return nil
}

// ArgumentMetadata describes a function argument.
type ArgumentMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`      // Go type string
	Offset        uint64                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"` // Stack/register offset
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArgumentMetadata) Reset() {
	*x = ArgumentMetadata{}
	mi := &file_coral_sdk_v1_debug_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArgumentMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArgumentMetadata) ProtoMessage() {}

func (x *ArgumentMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_coral_sdk_v1_debug_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArgumentMetadata.ProtoReflect.Descriptor instead.
func (*ArgumentMetadata) Descriptor() ([]byte, []int) {
	return file_coral_sdk_v1_debug_proto_rawDescGZIP(), []int{3}
}

func (x *ArgumentMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ArgumentMetadata) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ArgumentMetadata) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// ReturnValueMetadata describes a return value.
type ReturnValueMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReturnValueMetadata) Reset() {
	*x = ReturnValueMetadata{}
	mi := &file_coral_sdk_v1_debug_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReturnValueMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnValueMetadata) ProtoMessage() {}

func (x *ReturnValueMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_coral_sdk_v1_debug_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnValueMetadata.ProtoReflect.Descriptor instead.
func (*ReturnValueMetadata) Descriptor() ([]byte, []int) {
	return file_coral_sdk_v1_debug_proto_rawDescGZIP(), []int{4}
}

func (x *ReturnValueMetadata) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ReturnValueMetadata) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// ListFunctionsRequest requests all instrumentable functions.
type ListFunctionsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PackagePattern string                 `protobuf:"bytes,1,opt,name=package_pattern,json=packagePattern,proto3" json:"package_pattern,omitempty"` // e.g., "github.com/myapp/*"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListFunctionsRequest) Reset() {
	*x = ListFunctionsRequest{}
	mi := &file_coral_sdk_v1_debug_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFunctionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFunctionsRequest) ProtoMessage() {}

func (x *ListFunctionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coral_sdk_v1_debug_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFunctionsRequest.ProtoReflect.Descriptor instead.
func (*ListFunctionsRequest) Descriptor() ([]byte, []int) {
	return file_coral_sdk_v1_debug_proto_rawDescGZIP(), []int{5}
}

func (x *ListFunctionsRequest) GetPackagePattern() string {
	if x != nil {
		return x.PackagePattern
	}
	return ""
}

// ListFunctionsResponse returns available functions.
type ListFunctionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Functions     []string               `protobuf:"bytes,1,rep,name=functions,proto3" json:"functions,omitempty"` // List of fully qualified function names
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFunctionsResponse) Reset() {
	*x = ListFunctionsResponse{}
	mi := &file_coral_sdk_v1_debug_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFunctionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFunctionsResponse) ProtoMessage() {}

func (x *ListFunctionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coral_sdk_v1_debug_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFunctionsResponse.ProtoReflect.Descriptor instead.
func (*ListFunctionsResponse) Descriptor() ([]byte, []int) {
	return file_coral_sdk_v1_debug_proto_rawDescGZIP(), []int{6}
}

func (x *ListFunctionsResponse) GetFunctions() []string {
	if x != nil {
		return x.Functions
	}
	return nil
}

var File_coral_sdk_v1_debug_proto protoreflect.FileDescriptor

const file_coral_sdk_v1_debug_proto_rawDesc = "" +
	"\n" +
	"\x18coral/sdk/v1/debug.proto\x12\fcoral.sdk.v1\"A\n" +
	"\x1aGetFunctionMetadataRequest\x12#\n" +
	"\rfunction_name\x18\x01 \x01(\tR\ffunctionName\"\x85\x01\n" +
	"\x1bGetFunctionMetadataResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12:\n" +
	"\bmetadata\x18\x02 \x01(\v2\x1e.coral.sdk.v1.FunctionMetadataR\bmetadata\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xf7\x01\n" +
	"\x10FunctionMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vbinary_path\x18\x02 \x01(\tR\n" +
	"binaryPath\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\x12\x10\n" +
	"\x03pid\x18\x04 \x01(\rR\x03pid\x12<\n" +
	"\targuments\x18\x05 \x03(\v2\x1e.coral.sdk.v1.ArgumentMetadataR\targuments\x12F\n" +
	"\rreturn_values\x18\x06 \x03(\v2!.coral.sdk.v1.ReturnValueMetadataR\freturnValues\"R\n" +
	"\x10ArgumentMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\"A\n" +
	"\x13ReturnValueMetadata\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\"?\n" +
	"\x14ListFunctionsRequest\x12'\n" +
	"\x0fpackage_pattern\x18\x01 \x01(\tR\x0epackagePattern\"5\n" +
	"\x15ListFunctionsResponse\x12\x1c\n" +
	"\tfunctions\x18\x01 \x03(\tR\tfunctions2\xd7\x01\n" +
	"\x0fSDKDebugService\x12j\n" +
	"\x13GetFunctionMetadata\x12(.coral.sdk.v1.GetFunctionMetadataRequest\x1a).coral.sdk.v1.GetFunctionMetadataResponse\x12X\n" +
	"\rListFunctions\x12\".coral.sdk.v1.ListFunctionsRequest\x1a#.coral.sdk.v1.ListFunctionsResponseB\xa0\x01\n" +
	"\x10com.coral.sdk.v1B\n" +
	"DebugProtoP\x01Z.github.com/coral-mesh/coral/coral/sdk/v1;sdkv1\xa2\x02\x03CSX\xaa\x02\fCoral.Sdk.V1\xca\x02\fCoral\\Sdk\\V1\xe2\x02\x18Coral\\Sdk\\V1\\GPBMetadata\xea\x02\x0eCoral::Sdk::V1b\x06proto3"

var (
	file_coral_sdk_v1_debug_proto_rawDescOnce sync.Once
	file_coral_sdk_v1_debug_proto_rawDescData []byte
)

func file_coral_sdk_v1_debug_proto_rawDescGZIP() []byte {
	file_coral_sdk_v1_debug_proto_rawDescOnce.Do(func() {
		file_coral_sdk_v1_debug_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coral_sdk_v1_debug_proto_rawDesc), len(file_coral_sdk_v1_debug_proto_rawDesc)))
	})
	return file_coral_sdk_v1_debug_proto_rawDescData
}

var file_coral_sdk_v1_debug_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_coral_sdk_v1_debug_proto_goTypes = []any{
	(*GetFunctionMetadataRequest)(nil),  // 0: coral.sdk.v1.GetFunctionMetadataRequest
	(*GetFunctionMetadataResponse)(nil), // 1: coral.sdk.v1.GetFunctionMetadataResponse
	(*FunctionMetadata)(nil),            // 2: coral.sdk.v1.FunctionMetadata
	(*ArgumentMetadata)(nil),            // 3: coral.sdk.v1.ArgumentMetadata
	(*ReturnValueMetadata)(nil),         // 4: coral.sdk.v1.ReturnValueMetadata
	(*ListFunctionsRequest)(nil),        // 5: coral.sdk.v1.ListFunctionsRequest
	(*ListFunctionsResponse)(nil),       // 6: coral.sdk.v1.ListFunctionsResponse
}
var file_coral_sdk_v1_debug_proto_depIdxs = []int32{
	2, // 0: coral.sdk.v1.GetFunctionMetadataResponse.metadata:type_name -> coral.sdk.v1.FunctionMetadata
	3, // 1: coral.sdk.v1.FunctionMetadata.arguments:type_name -> coral.sdk.v1.ArgumentMetadata
	4, // 2: coral.sdk.v1.FunctionMetadata.return_values:type_name -> coral.sdk.v1.ReturnValueMetadata
	0, // 3: coral.sdk.v1.SDKDebugService.GetFunctionMetadata:input_type -> coral.sdk.v1.GetFunctionMetadataRequest
	5, // 4: coral.sdk.v1.SDKDebugService.ListFunctions:input_type -> coral.sdk.v1.ListFunctionsRequest
	1, // 5: coral.sdk.v1.SDKDebugService.GetFunctionMetadata:output_type -> coral.sdk.v1.GetFunctionMetadataResponse
	6, // 6: coral.sdk.v1.SDKDebugService.ListFunctions:output_type -> coral.sdk.v1.ListFunctionsResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_coral_sdk_v1_debug_proto_init() }
func file_coral_sdk_v1_debug_proto_init() {
	if File_coral_sdk_v1_debug_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coral_sdk_v1_debug_proto_rawDesc), len(file_coral_sdk_v1_debug_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coral_sdk_v1_debug_proto_goTypes,
		DependencyIndexes: file_coral_sdk_v1_debug_proto_depIdxs,
		MessageInfos:      file_coral_sdk_v1_debug_proto_msgTypes,
	}.Build()
	File_coral_sdk_v1_debug_proto = out.File
	file_coral_sdk_v1_debug_proto_goTypes = nil
	file_coral_sdk_v1_debug_proto_depIdxs = nil
}
