version: "2"

linters:
  enable:
    - gosec
  settings:
    staticcheck:
      checks:
        - "all"
        - "-SA1019" # Ignore deprecated usage warnings
    gosec:
      excludes:
        - G104 # Audit errors not checked (covered by errcheck)
        - G115 # Integer overflow conversion (many false positives in this codebase)
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gosec

linters-settings:
  gosec:
    severity: medium
    confidence: medium

  # Configure linter to understand platform-specific code
  govet:
    enable-all: true
    settings:
      printf:
        funcs:
          - (github.com/rs/zerolog.Event).Msgf
          - (github.com/rs/zerolog.Logger).Printf

  # Ignore unused code warnings for platform-specific switch cases
  staticcheck:
    checks: ["all", "-SA1019"]

  unused:
    # Check for unused code across all platforms
    check-exported: false
