// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: coral/agent/v1/agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RuntimeContext int32

const (
	// Unknown runtime.
	RuntimeContext_RUNTIME_CONTEXT_UNKNOWN RuntimeContext = 0
	// Native process on host.
	RuntimeContext_RUNTIME_CONTEXT_NATIVE RuntimeContext = 1
	// Docker container.
	RuntimeContext_RUNTIME_CONTEXT_DOCKER RuntimeContext = 2
	// Kubernetes sidecar.
	RuntimeContext_RUNTIME_CONTEXT_K8S_SIDECAR RuntimeContext = 3
	// Kubernetes DaemonSet.
	RuntimeContext_RUNTIME_CONTEXT_K8S_DAEMONSET RuntimeContext = 4
)

// Enum value maps for RuntimeContext.
var (
	RuntimeContext_name = map[int32]string{
		0: "RUNTIME_CONTEXT_UNKNOWN",
		1: "RUNTIME_CONTEXT_NATIVE",
		2: "RUNTIME_CONTEXT_DOCKER",
		3: "RUNTIME_CONTEXT_K8S_SIDECAR",
		4: "RUNTIME_CONTEXT_K8S_DAEMONSET",
	}
	RuntimeContext_value = map[string]int32{
		"RUNTIME_CONTEXT_UNKNOWN":       0,
		"RUNTIME_CONTEXT_NATIVE":        1,
		"RUNTIME_CONTEXT_DOCKER":        2,
		"RUNTIME_CONTEXT_K8S_SIDECAR":   3,
		"RUNTIME_CONTEXT_K8S_DAEMONSET": 4,
	}
)

func (x RuntimeContext) Enum() *RuntimeContext {
	p := new(RuntimeContext)
	*p = x
	return p
}

func (x RuntimeContext) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuntimeContext) Descriptor() protoreflect.EnumDescriptor {
	return file_coral_agent_v1_agent_proto_enumTypes[0].Descriptor()
}

func (RuntimeContext) Type() protoreflect.EnumType {
	return &file_coral_agent_v1_agent_proto_enumTypes[0]
}

func (x RuntimeContext) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuntimeContext.Descriptor instead.
func (RuntimeContext) EnumDescriptor() ([]byte, []int) {
	return file_coral_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

type SidecarMode int32

const (
	// Unknown sidecar mode.
	SidecarMode_SIDECAR_MODE_UNKNOWN SidecarMode = 0
	// CRI socket available.
	SidecarMode_SIDECAR_MODE_CRI SidecarMode = 1
	// Shared process namespace.
	SidecarMode_SIDECAR_MODE_SHARED_NS SidecarMode = 2
	// Passive mode (limited capabilities).
	SidecarMode_SIDECAR_MODE_PASSIVE SidecarMode = 3
)

// Enum value maps for SidecarMode.
var (
	SidecarMode_name = map[int32]string{
		0: "SIDECAR_MODE_UNKNOWN",
		1: "SIDECAR_MODE_CRI",
		2: "SIDECAR_MODE_SHARED_NS",
		3: "SIDECAR_MODE_PASSIVE",
	}
	SidecarMode_value = map[string]int32{
		"SIDECAR_MODE_UNKNOWN":   0,
		"SIDECAR_MODE_CRI":       1,
		"SIDECAR_MODE_SHARED_NS": 2,
		"SIDECAR_MODE_PASSIVE":   3,
	}
)

func (x SidecarMode) Enum() *SidecarMode {
	p := new(SidecarMode)
	*p = x
	return p
}

func (x SidecarMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SidecarMode) Descriptor() protoreflect.EnumDescriptor {
	return file_coral_agent_v1_agent_proto_enumTypes[1].Descriptor()
}

func (SidecarMode) Type() protoreflect.EnumType {
	return &file_coral_agent_v1_agent_proto_enumTypes[1]
}

func (x SidecarMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SidecarMode.Descriptor instead.
func (SidecarMode) EnumDescriptor() ([]byte, []int) {
	return file_coral_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

type GetRuntimeContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuntimeContextRequest) Reset() {
	*x = GetRuntimeContextRequest{}
	mi := &file_coral_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuntimeContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuntimeContextRequest) ProtoMessage() {}

func (x *GetRuntimeContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coral_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuntimeContextRequest.ProtoReflect.Descriptor instead.
func (*GetRuntimeContextRequest) Descriptor() ([]byte, []int) {
	return file_coral_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

type RuntimeContextResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Platform information.
	Platform *PlatformInfo `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	// Runtime type.
	RuntimeType RuntimeContext `protobuf:"varint,2,opt,name=runtime_type,json=runtimeType,proto3,enum=coral.agent.v1.RuntimeContext" json:"runtime_type,omitempty"`
	// Sidecar mode (if K8s).
	SidecarMode SidecarMode `protobuf:"varint,3,opt,name=sidecar_mode,json=sidecarMode,proto3,enum=coral.agent.v1.SidecarMode" json:"sidecar_mode,omitempty"`
	// CRI socket info.
	CriSocket *CRISocketInfo `protobuf:"bytes,4,opt,name=cri_socket,json=criSocket,proto3" json:"cri_socket,omitempty"`
	// Capabilities.
	Capabilities *Capabilities `protobuf:"bytes,5,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	// Visibility scope.
	Visibility *VisibilityScope `protobuf:"bytes,6,opt,name=visibility,proto3" json:"visibility,omitempty"`
	// Detection metadata.
	DetectedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=detected_at,json=detectedAt,proto3" json:"detected_at,omitempty"`
	// Agent version.
	Version       string `protobuf:"bytes,8,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeContextResponse) Reset() {
	*x = RuntimeContextResponse{}
	mi := &file_coral_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeContextResponse) ProtoMessage() {}

func (x *RuntimeContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coral_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeContextResponse.ProtoReflect.Descriptor instead.
func (*RuntimeContextResponse) Descriptor() ([]byte, []int) {
	return file_coral_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RuntimeContextResponse) GetPlatform() *PlatformInfo {
	if x != nil {
		return x.Platform
	}
	return nil
}

func (x *RuntimeContextResponse) GetRuntimeType() RuntimeContext {
	if x != nil {
		return x.RuntimeType
	}
	return RuntimeContext_RUNTIME_CONTEXT_UNKNOWN
}

func (x *RuntimeContextResponse) GetSidecarMode() SidecarMode {
	if x != nil {
		return x.SidecarMode
	}
	return SidecarMode_SIDECAR_MODE_UNKNOWN
}

func (x *RuntimeContextResponse) GetCriSocket() *CRISocketInfo {
	if x != nil {
		return x.CriSocket
	}
	return nil
}

func (x *RuntimeContextResponse) GetCapabilities() *Capabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RuntimeContextResponse) GetVisibility() *VisibilityScope {
	if x != nil {
		return x.Visibility
	}
	return nil
}

func (x *RuntimeContextResponse) GetDetectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DetectedAt
	}
	return nil
}

func (x *RuntimeContextResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type PlatformInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Operating system: "linux", "darwin", "windows".
	Os string `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`
	// Architecture: "amd64", "arm64".
	Arch string `protobuf:"bytes,2,opt,name=arch,proto3" json:"arch,omitempty"`
	// OS version: "Ubuntu 22.04", "macOS 14.2".
	OsVersion string `protobuf:"bytes,3,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	// Kernel version: "6.5.0-35-generic", "Darwin 23.3.0".
	Kernel        string `protobuf:"bytes,4,opt,name=kernel,proto3" json:"kernel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlatformInfo) Reset() {
	*x = PlatformInfo{}
	mi := &file_coral_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformInfo) ProtoMessage() {}

func (x *PlatformInfo) ProtoReflect() protoreflect.Message {
	mi := &file_coral_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformInfo.ProtoReflect.Descriptor instead.
func (*PlatformInfo) Descriptor() ([]byte, []int) {
	return file_coral_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *PlatformInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *PlatformInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *PlatformInfo) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *PlatformInfo) GetKernel() string {
	if x != nil {
		return x.Kernel
	}
	return ""
}

type CRISocketInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Socket path: "/var/run/containerd/containerd.sock".
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Runtime type: "containerd", "crio", "docker".
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// Runtime version: "1.7.0".
	Version       string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CRISocketInfo) Reset() {
	*x = CRISocketInfo{}
	mi := &file_coral_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CRISocketInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CRISocketInfo) ProtoMessage() {}

func (x *CRISocketInfo) ProtoReflect() protoreflect.Message {
	mi := &file_coral_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CRISocketInfo.ProtoReflect.Descriptor instead.
func (*CRISocketInfo) Descriptor() ([]byte, []int) {
	return file_coral_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *CRISocketInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CRISocketInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CRISocketInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type VisibilityScope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Can see all host PIDs.
	AllPids bool `protobuf:"varint,1,opt,name=all_pids,json=allPids,proto3" json:"all_pids,omitempty"`
	// Can see all containers.
	AllContainers bool `protobuf:"varint,2,opt,name=all_containers,json=allContainers,proto3" json:"all_containers,omitempty"`
	// Limited to pod scope.
	PodScope bool `protobuf:"varint,3,opt,name=pod_scope,json=podScope,proto3" json:"pod_scope,omitempty"`
	// Explicit target container IDs.
	ContainerIds []string `protobuf:"bytes,4,rep,name=container_ids,json=containerIds,proto3" json:"container_ids,omitempty"`
	// Namespace type: "host", "container", "pod", "node".
	Namespace     string `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisibilityScope) Reset() {
	*x = VisibilityScope{}
	mi := &file_coral_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisibilityScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisibilityScope) ProtoMessage() {}

func (x *VisibilityScope) ProtoReflect() protoreflect.Message {
	mi := &file_coral_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisibilityScope.ProtoReflect.Descriptor instead.
func (*VisibilityScope) Descriptor() ([]byte, []int) {
	return file_coral_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *VisibilityScope) GetAllPids() bool {
	if x != nil {
		return x.AllPids
	}
	return false
}

func (x *VisibilityScope) GetAllContainers() bool {
	if x != nil {
		return x.AllContainers
	}
	return false
}

func (x *VisibilityScope) GetPodScope() bool {
	if x != nil {
		return x.PodScope
	}
	return false
}

func (x *VisibilityScope) GetContainerIds() []string {
	if x != nil {
		return x.ContainerIds
	}
	return nil
}

func (x *VisibilityScope) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type Capabilities struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Can run new containers/processes.
	CanRun bool `protobuf:"varint,1,opt,name=can_run,json=canRun,proto3" json:"can_run,omitempty"`
	// Can exec into existing containers/processes.
	CanExec bool `protobuf:"varint,2,opt,name=can_exec,json=canExec,proto3" json:"can_exec,omitempty"`
	// Can open interactive shell.
	CanShell bool `protobuf:"varint,3,opt,name=can_shell,json=canShell,proto3" json:"can_shell,omitempty"`
	// Can monitor/observe (always true).
	CanConnect    bool `protobuf:"varint,4,opt,name=can_connect,json=canConnect,proto3" json:"can_connect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capabilities) Reset() {
	*x = Capabilities{}
	mi := &file_coral_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capabilities) ProtoMessage() {}

func (x *Capabilities) ProtoReflect() protoreflect.Message {
	mi := &file_coral_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capabilities.ProtoReflect.Descriptor instead.
func (*Capabilities) Descriptor() ([]byte, []int) {
	return file_coral_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *Capabilities) GetCanRun() bool {
	if x != nil {
		return x.CanRun
	}
	return false
}

func (x *Capabilities) GetCanExec() bool {
	if x != nil {
		return x.CanExec
	}
	return false
}

func (x *Capabilities) GetCanShell() bool {
	if x != nil {
		return x.CanShell
	}
	return false
}

func (x *Capabilities) GetCanConnect() bool {
	if x != nil {
		return x.CanConnect
	}
	return false
}

var File_coral_agent_v1_agent_proto protoreflect.FileDescriptor

const file_coral_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x1acoral/agent/v1/agent.proto\x12\x0ecoral.agent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1a\n" +
	"\x18GetRuntimeContextRequest\"\xed\x03\n" +
	"\x16RuntimeContextResponse\x128\n" +
	"\bplatform\x18\x01 \x01(\v2\x1c.coral.agent.v1.PlatformInfoR\bplatform\x12A\n" +
	"\fruntime_type\x18\x02 \x01(\x0e2\x1e.coral.agent.v1.RuntimeContextR\vruntimeType\x12>\n" +
	"\fsidecar_mode\x18\x03 \x01(\x0e2\x1b.coral.agent.v1.SidecarModeR\vsidecarMode\x12<\n" +
	"\n" +
	"cri_socket\x18\x04 \x01(\v2\x1d.coral.agent.v1.CRISocketInfoR\tcriSocket\x12@\n" +
	"\fcapabilities\x18\x05 \x01(\v2\x1c.coral.agent.v1.CapabilitiesR\fcapabilities\x12?\n" +
	"\n" +
	"visibility\x18\x06 \x01(\v2\x1f.coral.agent.v1.VisibilityScopeR\n" +
	"visibility\x12;\n" +
	"\vdetected_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"detectedAt\x12\x18\n" +
	"\aversion\x18\b \x01(\tR\aversion\"i\n" +
	"\fPlatformInfo\x12\x0e\n" +
	"\x02os\x18\x01 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x02 \x01(\tR\x04arch\x12\x1d\n" +
	"\n" +
	"os_version\x18\x03 \x01(\tR\tosVersion\x12\x16\n" +
	"\x06kernel\x18\x04 \x01(\tR\x06kernel\"Q\n" +
	"\rCRISocketInfo\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"\xb3\x01\n" +
	"\x0fVisibilityScope\x12\x19\n" +
	"\ball_pids\x18\x01 \x01(\bR\aallPids\x12%\n" +
	"\x0eall_containers\x18\x02 \x01(\bR\rallContainers\x12\x1b\n" +
	"\tpod_scope\x18\x03 \x01(\bR\bpodScope\x12#\n" +
	"\rcontainer_ids\x18\x04 \x03(\tR\fcontainerIds\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\"\x80\x01\n" +
	"\fCapabilities\x12\x17\n" +
	"\acan_run\x18\x01 \x01(\bR\x06canRun\x12\x19\n" +
	"\bcan_exec\x18\x02 \x01(\bR\acanExec\x12\x1b\n" +
	"\tcan_shell\x18\x03 \x01(\bR\bcanShell\x12\x1f\n" +
	"\vcan_connect\x18\x04 \x01(\bR\n" +
	"canConnect*\xa9\x01\n" +
	"\x0eRuntimeContext\x12\x1b\n" +
	"\x17RUNTIME_CONTEXT_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16RUNTIME_CONTEXT_NATIVE\x10\x01\x12\x1a\n" +
	"\x16RUNTIME_CONTEXT_DOCKER\x10\x02\x12\x1f\n" +
	"\x1bRUNTIME_CONTEXT_K8S_SIDECAR\x10\x03\x12!\n" +
	"\x1dRUNTIME_CONTEXT_K8S_DAEMONSET\x10\x04*s\n" +
	"\vSidecarMode\x12\x18\n" +
	"\x14SIDECAR_MODE_UNKNOWN\x10\x00\x12\x14\n" +
	"\x10SIDECAR_MODE_CRI\x10\x01\x12\x1a\n" +
	"\x16SIDECAR_MODE_SHARED_NS\x10\x02\x12\x18\n" +
	"\x14SIDECAR_MODE_PASSIVE\x10\x032u\n" +
	"\fAgentService\x12e\n" +
	"\x11GetRuntimeContext\x12(.coral.agent.v1.GetRuntimeContextRequest\x1a&.coral.agent.v1.RuntimeContextResponseB\xac\x01\n" +
	"\x12com.coral.agent.v1B\n" +
	"AgentProtoP\x01Z0github.com/coral-io/coral/coral/agent/v1;agentv1\xa2\x02\x03CAX\xaa\x02\x0eCoral.Agent.V1\xca\x02\x0eCoral\\Agent\\V1\xe2\x02\x1aCoral\\Agent\\V1\\GPBMetadata\xea\x02\x10Coral::Agent::V1b\x06proto3"

var (
	file_coral_agent_v1_agent_proto_rawDescOnce sync.Once
	file_coral_agent_v1_agent_proto_rawDescData []byte
)

func file_coral_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_coral_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_coral_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coral_agent_v1_agent_proto_rawDesc), len(file_coral_agent_v1_agent_proto_rawDesc)))
	})
	return file_coral_agent_v1_agent_proto_rawDescData
}

var file_coral_agent_v1_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_coral_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_coral_agent_v1_agent_proto_goTypes = []any{
	(RuntimeContext)(0),              // 0: coral.agent.v1.RuntimeContext
	(SidecarMode)(0),                 // 1: coral.agent.v1.SidecarMode
	(*GetRuntimeContextRequest)(nil), // 2: coral.agent.v1.GetRuntimeContextRequest
	(*RuntimeContextResponse)(nil),   // 3: coral.agent.v1.RuntimeContextResponse
	(*PlatformInfo)(nil),             // 4: coral.agent.v1.PlatformInfo
	(*CRISocketInfo)(nil),            // 5: coral.agent.v1.CRISocketInfo
	(*VisibilityScope)(nil),          // 6: coral.agent.v1.VisibilityScope
	(*Capabilities)(nil),             // 7: coral.agent.v1.Capabilities
	(*timestamppb.Timestamp)(nil),    // 8: google.protobuf.Timestamp
}
var file_coral_agent_v1_agent_proto_depIdxs = []int32{
	4, // 0: coral.agent.v1.RuntimeContextResponse.platform:type_name -> coral.agent.v1.PlatformInfo
	0, // 1: coral.agent.v1.RuntimeContextResponse.runtime_type:type_name -> coral.agent.v1.RuntimeContext
	1, // 2: coral.agent.v1.RuntimeContextResponse.sidecar_mode:type_name -> coral.agent.v1.SidecarMode
	5, // 3: coral.agent.v1.RuntimeContextResponse.cri_socket:type_name -> coral.agent.v1.CRISocketInfo
	7, // 4: coral.agent.v1.RuntimeContextResponse.capabilities:type_name -> coral.agent.v1.Capabilities
	6, // 5: coral.agent.v1.RuntimeContextResponse.visibility:type_name -> coral.agent.v1.VisibilityScope
	8, // 6: coral.agent.v1.RuntimeContextResponse.detected_at:type_name -> google.protobuf.Timestamp
	2, // 7: coral.agent.v1.AgentService.GetRuntimeContext:input_type -> coral.agent.v1.GetRuntimeContextRequest
	3, // 8: coral.agent.v1.AgentService.GetRuntimeContext:output_type -> coral.agent.v1.RuntimeContextResponse
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_coral_agent_v1_agent_proto_init() }
func file_coral_agent_v1_agent_proto_init() {
	if File_coral_agent_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coral_agent_v1_agent_proto_rawDesc), len(file_coral_agent_v1_agent_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coral_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_coral_agent_v1_agent_proto_depIdxs,
		EnumInfos:         file_coral_agent_v1_agent_proto_enumTypes,
		MessageInfos:      file_coral_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_coral_agent_v1_agent_proto = out.File
	file_coral_agent_v1_agent_proto_goTypes = nil
	file_coral_agent_v1_agent_proto_depIdxs = nil
}
