// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: coral/agent/v1/debug.proto

package agentv1connect

import (
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"

	connect "connectrpc.com/connect"
	v1 "github.com/coral-mesh/coral/coral/agent/v1"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AgentDebugServiceName is the fully-qualified name of the AgentDebugService service.
	AgentDebugServiceName = "coral.agent.v1.AgentDebugService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AgentDebugServiceStartUprobeCollectorProcedure is the fully-qualified name of the
	// AgentDebugService's StartUprobeCollector RPC.
	AgentDebugServiceStartUprobeCollectorProcedure = "/coral.agent.v1.AgentDebugService/StartUprobeCollector"
	// AgentDebugServiceStopUprobeCollectorProcedure is the fully-qualified name of the
	// AgentDebugService's StopUprobeCollector RPC.
	AgentDebugServiceStopUprobeCollectorProcedure = "/coral.agent.v1.AgentDebugService/StopUprobeCollector"
	// AgentDebugServiceQueryUprobeEventsProcedure is the fully-qualified name of the
	// AgentDebugService's QueryUprobeEvents RPC.
	AgentDebugServiceQueryUprobeEventsProcedure = "/coral.agent.v1.AgentDebugService/QueryUprobeEvents"
	// AgentDebugServiceProfileCPUProcedure is the fully-qualified name of the AgentDebugService's
	// ProfileCPU RPC.
	AgentDebugServiceProfileCPUProcedure = "/coral.agent.v1.AgentDebugService/ProfileCPU"
	// AgentDebugServiceQueryCPUProfileSamplesProcedure is the fully-qualified name of the
	// AgentDebugService's QueryCPUProfileSamples RPC.
	AgentDebugServiceQueryCPUProfileSamplesProcedure = "/coral.agent.v1.AgentDebugService/QueryCPUProfileSamples"
)

// AgentDebugServiceClient is a client for the coral.agent.v1.AgentDebugService service.
type AgentDebugServiceClient interface {
	// Start a uprobe collector on an agent.
	StartUprobeCollector(context.Context, *connect.Request[v1.StartUprobeCollectorRequest]) (*connect.Response[v1.StartUprobeCollectorResponse], error)
	// Stop a running uprobe collector.
	StopUprobeCollector(context.Context, *connect.Request[v1.StopUprobeCollectorRequest]) (*connect.Response[v1.StopUprobeCollectorResponse], error)
	// Query events from a uprobe collector.
	QueryUprobeEvents(context.Context, *connect.Request[v1.QueryUprobeEventsRequest]) (*connect.Response[v1.QueryUprobeEventsResponse], error)
	// Collect CPU profile samples for a target process (RFD 070).
	ProfileCPU(context.Context, *connect.Request[v1.ProfileCPUAgentRequest]) (*connect.Response[v1.ProfileCPUAgentResponse], error)
	// Query historical CPU profile samples from continuous profiling (RFD 072).
	QueryCPUProfileSamples(context.Context, *connect.Request[v1.QueryCPUProfileSamplesRequest]) (*connect.Response[v1.QueryCPUProfileSamplesResponse], error)
}

// NewAgentDebugServiceClient constructs a client for the coral.agent.v1.AgentDebugService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAgentDebugServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AgentDebugServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	agentDebugServiceMethods := v1.File_coral_agent_v1_debug_proto.Services().ByName("AgentDebugService").Methods()
	return &agentDebugServiceClient{
		startUprobeCollector: connect.NewClient[v1.StartUprobeCollectorRequest, v1.StartUprobeCollectorResponse](
			httpClient,
			baseURL+AgentDebugServiceStartUprobeCollectorProcedure,
			connect.WithSchema(agentDebugServiceMethods.ByName("StartUprobeCollector")),
			connect.WithClientOptions(opts...),
		),
		stopUprobeCollector: connect.NewClient[v1.StopUprobeCollectorRequest, v1.StopUprobeCollectorResponse](
			httpClient,
			baseURL+AgentDebugServiceStopUprobeCollectorProcedure,
			connect.WithSchema(agentDebugServiceMethods.ByName("StopUprobeCollector")),
			connect.WithClientOptions(opts...),
		),
		queryUprobeEvents: connect.NewClient[v1.QueryUprobeEventsRequest, v1.QueryUprobeEventsResponse](
			httpClient,
			baseURL+AgentDebugServiceQueryUprobeEventsProcedure,
			connect.WithSchema(agentDebugServiceMethods.ByName("QueryUprobeEvents")),
			connect.WithClientOptions(opts...),
		),
		profileCPU: connect.NewClient[v1.ProfileCPUAgentRequest, v1.ProfileCPUAgentResponse](
			httpClient,
			baseURL+AgentDebugServiceProfileCPUProcedure,
			connect.WithSchema(agentDebugServiceMethods.ByName("ProfileCPU")),
			connect.WithClientOptions(opts...),
		),
		queryCPUProfileSamples: connect.NewClient[v1.QueryCPUProfileSamplesRequest, v1.QueryCPUProfileSamplesResponse](
			httpClient,
			baseURL+AgentDebugServiceQueryCPUProfileSamplesProcedure,
			connect.WithSchema(agentDebugServiceMethods.ByName("QueryCPUProfileSamples")),
			connect.WithClientOptions(opts...),
		),
	}
}

// agentDebugServiceClient implements AgentDebugServiceClient.
type agentDebugServiceClient struct {
	startUprobeCollector   *connect.Client[v1.StartUprobeCollectorRequest, v1.StartUprobeCollectorResponse]
	stopUprobeCollector    *connect.Client[v1.StopUprobeCollectorRequest, v1.StopUprobeCollectorResponse]
	queryUprobeEvents      *connect.Client[v1.QueryUprobeEventsRequest, v1.QueryUprobeEventsResponse]
	profileCPU             *connect.Client[v1.ProfileCPUAgentRequest, v1.ProfileCPUAgentResponse]
	queryCPUProfileSamples *connect.Client[v1.QueryCPUProfileSamplesRequest, v1.QueryCPUProfileSamplesResponse]
}

// StartUprobeCollector calls coral.agent.v1.AgentDebugService.StartUprobeCollector.
func (c *agentDebugServiceClient) StartUprobeCollector(ctx context.Context, req *connect.Request[v1.StartUprobeCollectorRequest]) (*connect.Response[v1.StartUprobeCollectorResponse], error) {
	return c.startUprobeCollector.CallUnary(ctx, req)
}

// StopUprobeCollector calls coral.agent.v1.AgentDebugService.StopUprobeCollector.
func (c *agentDebugServiceClient) StopUprobeCollector(ctx context.Context, req *connect.Request[v1.StopUprobeCollectorRequest]) (*connect.Response[v1.StopUprobeCollectorResponse], error) {
	return c.stopUprobeCollector.CallUnary(ctx, req)
}

// QueryUprobeEvents calls coral.agent.v1.AgentDebugService.QueryUprobeEvents.
func (c *agentDebugServiceClient) QueryUprobeEvents(ctx context.Context, req *connect.Request[v1.QueryUprobeEventsRequest]) (*connect.Response[v1.QueryUprobeEventsResponse], error) {
	return c.queryUprobeEvents.CallUnary(ctx, req)
}

// ProfileCPU calls coral.agent.v1.AgentDebugService.ProfileCPU.
func (c *agentDebugServiceClient) ProfileCPU(ctx context.Context, req *connect.Request[v1.ProfileCPUAgentRequest]) (*connect.Response[v1.ProfileCPUAgentResponse], error) {
	return c.profileCPU.CallUnary(ctx, req)
}

// QueryCPUProfileSamples calls coral.agent.v1.AgentDebugService.QueryCPUProfileSamples.
func (c *agentDebugServiceClient) QueryCPUProfileSamples(ctx context.Context, req *connect.Request[v1.QueryCPUProfileSamplesRequest]) (*connect.Response[v1.QueryCPUProfileSamplesResponse], error) {
	return c.queryCPUProfileSamples.CallUnary(ctx, req)
}

// AgentDebugServiceHandler is an implementation of the coral.agent.v1.AgentDebugService service.
type AgentDebugServiceHandler interface {
	// Start a uprobe collector on an agent.
	StartUprobeCollector(context.Context, *connect.Request[v1.StartUprobeCollectorRequest]) (*connect.Response[v1.StartUprobeCollectorResponse], error)
	// Stop a running uprobe collector.
	StopUprobeCollector(context.Context, *connect.Request[v1.StopUprobeCollectorRequest]) (*connect.Response[v1.StopUprobeCollectorResponse], error)
	// Query events from a uprobe collector.
	QueryUprobeEvents(context.Context, *connect.Request[v1.QueryUprobeEventsRequest]) (*connect.Response[v1.QueryUprobeEventsResponse], error)
	// Collect CPU profile samples for a target process (RFD 070).
	ProfileCPU(context.Context, *connect.Request[v1.ProfileCPUAgentRequest]) (*connect.Response[v1.ProfileCPUAgentResponse], error)
	// Query historical CPU profile samples from continuous profiling (RFD 072).
	QueryCPUProfileSamples(context.Context, *connect.Request[v1.QueryCPUProfileSamplesRequest]) (*connect.Response[v1.QueryCPUProfileSamplesResponse], error)
}

// NewAgentDebugServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAgentDebugServiceHandler(svc AgentDebugServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	agentDebugServiceMethods := v1.File_coral_agent_v1_debug_proto.Services().ByName("AgentDebugService").Methods()
	agentDebugServiceStartUprobeCollectorHandler := connect.NewUnaryHandler(
		AgentDebugServiceStartUprobeCollectorProcedure,
		svc.StartUprobeCollector,
		connect.WithSchema(agentDebugServiceMethods.ByName("StartUprobeCollector")),
		connect.WithHandlerOptions(opts...),
	)
	agentDebugServiceStopUprobeCollectorHandler := connect.NewUnaryHandler(
		AgentDebugServiceStopUprobeCollectorProcedure,
		svc.StopUprobeCollector,
		connect.WithSchema(agentDebugServiceMethods.ByName("StopUprobeCollector")),
		connect.WithHandlerOptions(opts...),
	)
	agentDebugServiceQueryUprobeEventsHandler := connect.NewUnaryHandler(
		AgentDebugServiceQueryUprobeEventsProcedure,
		svc.QueryUprobeEvents,
		connect.WithSchema(agentDebugServiceMethods.ByName("QueryUprobeEvents")),
		connect.WithHandlerOptions(opts...),
	)
	agentDebugServiceProfileCPUHandler := connect.NewUnaryHandler(
		AgentDebugServiceProfileCPUProcedure,
		svc.ProfileCPU,
		connect.WithSchema(agentDebugServiceMethods.ByName("ProfileCPU")),
		connect.WithHandlerOptions(opts...),
	)
	agentDebugServiceQueryCPUProfileSamplesHandler := connect.NewUnaryHandler(
		AgentDebugServiceQueryCPUProfileSamplesProcedure,
		svc.QueryCPUProfileSamples,
		connect.WithSchema(agentDebugServiceMethods.ByName("QueryCPUProfileSamples")),
		connect.WithHandlerOptions(opts...),
	)
	return "/coral.agent.v1.AgentDebugService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AgentDebugServiceStartUprobeCollectorProcedure:
			agentDebugServiceStartUprobeCollectorHandler.ServeHTTP(w, r)
		case AgentDebugServiceStopUprobeCollectorProcedure:
			agentDebugServiceStopUprobeCollectorHandler.ServeHTTP(w, r)
		case AgentDebugServiceQueryUprobeEventsProcedure:
			agentDebugServiceQueryUprobeEventsHandler.ServeHTTP(w, r)
		case AgentDebugServiceProfileCPUProcedure:
			agentDebugServiceProfileCPUHandler.ServeHTTP(w, r)
		case AgentDebugServiceQueryCPUProfileSamplesProcedure:
			agentDebugServiceQueryCPUProfileSamplesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAgentDebugServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAgentDebugServiceHandler struct{}

func (UnimplementedAgentDebugServiceHandler) StartUprobeCollector(context.Context, *connect.Request[v1.StartUprobeCollectorRequest]) (*connect.Response[v1.StartUprobeCollectorResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coral.agent.v1.AgentDebugService.StartUprobeCollector is not implemented"))
}

func (UnimplementedAgentDebugServiceHandler) StopUprobeCollector(context.Context, *connect.Request[v1.StopUprobeCollectorRequest]) (*connect.Response[v1.StopUprobeCollectorResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coral.agent.v1.AgentDebugService.StopUprobeCollector is not implemented"))
}

func (UnimplementedAgentDebugServiceHandler) QueryUprobeEvents(context.Context, *connect.Request[v1.QueryUprobeEventsRequest]) (*connect.Response[v1.QueryUprobeEventsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coral.agent.v1.AgentDebugService.QueryUprobeEvents is not implemented"))
}

func (UnimplementedAgentDebugServiceHandler) ProfileCPU(context.Context, *connect.Request[v1.ProfileCPUAgentRequest]) (*connect.Response[v1.ProfileCPUAgentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coral.agent.v1.AgentDebugService.ProfileCPU is not implemented"))
}

func (UnimplementedAgentDebugServiceHandler) QueryCPUProfileSamples(context.Context, *connect.Request[v1.QueryCPUProfileSamplesRequest]) (*connect.Response[v1.QueryCPUProfileSamplesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coral.agent.v1.AgentDebugService.QueryCPUProfileSamples is not implemented"))
}
