// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: coral/colony/v1/colony.proto

package colonyv1connect

import (
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"

	connect "connectrpc.com/connect"
	v1 "github.com/coral-mesh/coral/coral/colony/v1"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ColonyServiceName is the fully-qualified name of the ColonyService service.
	ColonyServiceName = "coral.colony.v1.ColonyService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ColonyServiceGetStatusProcedure is the fully-qualified name of the ColonyService's GetStatus RPC.
	ColonyServiceGetStatusProcedure = "/coral.colony.v1.ColonyService/GetStatus"
	// ColonyServiceListAgentsProcedure is the fully-qualified name of the ColonyService's ListAgents
	// RPC.
	ColonyServiceListAgentsProcedure = "/coral.colony.v1.ColonyService/ListAgents"
	// ColonyServiceGetTopologyProcedure is the fully-qualified name of the ColonyService's GetTopology
	// RPC.
	ColonyServiceGetTopologyProcedure = "/coral.colony.v1.ColonyService/GetTopology"
	// ColonyServiceQueryUnifiedSummaryProcedure is the fully-qualified name of the ColonyService's
	// QueryUnifiedSummary RPC.
	ColonyServiceQueryUnifiedSummaryProcedure = "/coral.colony.v1.ColonyService/QueryUnifiedSummary"
	// ColonyServiceQueryUnifiedTracesProcedure is the fully-qualified name of the ColonyService's
	// QueryUnifiedTraces RPC.
	ColonyServiceQueryUnifiedTracesProcedure = "/coral.colony.v1.ColonyService/QueryUnifiedTraces"
	// ColonyServiceQueryUnifiedMetricsProcedure is the fully-qualified name of the ColonyService's
	// QueryUnifiedMetrics RPC.
	ColonyServiceQueryUnifiedMetricsProcedure = "/coral.colony.v1.ColonyService/QueryUnifiedMetrics"
	// ColonyServiceQueryUnifiedLogsProcedure is the fully-qualified name of the ColonyService's
	// QueryUnifiedLogs RPC.
	ColonyServiceQueryUnifiedLogsProcedure = "/coral.colony.v1.ColonyService/QueryUnifiedLogs"
	// ColonyServiceListServicesProcedure is the fully-qualified name of the ColonyService's
	// ListServices RPC.
	ColonyServiceListServicesProcedure = "/coral.colony.v1.ColonyService/ListServices"
	// ColonyServiceGetMetricPercentileProcedure is the fully-qualified name of the ColonyService's
	// GetMetricPercentile RPC.
	ColonyServiceGetMetricPercentileProcedure = "/coral.colony.v1.ColonyService/GetMetricPercentile"
	// ColonyServiceExecuteQueryProcedure is the fully-qualified name of the ColonyService's
	// ExecuteQuery RPC.
	ColonyServiceExecuteQueryProcedure = "/coral.colony.v1.ColonyService/ExecuteQuery"
	// ColonyServiceCallToolProcedure is the fully-qualified name of the ColonyService's CallTool RPC.
	ColonyServiceCallToolProcedure = "/coral.colony.v1.ColonyService/CallTool"
	// ColonyServiceStreamToolProcedure is the fully-qualified name of the ColonyService's StreamTool
	// RPC.
	ColonyServiceStreamToolProcedure = "/coral.colony.v1.ColonyService/StreamTool"
	// ColonyServiceListToolsProcedure is the fully-qualified name of the ColonyService's ListTools RPC.
	ColonyServiceListToolsProcedure = "/coral.colony.v1.ColonyService/ListTools"
	// ColonyServiceRequestCertificateProcedure is the fully-qualified name of the ColonyService's
	// RequestCertificate RPC.
	ColonyServiceRequestCertificateProcedure = "/coral.colony.v1.ColonyService/RequestCertificate"
	// ColonyServiceRevokeCertificateProcedure is the fully-qualified name of the ColonyService's
	// RevokeCertificate RPC.
	ColonyServiceRevokeCertificateProcedure = "/coral.colony.v1.ColonyService/RevokeCertificate"
)

// ColonyServiceClient is a client for the coral.colony.v1.ColonyService service.
type ColonyServiceClient interface {
	// Get colony status and health.
	GetStatus(context.Context, *connect.Request[v1.GetStatusRequest]) (*connect.Response[v1.GetStatusResponse], error)
	// List connected agents.
	ListAgents(context.Context, *connect.Request[v1.ListAgentsRequest]) (*connect.Response[v1.ListAgentsResponse], error)
	// Get network topology.
	GetTopology(context.Context, *connect.Request[v1.GetTopologyRequest]) (*connect.Response[v1.GetTopologyResponse], error)
	// Unified query interface (RFD 067) - comprehensive queries for detailed analysis.
	QueryUnifiedSummary(context.Context, *connect.Request[v1.QueryUnifiedSummaryRequest]) (*connect.Response[v1.QueryUnifiedSummaryResponse], error)
	QueryUnifiedTraces(context.Context, *connect.Request[v1.QueryUnifiedTracesRequest]) (*connect.Response[v1.QueryUnifiedTracesResponse], error)
	QueryUnifiedMetrics(context.Context, *connect.Request[v1.QueryUnifiedMetricsRequest]) (*connect.Response[v1.QueryUnifiedMetricsResponse], error)
	QueryUnifiedLogs(context.Context, *connect.Request[v1.QueryUnifiedLogsRequest]) (*connect.Response[v1.QueryUnifiedLogsResponse], error)
	// Focused query interface (RFD 076) - focused queries for scripting and CLI.
	ListServices(context.Context, *connect.Request[v1.ListServicesRequest]) (*connect.Response[v1.ListServicesResponse], error)
	GetMetricPercentile(context.Context, *connect.Request[v1.GetMetricPercentileRequest]) (*connect.Response[v1.GetMetricPercentileResponse], error)
	ExecuteQuery(context.Context, *connect.Request[v1.ExecuteQueryRequest]) (*connect.Response[v1.ExecuteQueryResponse], error)
	// Execute an MCP tool and return the result.
	CallTool(context.Context, *connect.Request[v1.CallToolRequest]) (*connect.Response[v1.CallToolResponse], error)
	// Execute an MCP tool with streaming (bidirectional).
	StreamTool(context.Context) *connect.BidiStreamForClient[v1.StreamToolRequest, v1.StreamToolResponse]
	// List available MCP tools.
	ListTools(context.Context, *connect.Request[v1.ListToolsRequest]) (*connect.Response[v1.ListToolsResponse], error)
	// Request a client certificate using a bootstrap token.
	RequestCertificate(context.Context, *connect.Request[v1.RequestCertificateRequest]) (*connect.Response[v1.RequestCertificateResponse], error)
	// Revoke an issued certificate.
	RevokeCertificate(context.Context, *connect.Request[v1.RevokeCertificateRequest]) (*connect.Response[v1.RevokeCertificateResponse], error)
}

// NewColonyServiceClient constructs a client for the coral.colony.v1.ColonyService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewColonyServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ColonyServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	colonyServiceMethods := v1.File_coral_colony_v1_colony_proto.Services().ByName("ColonyService").Methods()
	return &colonyServiceClient{
		getStatus: connect.NewClient[v1.GetStatusRequest, v1.GetStatusResponse](
			httpClient,
			baseURL+ColonyServiceGetStatusProcedure,
			connect.WithSchema(colonyServiceMethods.ByName("GetStatus")),
			connect.WithClientOptions(opts...),
		),
		listAgents: connect.NewClient[v1.ListAgentsRequest, v1.ListAgentsResponse](
			httpClient,
			baseURL+ColonyServiceListAgentsProcedure,
			connect.WithSchema(colonyServiceMethods.ByName("ListAgents")),
			connect.WithClientOptions(opts...),
		),
		getTopology: connect.NewClient[v1.GetTopologyRequest, v1.GetTopologyResponse](
			httpClient,
			baseURL+ColonyServiceGetTopologyProcedure,
			connect.WithSchema(colonyServiceMethods.ByName("GetTopology")),
			connect.WithClientOptions(opts...),
		),
		queryUnifiedSummary: connect.NewClient[v1.QueryUnifiedSummaryRequest, v1.QueryUnifiedSummaryResponse](
			httpClient,
			baseURL+ColonyServiceQueryUnifiedSummaryProcedure,
			connect.WithSchema(colonyServiceMethods.ByName("QueryUnifiedSummary")),
			connect.WithClientOptions(opts...),
		),
		queryUnifiedTraces: connect.NewClient[v1.QueryUnifiedTracesRequest, v1.QueryUnifiedTracesResponse](
			httpClient,
			baseURL+ColonyServiceQueryUnifiedTracesProcedure,
			connect.WithSchema(colonyServiceMethods.ByName("QueryUnifiedTraces")),
			connect.WithClientOptions(opts...),
		),
		queryUnifiedMetrics: connect.NewClient[v1.QueryUnifiedMetricsRequest, v1.QueryUnifiedMetricsResponse](
			httpClient,
			baseURL+ColonyServiceQueryUnifiedMetricsProcedure,
			connect.WithSchema(colonyServiceMethods.ByName("QueryUnifiedMetrics")),
			connect.WithClientOptions(opts...),
		),
		queryUnifiedLogs: connect.NewClient[v1.QueryUnifiedLogsRequest, v1.QueryUnifiedLogsResponse](
			httpClient,
			baseURL+ColonyServiceQueryUnifiedLogsProcedure,
			connect.WithSchema(colonyServiceMethods.ByName("QueryUnifiedLogs")),
			connect.WithClientOptions(opts...),
		),
		listServices: connect.NewClient[v1.ListServicesRequest, v1.ListServicesResponse](
			httpClient,
			baseURL+ColonyServiceListServicesProcedure,
			connect.WithSchema(colonyServiceMethods.ByName("ListServices")),
			connect.WithClientOptions(opts...),
		),
		getMetricPercentile: connect.NewClient[v1.GetMetricPercentileRequest, v1.GetMetricPercentileResponse](
			httpClient,
			baseURL+ColonyServiceGetMetricPercentileProcedure,
			connect.WithSchema(colonyServiceMethods.ByName("GetMetricPercentile")),
			connect.WithClientOptions(opts...),
		),
		executeQuery: connect.NewClient[v1.ExecuteQueryRequest, v1.ExecuteQueryResponse](
			httpClient,
			baseURL+ColonyServiceExecuteQueryProcedure,
			connect.WithSchema(colonyServiceMethods.ByName("ExecuteQuery")),
			connect.WithClientOptions(opts...),
		),
		callTool: connect.NewClient[v1.CallToolRequest, v1.CallToolResponse](
			httpClient,
			baseURL+ColonyServiceCallToolProcedure,
			connect.WithSchema(colonyServiceMethods.ByName("CallTool")),
			connect.WithClientOptions(opts...),
		),
		streamTool: connect.NewClient[v1.StreamToolRequest, v1.StreamToolResponse](
			httpClient,
			baseURL+ColonyServiceStreamToolProcedure,
			connect.WithSchema(colonyServiceMethods.ByName("StreamTool")),
			connect.WithClientOptions(opts...),
		),
		listTools: connect.NewClient[v1.ListToolsRequest, v1.ListToolsResponse](
			httpClient,
			baseURL+ColonyServiceListToolsProcedure,
			connect.WithSchema(colonyServiceMethods.ByName("ListTools")),
			connect.WithClientOptions(opts...),
		),
		requestCertificate: connect.NewClient[v1.RequestCertificateRequest, v1.RequestCertificateResponse](
			httpClient,
			baseURL+ColonyServiceRequestCertificateProcedure,
			connect.WithSchema(colonyServiceMethods.ByName("RequestCertificate")),
			connect.WithClientOptions(opts...),
		),
		revokeCertificate: connect.NewClient[v1.RevokeCertificateRequest, v1.RevokeCertificateResponse](
			httpClient,
			baseURL+ColonyServiceRevokeCertificateProcedure,
			connect.WithSchema(colonyServiceMethods.ByName("RevokeCertificate")),
			connect.WithClientOptions(opts...),
		),
	}
}

// colonyServiceClient implements ColonyServiceClient.
type colonyServiceClient struct {
	getStatus           *connect.Client[v1.GetStatusRequest, v1.GetStatusResponse]
	listAgents          *connect.Client[v1.ListAgentsRequest, v1.ListAgentsResponse]
	getTopology         *connect.Client[v1.GetTopologyRequest, v1.GetTopologyResponse]
	queryUnifiedSummary *connect.Client[v1.QueryUnifiedSummaryRequest, v1.QueryUnifiedSummaryResponse]
	queryUnifiedTraces  *connect.Client[v1.QueryUnifiedTracesRequest, v1.QueryUnifiedTracesResponse]
	queryUnifiedMetrics *connect.Client[v1.QueryUnifiedMetricsRequest, v1.QueryUnifiedMetricsResponse]
	queryUnifiedLogs    *connect.Client[v1.QueryUnifiedLogsRequest, v1.QueryUnifiedLogsResponse]
	listServices        *connect.Client[v1.ListServicesRequest, v1.ListServicesResponse]
	getMetricPercentile *connect.Client[v1.GetMetricPercentileRequest, v1.GetMetricPercentileResponse]
	executeQuery        *connect.Client[v1.ExecuteQueryRequest, v1.ExecuteQueryResponse]
	callTool            *connect.Client[v1.CallToolRequest, v1.CallToolResponse]
	streamTool          *connect.Client[v1.StreamToolRequest, v1.StreamToolResponse]
	listTools           *connect.Client[v1.ListToolsRequest, v1.ListToolsResponse]
	requestCertificate  *connect.Client[v1.RequestCertificateRequest, v1.RequestCertificateResponse]
	revokeCertificate   *connect.Client[v1.RevokeCertificateRequest, v1.RevokeCertificateResponse]
}

// GetStatus calls coral.colony.v1.ColonyService.GetStatus.
func (c *colonyServiceClient) GetStatus(ctx context.Context, req *connect.Request[v1.GetStatusRequest]) (*connect.Response[v1.GetStatusResponse], error) {
	return c.getStatus.CallUnary(ctx, req)
}

// ListAgents calls coral.colony.v1.ColonyService.ListAgents.
func (c *colonyServiceClient) ListAgents(ctx context.Context, req *connect.Request[v1.ListAgentsRequest]) (*connect.Response[v1.ListAgentsResponse], error) {
	return c.listAgents.CallUnary(ctx, req)
}

// GetTopology calls coral.colony.v1.ColonyService.GetTopology.
func (c *colonyServiceClient) GetTopology(ctx context.Context, req *connect.Request[v1.GetTopologyRequest]) (*connect.Response[v1.GetTopologyResponse], error) {
	return c.getTopology.CallUnary(ctx, req)
}

// QueryUnifiedSummary calls coral.colony.v1.ColonyService.QueryUnifiedSummary.
func (c *colonyServiceClient) QueryUnifiedSummary(ctx context.Context, req *connect.Request[v1.QueryUnifiedSummaryRequest]) (*connect.Response[v1.QueryUnifiedSummaryResponse], error) {
	return c.queryUnifiedSummary.CallUnary(ctx, req)
}

// QueryUnifiedTraces calls coral.colony.v1.ColonyService.QueryUnifiedTraces.
func (c *colonyServiceClient) QueryUnifiedTraces(ctx context.Context, req *connect.Request[v1.QueryUnifiedTracesRequest]) (*connect.Response[v1.QueryUnifiedTracesResponse], error) {
	return c.queryUnifiedTraces.CallUnary(ctx, req)
}

// QueryUnifiedMetrics calls coral.colony.v1.ColonyService.QueryUnifiedMetrics.
func (c *colonyServiceClient) QueryUnifiedMetrics(ctx context.Context, req *connect.Request[v1.QueryUnifiedMetricsRequest]) (*connect.Response[v1.QueryUnifiedMetricsResponse], error) {
	return c.queryUnifiedMetrics.CallUnary(ctx, req)
}

// QueryUnifiedLogs calls coral.colony.v1.ColonyService.QueryUnifiedLogs.
func (c *colonyServiceClient) QueryUnifiedLogs(ctx context.Context, req *connect.Request[v1.QueryUnifiedLogsRequest]) (*connect.Response[v1.QueryUnifiedLogsResponse], error) {
	return c.queryUnifiedLogs.CallUnary(ctx, req)
}

// ListServices calls coral.colony.v1.ColonyService.ListServices.
func (c *colonyServiceClient) ListServices(ctx context.Context, req *connect.Request[v1.ListServicesRequest]) (*connect.Response[v1.ListServicesResponse], error) {
	return c.listServices.CallUnary(ctx, req)
}

// GetMetricPercentile calls coral.colony.v1.ColonyService.GetMetricPercentile.
func (c *colonyServiceClient) GetMetricPercentile(ctx context.Context, req *connect.Request[v1.GetMetricPercentileRequest]) (*connect.Response[v1.GetMetricPercentileResponse], error) {
	return c.getMetricPercentile.CallUnary(ctx, req)
}

// ExecuteQuery calls coral.colony.v1.ColonyService.ExecuteQuery.
func (c *colonyServiceClient) ExecuteQuery(ctx context.Context, req *connect.Request[v1.ExecuteQueryRequest]) (*connect.Response[v1.ExecuteQueryResponse], error) {
	return c.executeQuery.CallUnary(ctx, req)
}

// CallTool calls coral.colony.v1.ColonyService.CallTool.
func (c *colonyServiceClient) CallTool(ctx context.Context, req *connect.Request[v1.CallToolRequest]) (*connect.Response[v1.CallToolResponse], error) {
	return c.callTool.CallUnary(ctx, req)
}

// StreamTool calls coral.colony.v1.ColonyService.StreamTool.
func (c *colonyServiceClient) StreamTool(ctx context.Context) *connect.BidiStreamForClient[v1.StreamToolRequest, v1.StreamToolResponse] {
	return c.streamTool.CallBidiStream(ctx)
}

// ListTools calls coral.colony.v1.ColonyService.ListTools.
func (c *colonyServiceClient) ListTools(ctx context.Context, req *connect.Request[v1.ListToolsRequest]) (*connect.Response[v1.ListToolsResponse], error) {
	return c.listTools.CallUnary(ctx, req)
}

// RequestCertificate calls coral.colony.v1.ColonyService.RequestCertificate.
func (c *colonyServiceClient) RequestCertificate(ctx context.Context, req *connect.Request[v1.RequestCertificateRequest]) (*connect.Response[v1.RequestCertificateResponse], error) {
	return c.requestCertificate.CallUnary(ctx, req)
}

// RevokeCertificate calls coral.colony.v1.ColonyService.RevokeCertificate.
func (c *colonyServiceClient) RevokeCertificate(ctx context.Context, req *connect.Request[v1.RevokeCertificateRequest]) (*connect.Response[v1.RevokeCertificateResponse], error) {
	return c.revokeCertificate.CallUnary(ctx, req)
}

// ColonyServiceHandler is an implementation of the coral.colony.v1.ColonyService service.
type ColonyServiceHandler interface {
	// Get colony status and health.
	GetStatus(context.Context, *connect.Request[v1.GetStatusRequest]) (*connect.Response[v1.GetStatusResponse], error)
	// List connected agents.
	ListAgents(context.Context, *connect.Request[v1.ListAgentsRequest]) (*connect.Response[v1.ListAgentsResponse], error)
	// Get network topology.
	GetTopology(context.Context, *connect.Request[v1.GetTopologyRequest]) (*connect.Response[v1.GetTopologyResponse], error)
	// Unified query interface (RFD 067) - comprehensive queries for detailed analysis.
	QueryUnifiedSummary(context.Context, *connect.Request[v1.QueryUnifiedSummaryRequest]) (*connect.Response[v1.QueryUnifiedSummaryResponse], error)
	QueryUnifiedTraces(context.Context, *connect.Request[v1.QueryUnifiedTracesRequest]) (*connect.Response[v1.QueryUnifiedTracesResponse], error)
	QueryUnifiedMetrics(context.Context, *connect.Request[v1.QueryUnifiedMetricsRequest]) (*connect.Response[v1.QueryUnifiedMetricsResponse], error)
	QueryUnifiedLogs(context.Context, *connect.Request[v1.QueryUnifiedLogsRequest]) (*connect.Response[v1.QueryUnifiedLogsResponse], error)
	// Focused query interface (RFD 076) - focused queries for scripting and CLI.
	ListServices(context.Context, *connect.Request[v1.ListServicesRequest]) (*connect.Response[v1.ListServicesResponse], error)
	GetMetricPercentile(context.Context, *connect.Request[v1.GetMetricPercentileRequest]) (*connect.Response[v1.GetMetricPercentileResponse], error)
	ExecuteQuery(context.Context, *connect.Request[v1.ExecuteQueryRequest]) (*connect.Response[v1.ExecuteQueryResponse], error)
	// Execute an MCP tool and return the result.
	CallTool(context.Context, *connect.Request[v1.CallToolRequest]) (*connect.Response[v1.CallToolResponse], error)
	// Execute an MCP tool with streaming (bidirectional).
	StreamTool(context.Context, *connect.BidiStream[v1.StreamToolRequest, v1.StreamToolResponse]) error
	// List available MCP tools.
	ListTools(context.Context, *connect.Request[v1.ListToolsRequest]) (*connect.Response[v1.ListToolsResponse], error)
	// Request a client certificate using a bootstrap token.
	RequestCertificate(context.Context, *connect.Request[v1.RequestCertificateRequest]) (*connect.Response[v1.RequestCertificateResponse], error)
	// Revoke an issued certificate.
	RevokeCertificate(context.Context, *connect.Request[v1.RevokeCertificateRequest]) (*connect.Response[v1.RevokeCertificateResponse], error)
}

// NewColonyServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewColonyServiceHandler(svc ColonyServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	colonyServiceMethods := v1.File_coral_colony_v1_colony_proto.Services().ByName("ColonyService").Methods()
	colonyServiceGetStatusHandler := connect.NewUnaryHandler(
		ColonyServiceGetStatusProcedure,
		svc.GetStatus,
		connect.WithSchema(colonyServiceMethods.ByName("GetStatus")),
		connect.WithHandlerOptions(opts...),
	)
	colonyServiceListAgentsHandler := connect.NewUnaryHandler(
		ColonyServiceListAgentsProcedure,
		svc.ListAgents,
		connect.WithSchema(colonyServiceMethods.ByName("ListAgents")),
		connect.WithHandlerOptions(opts...),
	)
	colonyServiceGetTopologyHandler := connect.NewUnaryHandler(
		ColonyServiceGetTopologyProcedure,
		svc.GetTopology,
		connect.WithSchema(colonyServiceMethods.ByName("GetTopology")),
		connect.WithHandlerOptions(opts...),
	)
	colonyServiceQueryUnifiedSummaryHandler := connect.NewUnaryHandler(
		ColonyServiceQueryUnifiedSummaryProcedure,
		svc.QueryUnifiedSummary,
		connect.WithSchema(colonyServiceMethods.ByName("QueryUnifiedSummary")),
		connect.WithHandlerOptions(opts...),
	)
	colonyServiceQueryUnifiedTracesHandler := connect.NewUnaryHandler(
		ColonyServiceQueryUnifiedTracesProcedure,
		svc.QueryUnifiedTraces,
		connect.WithSchema(colonyServiceMethods.ByName("QueryUnifiedTraces")),
		connect.WithHandlerOptions(opts...),
	)
	colonyServiceQueryUnifiedMetricsHandler := connect.NewUnaryHandler(
		ColonyServiceQueryUnifiedMetricsProcedure,
		svc.QueryUnifiedMetrics,
		connect.WithSchema(colonyServiceMethods.ByName("QueryUnifiedMetrics")),
		connect.WithHandlerOptions(opts...),
	)
	colonyServiceQueryUnifiedLogsHandler := connect.NewUnaryHandler(
		ColonyServiceQueryUnifiedLogsProcedure,
		svc.QueryUnifiedLogs,
		connect.WithSchema(colonyServiceMethods.ByName("QueryUnifiedLogs")),
		connect.WithHandlerOptions(opts...),
	)
	colonyServiceListServicesHandler := connect.NewUnaryHandler(
		ColonyServiceListServicesProcedure,
		svc.ListServices,
		connect.WithSchema(colonyServiceMethods.ByName("ListServices")),
		connect.WithHandlerOptions(opts...),
	)
	colonyServiceGetMetricPercentileHandler := connect.NewUnaryHandler(
		ColonyServiceGetMetricPercentileProcedure,
		svc.GetMetricPercentile,
		connect.WithSchema(colonyServiceMethods.ByName("GetMetricPercentile")),
		connect.WithHandlerOptions(opts...),
	)
	colonyServiceExecuteQueryHandler := connect.NewUnaryHandler(
		ColonyServiceExecuteQueryProcedure,
		svc.ExecuteQuery,
		connect.WithSchema(colonyServiceMethods.ByName("ExecuteQuery")),
		connect.WithHandlerOptions(opts...),
	)
	colonyServiceCallToolHandler := connect.NewUnaryHandler(
		ColonyServiceCallToolProcedure,
		svc.CallTool,
		connect.WithSchema(colonyServiceMethods.ByName("CallTool")),
		connect.WithHandlerOptions(opts...),
	)
	colonyServiceStreamToolHandler := connect.NewBidiStreamHandler(
		ColonyServiceStreamToolProcedure,
		svc.StreamTool,
		connect.WithSchema(colonyServiceMethods.ByName("StreamTool")),
		connect.WithHandlerOptions(opts...),
	)
	colonyServiceListToolsHandler := connect.NewUnaryHandler(
		ColonyServiceListToolsProcedure,
		svc.ListTools,
		connect.WithSchema(colonyServiceMethods.ByName("ListTools")),
		connect.WithHandlerOptions(opts...),
	)
	colonyServiceRequestCertificateHandler := connect.NewUnaryHandler(
		ColonyServiceRequestCertificateProcedure,
		svc.RequestCertificate,
		connect.WithSchema(colonyServiceMethods.ByName("RequestCertificate")),
		connect.WithHandlerOptions(opts...),
	)
	colonyServiceRevokeCertificateHandler := connect.NewUnaryHandler(
		ColonyServiceRevokeCertificateProcedure,
		svc.RevokeCertificate,
		connect.WithSchema(colonyServiceMethods.ByName("RevokeCertificate")),
		connect.WithHandlerOptions(opts...),
	)
	return "/coral.colony.v1.ColonyService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ColonyServiceGetStatusProcedure:
			colonyServiceGetStatusHandler.ServeHTTP(w, r)
		case ColonyServiceListAgentsProcedure:
			colonyServiceListAgentsHandler.ServeHTTP(w, r)
		case ColonyServiceGetTopologyProcedure:
			colonyServiceGetTopologyHandler.ServeHTTP(w, r)
		case ColonyServiceQueryUnifiedSummaryProcedure:
			colonyServiceQueryUnifiedSummaryHandler.ServeHTTP(w, r)
		case ColonyServiceQueryUnifiedTracesProcedure:
			colonyServiceQueryUnifiedTracesHandler.ServeHTTP(w, r)
		case ColonyServiceQueryUnifiedMetricsProcedure:
			colonyServiceQueryUnifiedMetricsHandler.ServeHTTP(w, r)
		case ColonyServiceQueryUnifiedLogsProcedure:
			colonyServiceQueryUnifiedLogsHandler.ServeHTTP(w, r)
		case ColonyServiceListServicesProcedure:
			colonyServiceListServicesHandler.ServeHTTP(w, r)
		case ColonyServiceGetMetricPercentileProcedure:
			colonyServiceGetMetricPercentileHandler.ServeHTTP(w, r)
		case ColonyServiceExecuteQueryProcedure:
			colonyServiceExecuteQueryHandler.ServeHTTP(w, r)
		case ColonyServiceCallToolProcedure:
			colonyServiceCallToolHandler.ServeHTTP(w, r)
		case ColonyServiceStreamToolProcedure:
			colonyServiceStreamToolHandler.ServeHTTP(w, r)
		case ColonyServiceListToolsProcedure:
			colonyServiceListToolsHandler.ServeHTTP(w, r)
		case ColonyServiceRequestCertificateProcedure:
			colonyServiceRequestCertificateHandler.ServeHTTP(w, r)
		case ColonyServiceRevokeCertificateProcedure:
			colonyServiceRevokeCertificateHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedColonyServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedColonyServiceHandler struct{}

func (UnimplementedColonyServiceHandler) GetStatus(context.Context, *connect.Request[v1.GetStatusRequest]) (*connect.Response[v1.GetStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coral.colony.v1.ColonyService.GetStatus is not implemented"))
}

func (UnimplementedColonyServiceHandler) ListAgents(context.Context, *connect.Request[v1.ListAgentsRequest]) (*connect.Response[v1.ListAgentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coral.colony.v1.ColonyService.ListAgents is not implemented"))
}

func (UnimplementedColonyServiceHandler) GetTopology(context.Context, *connect.Request[v1.GetTopologyRequest]) (*connect.Response[v1.GetTopologyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coral.colony.v1.ColonyService.GetTopology is not implemented"))
}

func (UnimplementedColonyServiceHandler) QueryUnifiedSummary(context.Context, *connect.Request[v1.QueryUnifiedSummaryRequest]) (*connect.Response[v1.QueryUnifiedSummaryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coral.colony.v1.ColonyService.QueryUnifiedSummary is not implemented"))
}

func (UnimplementedColonyServiceHandler) QueryUnifiedTraces(context.Context, *connect.Request[v1.QueryUnifiedTracesRequest]) (*connect.Response[v1.QueryUnifiedTracesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coral.colony.v1.ColonyService.QueryUnifiedTraces is not implemented"))
}

func (UnimplementedColonyServiceHandler) QueryUnifiedMetrics(context.Context, *connect.Request[v1.QueryUnifiedMetricsRequest]) (*connect.Response[v1.QueryUnifiedMetricsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coral.colony.v1.ColonyService.QueryUnifiedMetrics is not implemented"))
}

func (UnimplementedColonyServiceHandler) QueryUnifiedLogs(context.Context, *connect.Request[v1.QueryUnifiedLogsRequest]) (*connect.Response[v1.QueryUnifiedLogsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coral.colony.v1.ColonyService.QueryUnifiedLogs is not implemented"))
}

func (UnimplementedColonyServiceHandler) ListServices(context.Context, *connect.Request[v1.ListServicesRequest]) (*connect.Response[v1.ListServicesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coral.colony.v1.ColonyService.ListServices is not implemented"))
}

func (UnimplementedColonyServiceHandler) GetMetricPercentile(context.Context, *connect.Request[v1.GetMetricPercentileRequest]) (*connect.Response[v1.GetMetricPercentileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coral.colony.v1.ColonyService.GetMetricPercentile is not implemented"))
}

func (UnimplementedColonyServiceHandler) ExecuteQuery(context.Context, *connect.Request[v1.ExecuteQueryRequest]) (*connect.Response[v1.ExecuteQueryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coral.colony.v1.ColonyService.ExecuteQuery is not implemented"))
}

func (UnimplementedColonyServiceHandler) CallTool(context.Context, *connect.Request[v1.CallToolRequest]) (*connect.Response[v1.CallToolResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coral.colony.v1.ColonyService.CallTool is not implemented"))
}

func (UnimplementedColonyServiceHandler) StreamTool(context.Context, *connect.BidiStream[v1.StreamToolRequest, v1.StreamToolResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("coral.colony.v1.ColonyService.StreamTool is not implemented"))
}

func (UnimplementedColonyServiceHandler) ListTools(context.Context, *connect.Request[v1.ListToolsRequest]) (*connect.Response[v1.ListToolsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coral.colony.v1.ColonyService.ListTools is not implemented"))
}

func (UnimplementedColonyServiceHandler) RequestCertificate(context.Context, *connect.Request[v1.RequestCertificateRequest]) (*connect.Response[v1.RequestCertificateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coral.colony.v1.ColonyService.RequestCertificate is not implemented"))
}

func (UnimplementedColonyServiceHandler) RevokeCertificate(context.Context, *connect.Request[v1.RevokeCertificateRequest]) (*connect.Response[v1.RevokeCertificateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coral.colony.v1.ColonyService.RevokeCertificate is not implemented"))
}
