// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: coral/colony/v1/debug.proto

package colonyv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/coral-mesh/coral/coral/colony/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DebugServiceName is the fully-qualified name of the DebugService service.
	DebugServiceName = "coral.colony.v1.DebugService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DebugServiceAttachUprobeProcedure is the fully-qualified name of the DebugService's AttachUprobe
	// RPC.
	DebugServiceAttachUprobeProcedure = "/coral.colony.v1.DebugService/AttachUprobe"
	// DebugServiceDetachUprobeProcedure is the fully-qualified name of the DebugService's DetachUprobe
	// RPC.
	DebugServiceDetachUprobeProcedure = "/coral.colony.v1.DebugService/DetachUprobe"
	// DebugServiceQueryUprobeEventsProcedure is the fully-qualified name of the DebugService's
	// QueryUprobeEvents RPC.
	DebugServiceQueryUprobeEventsProcedure = "/coral.colony.v1.DebugService/QueryUprobeEvents"
	// DebugServiceListDebugSessionsProcedure is the fully-qualified name of the DebugService's
	// ListDebugSessions RPC.
	DebugServiceListDebugSessionsProcedure = "/coral.colony.v1.DebugService/ListDebugSessions"
	// DebugServiceTraceRequestPathProcedure is the fully-qualified name of the DebugService's
	// TraceRequestPath RPC.
	DebugServiceTraceRequestPathProcedure = "/coral.colony.v1.DebugService/TraceRequestPath"
	// DebugServiceGetDebugResultsProcedure is the fully-qualified name of the DebugService's
	// GetDebugResults RPC.
	DebugServiceGetDebugResultsProcedure = "/coral.colony.v1.DebugService/GetDebugResults"
	// DebugServiceQueryFunctionsProcedure is the fully-qualified name of the DebugService's
	// QueryFunctions RPC.
	DebugServiceQueryFunctionsProcedure = "/coral.colony.v1.DebugService/QueryFunctions"
	// DebugServiceProfileFunctionsProcedure is the fully-qualified name of the DebugService's
	// ProfileFunctions RPC.
	DebugServiceProfileFunctionsProcedure = "/coral.colony.v1.DebugService/ProfileFunctions"
	// DebugServiceProfileCPUProcedure is the fully-qualified name of the DebugService's ProfileCPU RPC.
	DebugServiceProfileCPUProcedure = "/coral.colony.v1.DebugService/ProfileCPU"
)

// DebugServiceClient is a client for the coral.colony.v1.DebugService service.
type DebugServiceClient interface {
	// Start uprobe debug session.
	AttachUprobe(context.Context, *connect.Request[v1.AttachUprobeRequest]) (*connect.Response[v1.AttachUprobeResponse], error)
	// Stop uprobe session.
	DetachUprobe(context.Context, *connect.Request[v1.DetachUprobeRequest]) (*connect.Response[v1.DetachUprobeResponse], error)
	// Query uprobe events (pull-based, like Beyla).
	QueryUprobeEvents(context.Context, *connect.Request[v1.QueryUprobeEventsRequest]) (*connect.Response[v1.QueryUprobeEventsResponse], error)
	// List active debug sessions.
	ListDebugSessions(context.Context, *connect.Request[v1.ListDebugSessionsRequest]) (*connect.Response[v1.ListDebugSessionsResponse], error)
	// Trace request path (RFD 062).
	TraceRequestPath(context.Context, *connect.Request[v1.TraceRequestPathRequest]) (*connect.Response[v1.TraceRequestPathResponse], error)
	// Get aggregated debug results (RFD 062).
	GetDebugResults(context.Context, *connect.Request[v1.GetDebugResultsRequest]) (*connect.Response[v1.GetDebugResultsResponse], error)
	// Query functions with semantic search (RFD 069).
	QueryFunctions(context.Context, *connect.Request[v1.QueryFunctionsRequest]) (*connect.Response[v1.QueryFunctionsResponse], error)
	// Profile multiple functions with automatic analysis (RFD 069).
	ProfileFunctions(context.Context, *connect.Request[v1.ProfileFunctionsRequest]) (*connect.Response[v1.ProfileFunctionsResponse], error)
	// Collect CPU profile samples for a target service/pod (RFD 070).
	ProfileCPU(context.Context, *connect.Request[v1.ProfileCPURequest]) (*connect.Response[v1.ProfileCPUResponse], error)
}

// NewDebugServiceClient constructs a client for the coral.colony.v1.DebugService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDebugServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DebugServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	debugServiceMethods := v1.File_coral_colony_v1_debug_proto.Services().ByName("DebugService").Methods()
	return &debugServiceClient{
		attachUprobe: connect.NewClient[v1.AttachUprobeRequest, v1.AttachUprobeResponse](
			httpClient,
			baseURL+DebugServiceAttachUprobeProcedure,
			connect.WithSchema(debugServiceMethods.ByName("AttachUprobe")),
			connect.WithClientOptions(opts...),
		),
		detachUprobe: connect.NewClient[v1.DetachUprobeRequest, v1.DetachUprobeResponse](
			httpClient,
			baseURL+DebugServiceDetachUprobeProcedure,
			connect.WithSchema(debugServiceMethods.ByName("DetachUprobe")),
			connect.WithClientOptions(opts...),
		),
		queryUprobeEvents: connect.NewClient[v1.QueryUprobeEventsRequest, v1.QueryUprobeEventsResponse](
			httpClient,
			baseURL+DebugServiceQueryUprobeEventsProcedure,
			connect.WithSchema(debugServiceMethods.ByName("QueryUprobeEvents")),
			connect.WithClientOptions(opts...),
		),
		listDebugSessions: connect.NewClient[v1.ListDebugSessionsRequest, v1.ListDebugSessionsResponse](
			httpClient,
			baseURL+DebugServiceListDebugSessionsProcedure,
			connect.WithSchema(debugServiceMethods.ByName("ListDebugSessions")),
			connect.WithClientOptions(opts...),
		),
		traceRequestPath: connect.NewClient[v1.TraceRequestPathRequest, v1.TraceRequestPathResponse](
			httpClient,
			baseURL+DebugServiceTraceRequestPathProcedure,
			connect.WithSchema(debugServiceMethods.ByName("TraceRequestPath")),
			connect.WithClientOptions(opts...),
		),
		getDebugResults: connect.NewClient[v1.GetDebugResultsRequest, v1.GetDebugResultsResponse](
			httpClient,
			baseURL+DebugServiceGetDebugResultsProcedure,
			connect.WithSchema(debugServiceMethods.ByName("GetDebugResults")),
			connect.WithClientOptions(opts...),
		),
		queryFunctions: connect.NewClient[v1.QueryFunctionsRequest, v1.QueryFunctionsResponse](
			httpClient,
			baseURL+DebugServiceQueryFunctionsProcedure,
			connect.WithSchema(debugServiceMethods.ByName("QueryFunctions")),
			connect.WithClientOptions(opts...),
		),
		profileFunctions: connect.NewClient[v1.ProfileFunctionsRequest, v1.ProfileFunctionsResponse](
			httpClient,
			baseURL+DebugServiceProfileFunctionsProcedure,
			connect.WithSchema(debugServiceMethods.ByName("ProfileFunctions")),
			connect.WithClientOptions(opts...),
		),
		profileCPU: connect.NewClient[v1.ProfileCPURequest, v1.ProfileCPUResponse](
			httpClient,
			baseURL+DebugServiceProfileCPUProcedure,
			connect.WithSchema(debugServiceMethods.ByName("ProfileCPU")),
			connect.WithClientOptions(opts...),
		),
	}
}

// debugServiceClient implements DebugServiceClient.
type debugServiceClient struct {
	attachUprobe      *connect.Client[v1.AttachUprobeRequest, v1.AttachUprobeResponse]
	detachUprobe      *connect.Client[v1.DetachUprobeRequest, v1.DetachUprobeResponse]
	queryUprobeEvents *connect.Client[v1.QueryUprobeEventsRequest, v1.QueryUprobeEventsResponse]
	listDebugSessions *connect.Client[v1.ListDebugSessionsRequest, v1.ListDebugSessionsResponse]
	traceRequestPath  *connect.Client[v1.TraceRequestPathRequest, v1.TraceRequestPathResponse]
	getDebugResults   *connect.Client[v1.GetDebugResultsRequest, v1.GetDebugResultsResponse]
	queryFunctions    *connect.Client[v1.QueryFunctionsRequest, v1.QueryFunctionsResponse]
	profileFunctions  *connect.Client[v1.ProfileFunctionsRequest, v1.ProfileFunctionsResponse]
	profileCPU        *connect.Client[v1.ProfileCPURequest, v1.ProfileCPUResponse]
}

// AttachUprobe calls coral.colony.v1.DebugService.AttachUprobe.
func (c *debugServiceClient) AttachUprobe(ctx context.Context, req *connect.Request[v1.AttachUprobeRequest]) (*connect.Response[v1.AttachUprobeResponse], error) {
	return c.attachUprobe.CallUnary(ctx, req)
}

// DetachUprobe calls coral.colony.v1.DebugService.DetachUprobe.
func (c *debugServiceClient) DetachUprobe(ctx context.Context, req *connect.Request[v1.DetachUprobeRequest]) (*connect.Response[v1.DetachUprobeResponse], error) {
	return c.detachUprobe.CallUnary(ctx, req)
}

// QueryUprobeEvents calls coral.colony.v1.DebugService.QueryUprobeEvents.
func (c *debugServiceClient) QueryUprobeEvents(ctx context.Context, req *connect.Request[v1.QueryUprobeEventsRequest]) (*connect.Response[v1.QueryUprobeEventsResponse], error) {
	return c.queryUprobeEvents.CallUnary(ctx, req)
}

// ListDebugSessions calls coral.colony.v1.DebugService.ListDebugSessions.
func (c *debugServiceClient) ListDebugSessions(ctx context.Context, req *connect.Request[v1.ListDebugSessionsRequest]) (*connect.Response[v1.ListDebugSessionsResponse], error) {
	return c.listDebugSessions.CallUnary(ctx, req)
}

// TraceRequestPath calls coral.colony.v1.DebugService.TraceRequestPath.
func (c *debugServiceClient) TraceRequestPath(ctx context.Context, req *connect.Request[v1.TraceRequestPathRequest]) (*connect.Response[v1.TraceRequestPathResponse], error) {
	return c.traceRequestPath.CallUnary(ctx, req)
}

// GetDebugResults calls coral.colony.v1.DebugService.GetDebugResults.
func (c *debugServiceClient) GetDebugResults(ctx context.Context, req *connect.Request[v1.GetDebugResultsRequest]) (*connect.Response[v1.GetDebugResultsResponse], error) {
	return c.getDebugResults.CallUnary(ctx, req)
}

// QueryFunctions calls coral.colony.v1.DebugService.QueryFunctions.
func (c *debugServiceClient) QueryFunctions(ctx context.Context, req *connect.Request[v1.QueryFunctionsRequest]) (*connect.Response[v1.QueryFunctionsResponse], error) {
	return c.queryFunctions.CallUnary(ctx, req)
}

// ProfileFunctions calls coral.colony.v1.DebugService.ProfileFunctions.
func (c *debugServiceClient) ProfileFunctions(ctx context.Context, req *connect.Request[v1.ProfileFunctionsRequest]) (*connect.Response[v1.ProfileFunctionsResponse], error) {
	return c.profileFunctions.CallUnary(ctx, req)
}

// ProfileCPU calls coral.colony.v1.DebugService.ProfileCPU.
func (c *debugServiceClient) ProfileCPU(ctx context.Context, req *connect.Request[v1.ProfileCPURequest]) (*connect.Response[v1.ProfileCPUResponse], error) {
	return c.profileCPU.CallUnary(ctx, req)
}

// DebugServiceHandler is an implementation of the coral.colony.v1.DebugService service.
type DebugServiceHandler interface {
	// Start uprobe debug session.
	AttachUprobe(context.Context, *connect.Request[v1.AttachUprobeRequest]) (*connect.Response[v1.AttachUprobeResponse], error)
	// Stop uprobe session.
	DetachUprobe(context.Context, *connect.Request[v1.DetachUprobeRequest]) (*connect.Response[v1.DetachUprobeResponse], error)
	// Query uprobe events (pull-based, like Beyla).
	QueryUprobeEvents(context.Context, *connect.Request[v1.QueryUprobeEventsRequest]) (*connect.Response[v1.QueryUprobeEventsResponse], error)
	// List active debug sessions.
	ListDebugSessions(context.Context, *connect.Request[v1.ListDebugSessionsRequest]) (*connect.Response[v1.ListDebugSessionsResponse], error)
	// Trace request path (RFD 062).
	TraceRequestPath(context.Context, *connect.Request[v1.TraceRequestPathRequest]) (*connect.Response[v1.TraceRequestPathResponse], error)
	// Get aggregated debug results (RFD 062).
	GetDebugResults(context.Context, *connect.Request[v1.GetDebugResultsRequest]) (*connect.Response[v1.GetDebugResultsResponse], error)
	// Query functions with semantic search (RFD 069).
	QueryFunctions(context.Context, *connect.Request[v1.QueryFunctionsRequest]) (*connect.Response[v1.QueryFunctionsResponse], error)
	// Profile multiple functions with automatic analysis (RFD 069).
	ProfileFunctions(context.Context, *connect.Request[v1.ProfileFunctionsRequest]) (*connect.Response[v1.ProfileFunctionsResponse], error)
	// Collect CPU profile samples for a target service/pod (RFD 070).
	ProfileCPU(context.Context, *connect.Request[v1.ProfileCPURequest]) (*connect.Response[v1.ProfileCPUResponse], error)
}

// NewDebugServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDebugServiceHandler(svc DebugServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	debugServiceMethods := v1.File_coral_colony_v1_debug_proto.Services().ByName("DebugService").Methods()
	debugServiceAttachUprobeHandler := connect.NewUnaryHandler(
		DebugServiceAttachUprobeProcedure,
		svc.AttachUprobe,
		connect.WithSchema(debugServiceMethods.ByName("AttachUprobe")),
		connect.WithHandlerOptions(opts...),
	)
	debugServiceDetachUprobeHandler := connect.NewUnaryHandler(
		DebugServiceDetachUprobeProcedure,
		svc.DetachUprobe,
		connect.WithSchema(debugServiceMethods.ByName("DetachUprobe")),
		connect.WithHandlerOptions(opts...),
	)
	debugServiceQueryUprobeEventsHandler := connect.NewUnaryHandler(
		DebugServiceQueryUprobeEventsProcedure,
		svc.QueryUprobeEvents,
		connect.WithSchema(debugServiceMethods.ByName("QueryUprobeEvents")),
		connect.WithHandlerOptions(opts...),
	)
	debugServiceListDebugSessionsHandler := connect.NewUnaryHandler(
		DebugServiceListDebugSessionsProcedure,
		svc.ListDebugSessions,
		connect.WithSchema(debugServiceMethods.ByName("ListDebugSessions")),
		connect.WithHandlerOptions(opts...),
	)
	debugServiceTraceRequestPathHandler := connect.NewUnaryHandler(
		DebugServiceTraceRequestPathProcedure,
		svc.TraceRequestPath,
		connect.WithSchema(debugServiceMethods.ByName("TraceRequestPath")),
		connect.WithHandlerOptions(opts...),
	)
	debugServiceGetDebugResultsHandler := connect.NewUnaryHandler(
		DebugServiceGetDebugResultsProcedure,
		svc.GetDebugResults,
		connect.WithSchema(debugServiceMethods.ByName("GetDebugResults")),
		connect.WithHandlerOptions(opts...),
	)
	debugServiceQueryFunctionsHandler := connect.NewUnaryHandler(
		DebugServiceQueryFunctionsProcedure,
		svc.QueryFunctions,
		connect.WithSchema(debugServiceMethods.ByName("QueryFunctions")),
		connect.WithHandlerOptions(opts...),
	)
	debugServiceProfileFunctionsHandler := connect.NewUnaryHandler(
		DebugServiceProfileFunctionsProcedure,
		svc.ProfileFunctions,
		connect.WithSchema(debugServiceMethods.ByName("ProfileFunctions")),
		connect.WithHandlerOptions(opts...),
	)
	debugServiceProfileCPUHandler := connect.NewUnaryHandler(
		DebugServiceProfileCPUProcedure,
		svc.ProfileCPU,
		connect.WithSchema(debugServiceMethods.ByName("ProfileCPU")),
		connect.WithHandlerOptions(opts...),
	)
	return "/coral.colony.v1.DebugService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DebugServiceAttachUprobeProcedure:
			debugServiceAttachUprobeHandler.ServeHTTP(w, r)
		case DebugServiceDetachUprobeProcedure:
			debugServiceDetachUprobeHandler.ServeHTTP(w, r)
		case DebugServiceQueryUprobeEventsProcedure:
			debugServiceQueryUprobeEventsHandler.ServeHTTP(w, r)
		case DebugServiceListDebugSessionsProcedure:
			debugServiceListDebugSessionsHandler.ServeHTTP(w, r)
		case DebugServiceTraceRequestPathProcedure:
			debugServiceTraceRequestPathHandler.ServeHTTP(w, r)
		case DebugServiceGetDebugResultsProcedure:
			debugServiceGetDebugResultsHandler.ServeHTTP(w, r)
		case DebugServiceQueryFunctionsProcedure:
			debugServiceQueryFunctionsHandler.ServeHTTP(w, r)
		case DebugServiceProfileFunctionsProcedure:
			debugServiceProfileFunctionsHandler.ServeHTTP(w, r)
		case DebugServiceProfileCPUProcedure:
			debugServiceProfileCPUHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDebugServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDebugServiceHandler struct{}

func (UnimplementedDebugServiceHandler) AttachUprobe(context.Context, *connect.Request[v1.AttachUprobeRequest]) (*connect.Response[v1.AttachUprobeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coral.colony.v1.DebugService.AttachUprobe is not implemented"))
}

func (UnimplementedDebugServiceHandler) DetachUprobe(context.Context, *connect.Request[v1.DetachUprobeRequest]) (*connect.Response[v1.DetachUprobeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coral.colony.v1.DebugService.DetachUprobe is not implemented"))
}

func (UnimplementedDebugServiceHandler) QueryUprobeEvents(context.Context, *connect.Request[v1.QueryUprobeEventsRequest]) (*connect.Response[v1.QueryUprobeEventsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coral.colony.v1.DebugService.QueryUprobeEvents is not implemented"))
}

func (UnimplementedDebugServiceHandler) ListDebugSessions(context.Context, *connect.Request[v1.ListDebugSessionsRequest]) (*connect.Response[v1.ListDebugSessionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coral.colony.v1.DebugService.ListDebugSessions is not implemented"))
}

func (UnimplementedDebugServiceHandler) TraceRequestPath(context.Context, *connect.Request[v1.TraceRequestPathRequest]) (*connect.Response[v1.TraceRequestPathResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coral.colony.v1.DebugService.TraceRequestPath is not implemented"))
}

func (UnimplementedDebugServiceHandler) GetDebugResults(context.Context, *connect.Request[v1.GetDebugResultsRequest]) (*connect.Response[v1.GetDebugResultsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coral.colony.v1.DebugService.GetDebugResults is not implemented"))
}

func (UnimplementedDebugServiceHandler) QueryFunctions(context.Context, *connect.Request[v1.QueryFunctionsRequest]) (*connect.Response[v1.QueryFunctionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coral.colony.v1.DebugService.QueryFunctions is not implemented"))
}

func (UnimplementedDebugServiceHandler) ProfileFunctions(context.Context, *connect.Request[v1.ProfileFunctionsRequest]) (*connect.Response[v1.ProfileFunctionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coral.colony.v1.DebugService.ProfileFunctions is not implemented"))
}

func (UnimplementedDebugServiceHandler) ProfileCPU(context.Context, *connect.Request[v1.ProfileCPURequest]) (*connect.Response[v1.ProfileCPUResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coral.colony.v1.DebugService.ProfileCPU is not implemented"))
}
