// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package debug

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type cpu_profileStackKey struct {
	Pid           uint32
	UserStackId   int32
	KernelStackId int32
}

// loadCpu_profile returns the embedded CollectionSpec for cpu_profile.
func loadCpu_profile() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Cpu_profileBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load cpu_profile: %w", err)
	}

	return spec, err
}

// loadCpu_profileObjects loads cpu_profile and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*cpu_profileObjects
//	*cpu_profilePrograms
//	*cpu_profileMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadCpu_profileObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadCpu_profile()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// cpu_profileSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cpu_profileSpecs struct {
	cpu_profileProgramSpecs
	cpu_profileMapSpecs
}

// cpu_profileSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cpu_profileProgramSpecs struct {
	ProfileCpu *ebpf.ProgramSpec `ebpf:"profile_cpu"`
}

// cpu_profileMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cpu_profileMapSpecs struct {
	StackCounts *ebpf.MapSpec `ebpf:"stack_counts"`
	StackTraces *ebpf.MapSpec `ebpf:"stack_traces"`
}

// cpu_profileObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadCpu_profileObjects or ebpf.CollectionSpec.LoadAndAssign.
type cpu_profileObjects struct {
	cpu_profilePrograms
	cpu_profileMaps
}

func (o *cpu_profileObjects) Close() error {
	return _Cpu_profileClose(
		&o.cpu_profilePrograms,
		&o.cpu_profileMaps,
	)
}

// cpu_profileMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadCpu_profileObjects or ebpf.CollectionSpec.LoadAndAssign.
type cpu_profileMaps struct {
	StackCounts *ebpf.Map `ebpf:"stack_counts"`
	StackTraces *ebpf.Map `ebpf:"stack_traces"`
}

func (m *cpu_profileMaps) Close() error {
	return _Cpu_profileClose(
		m.StackCounts,
		m.StackTraces,
	)
}

// cpu_profilePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadCpu_profileObjects or ebpf.CollectionSpec.LoadAndAssign.
type cpu_profilePrograms struct {
	ProfileCpu *ebpf.Program `ebpf:"profile_cpu"`
}

func (p *cpu_profilePrograms) Close() error {
	return _Cpu_profileClose(
		p.ProfileCpu,
	)
}

func _Cpu_profileClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed cpu_profile_bpfeb.o
var _Cpu_profileBytes []byte
