// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package debug

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadUprobe_monitorObjects loads uprobe_monitor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*uprobe_monitorObjects
//	*uprobe_monitorPrograms
//	*uprobe_monitorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadUprobe_monitorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadUprobe_monitor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// uprobe_monitorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type uprobe_monitorSpecs struct {
	uprobe_monitorProgramSpecs
	uprobe_monitorMapSpecs
}

// uprobe_monitorSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type uprobe_monitorProgramSpecs struct {
	ProbeEntry *ebpf.ProgramSpec `ebpf:"probe_entry"`
	ProbeExit  *ebpf.ProgramSpec `ebpf:"probe_exit"`
}

// uprobe_monitorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type uprobe_monitorMapSpecs struct {
	Events     *ebpf.MapSpec `ebpf:"events"`
	StartTimes *ebpf.MapSpec `ebpf:"start_times"`
}

// uprobe_monitorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadUprobe_monitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type uprobe_monitorObjects struct {
	uprobe_monitorPrograms
	uprobe_monitorMaps
}

func (o *uprobe_monitorObjects) Close() error {
	return _Uprobe_monitorClose(
		&o.uprobe_monitorPrograms,
		&o.uprobe_monitorMaps,
	)
}

// uprobe_monitorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadUprobe_monitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type uprobe_monitorMaps struct {
	Events     *ebpf.Map `ebpf:"events"`
	StartTimes *ebpf.Map `ebpf:"start_times"`
}

func (m *uprobe_monitorMaps) Close() error {
	return _Uprobe_monitorClose(
		m.Events,
		m.StartTimes,
	)
}

// uprobe_monitorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadUprobe_monitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type uprobe_monitorPrograms struct {
	ProbeEntry *ebpf.Program `ebpf:"probe_entry"`
	ProbeExit  *ebpf.Program `ebpf:"probe_exit"`
}

func (p *uprobe_monitorPrograms) Close() error {
	return _Uprobe_monitorClose(
		p.ProbeEntry,
		p.ProbeExit,
	)
}

func _Uprobe_monitorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed uprobe_monitor_bpfel.o
var _Uprobe_monitorBytes []byte

func loadUprobe_monitor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Uprobe_monitorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load uprobe_monitor: %w", err)
	}

	return spec, err
}
