// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: coral/mesh/v1/auth.proto

package meshv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Agent authentication during registration
type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent identification
	AgentId       string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ComponentName string `protobuf:"bytes,2,opt,name=component_name,json=componentName,proto3" json:"component_name,omitempty"` // "frontend", "api", "database"
	// Authentication (RFD 002)
	ColonyId     string `protobuf:"bytes,3,opt,name=colony_id,json=colonyId,proto3" json:"colony_id,omitempty"`             // Must match colony's ID
	ColonySecret string `protobuf:"bytes,4,opt,name=colony_secret,json=colonySecret,proto3" json:"colony_secret,omitempty"` // Shared secret for auth
	// Agent metadata
	Version string            `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Labels  map[string]string `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// WireGuard (for mesh coordination)
	WireguardPubkey string `protobuf:"bytes,7,opt,name=wireguard_pubkey,json=wireguardPubkey,proto3" json:"wireguard_pubkey,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_coral_mesh_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coral_mesh_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_coral_mesh_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterRequest) GetComponentName() string {
	if x != nil {
		return x.ComponentName
	}
	return ""
}

func (x *RegisterRequest) GetColonyId() string {
	if x != nil {
		return x.ColonyId
	}
	return ""
}

func (x *RegisterRequest) GetColonySecret() string {
	if x != nil {
		return x.ColonySecret
	}
	return ""
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *RegisterRequest) GetWireguardPubkey() string {
	if x != nil {
		return x.WireguardPubkey
	}
	return ""
}

type RegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Authentication result
	Accepted bool   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason   string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // If rejected: "invalid_secret", "wrong_colony", "unauthorized"
	// Mesh assignment (if accepted)
	AssignedIp string      `protobuf:"bytes,3,opt,name=assigned_ip,json=assignedIp,proto3" json:"assigned_ip,omitempty"` // Agent's IP in WireGuard mesh (e.g., "10.100.0.42")
	MeshSubnet string      `protobuf:"bytes,4,opt,name=mesh_subnet,json=meshSubnet,proto3" json:"mesh_subnet,omitempty"` // Colony's mesh subnet (e.g., "10.100.0.0/16")
	Peers      []*PeerInfo `protobuf:"bytes,5,rep,name=peers,proto3" json:"peers,omitempty"`                             // Other agents in mesh
	// Colony info
	RegisteredAt  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_coral_mesh_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coral_mesh_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_coral_mesh_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RegisterResponse) GetAssignedIp() string {
	if x != nil {
		return x.AssignedIp
	}
	return ""
}

func (x *RegisterResponse) GetMeshSubnet() string {
	if x != nil {
		return x.MeshSubnet
	}
	return ""
}

func (x *RegisterResponse) GetPeers() []*PeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *RegisterResponse) GetRegisteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredAt
	}
	return nil
}

type PeerInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AgentId         string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ComponentName   string                 `protobuf:"bytes,2,opt,name=component_name,json=componentName,proto3" json:"component_name,omitempty"`
	MeshIp          string                 `protobuf:"bytes,3,opt,name=mesh_ip,json=meshIp,proto3" json:"mesh_ip,omitempty"`
	WireguardPubkey string                 `protobuf:"bytes,4,opt,name=wireguard_pubkey,json=wireguardPubkey,proto3" json:"wireguard_pubkey,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_coral_mesh_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_coral_mesh_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_coral_mesh_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *PeerInfo) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *PeerInfo) GetComponentName() string {
	if x != nil {
		return x.ComponentName
	}
	return ""
}

func (x *PeerInfo) GetMeshIp() string {
	if x != nil {
		return x.MeshIp
	}
	return ""
}

func (x *PeerInfo) GetWireguardPubkey() string {
	if x != nil {
		return x.WireguardPubkey
	}
	return ""
}

var File_coral_mesh_v1_auth_proto protoreflect.FileDescriptor

const file_coral_mesh_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x18coral/mesh/v1/auth.proto\x12\rcoral.mesh.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd9\x02\n" +
	"\x0fRegisterRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12%\n" +
	"\x0ecomponent_name\x18\x02 \x01(\tR\rcomponentName\x12\x1b\n" +
	"\tcolony_id\x18\x03 \x01(\tR\bcolonyId\x12#\n" +
	"\rcolony_secret\x18\x04 \x01(\tR\fcolonySecret\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12B\n" +
	"\x06labels\x18\x06 \x03(\v2*.coral.mesh.v1.RegisterRequest.LabelsEntryR\x06labels\x12)\n" +
	"\x10wireguard_pubkey\x18\a \x01(\tR\x0fwireguardPubkey\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf8\x01\n" +
	"\x10RegisterResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1f\n" +
	"\vassigned_ip\x18\x03 \x01(\tR\n" +
	"assignedIp\x12\x1f\n" +
	"\vmesh_subnet\x18\x04 \x01(\tR\n" +
	"meshSubnet\x12-\n" +
	"\x05peers\x18\x05 \x03(\v2\x17.coral.mesh.v1.PeerInfoR\x05peers\x12?\n" +
	"\rregistered_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\fregisteredAt\"\x90\x01\n" +
	"\bPeerInfo\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12%\n" +
	"\x0ecomponent_name\x18\x02 \x01(\tR\rcomponentName\x12\x17\n" +
	"\amesh_ip\x18\x03 \x01(\tR\x06meshIp\x12)\n" +
	"\x10wireguard_pubkey\x18\x04 \x01(\tR\x0fwireguardPubkey2Z\n" +
	"\vMeshService\x12K\n" +
	"\bRegister\x12\x1e.coral.mesh.v1.RegisterRequest\x1a\x1f.coral.mesh.v1.RegisterResponseB\xa4\x01\n" +
	"\x11com.coral.mesh.v1B\tAuthProtoP\x01Z.github.com/coral-io/coral/coral/mesh/v1;meshv1\xa2\x02\x03CMX\xaa\x02\rCoral.Mesh.V1\xca\x02\rCoral\\Mesh\\V1\xe2\x02\x19Coral\\Mesh\\V1\\GPBMetadata\xea\x02\x0fCoral::Mesh::V1b\x06proto3"

var (
	file_coral_mesh_v1_auth_proto_rawDescOnce sync.Once
	file_coral_mesh_v1_auth_proto_rawDescData []byte
)

func file_coral_mesh_v1_auth_proto_rawDescGZIP() []byte {
	file_coral_mesh_v1_auth_proto_rawDescOnce.Do(func() {
		file_coral_mesh_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coral_mesh_v1_auth_proto_rawDesc), len(file_coral_mesh_v1_auth_proto_rawDesc)))
	})
	return file_coral_mesh_v1_auth_proto_rawDescData
}

var file_coral_mesh_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_coral_mesh_v1_auth_proto_goTypes = []any{
	(*RegisterRequest)(nil),       // 0: coral.mesh.v1.RegisterRequest
	(*RegisterResponse)(nil),      // 1: coral.mesh.v1.RegisterResponse
	(*PeerInfo)(nil),              // 2: coral.mesh.v1.PeerInfo
	nil,                           // 3: coral.mesh.v1.RegisterRequest.LabelsEntry
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_coral_mesh_v1_auth_proto_depIdxs = []int32{
	3, // 0: coral.mesh.v1.RegisterRequest.labels:type_name -> coral.mesh.v1.RegisterRequest.LabelsEntry
	2, // 1: coral.mesh.v1.RegisterResponse.peers:type_name -> coral.mesh.v1.PeerInfo
	4, // 2: coral.mesh.v1.RegisterResponse.registered_at:type_name -> google.protobuf.Timestamp
	0, // 3: coral.mesh.v1.MeshService.Register:input_type -> coral.mesh.v1.RegisterRequest
	1, // 4: coral.mesh.v1.MeshService.Register:output_type -> coral.mesh.v1.RegisterResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_coral_mesh_v1_auth_proto_init() }
func file_coral_mesh_v1_auth_proto_init() {
	if File_coral_mesh_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coral_mesh_v1_auth_proto_rawDesc), len(file_coral_mesh_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coral_mesh_v1_auth_proto_goTypes,
		DependencyIndexes: file_coral_mesh_v1_auth_proto_depIdxs,
		MessageInfos:      file_coral_mesh_v1_auth_proto_msgTypes,
	}.Build()
	File_coral_mesh_v1_auth_proto = out.File
	file_coral_mesh_v1_auth_proto_goTypes = nil
	file_coral_mesh_v1_auth_proto_depIdxs = nil
}
