// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: coral/mesh/v1/network.proto

package meshv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MeshTelemetry contains detailed state of the mesh network interface.
type MeshTelemetry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MeshIp        string                 `protobuf:"bytes,1,opt,name=mesh_ip,json=meshIp,proto3" json:"mesh_ip,omitempty"`
	MeshSubnet    string                 `protobuf:"bytes,2,opt,name=mesh_subnet,json=meshSubnet,proto3" json:"mesh_subnet,omitempty"`
	Wireguard     *WireGuardTelemetry    `protobuf:"bytes,3,opt,name=wireguard,proto3" json:"wireguard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeshTelemetry) Reset() {
	*x = MeshTelemetry{}
	mi := &file_coral_mesh_v1_network_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshTelemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshTelemetry) ProtoMessage() {}

func (x *MeshTelemetry) ProtoReflect() protoreflect.Message {
	mi := &file_coral_mesh_v1_network_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshTelemetry.ProtoReflect.Descriptor instead.
func (*MeshTelemetry) Descriptor() ([]byte, []int) {
	return file_coral_mesh_v1_network_proto_rawDescGZIP(), []int{0}
}

func (x *MeshTelemetry) GetMeshIp() string {
	if x != nil {
		return x.MeshIp
	}
	return ""
}

func (x *MeshTelemetry) GetMeshSubnet() string {
	if x != nil {
		return x.MeshSubnet
	}
	return ""
}

func (x *MeshTelemetry) GetWireguard() *WireGuardTelemetry {
	if x != nil {
		return x.Wireguard
	}
	return nil
}

// WireGuardTelemetry contains statistics and state of the WireGuard instance.
type WireGuardTelemetry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InterfaceExists bool                   `protobuf:"varint,1,opt,name=interface_exists,json=interfaceExists,proto3" json:"interface_exists,omitempty"`
	LinkStatus      string                 `protobuf:"bytes,2,opt,name=link_status,json=linkStatus,proto3" json:"link_status,omitempty"`
	Peers           []*WireGuardPeer       `protobuf:"bytes,3,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WireGuardTelemetry) Reset() {
	*x = WireGuardTelemetry{}
	mi := &file_coral_mesh_v1_network_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireGuardTelemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireGuardTelemetry) ProtoMessage() {}

func (x *WireGuardTelemetry) ProtoReflect() protoreflect.Message {
	mi := &file_coral_mesh_v1_network_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireGuardTelemetry.ProtoReflect.Descriptor instead.
func (*WireGuardTelemetry) Descriptor() ([]byte, []int) {
	return file_coral_mesh_v1_network_proto_rawDescGZIP(), []int{1}
}

func (x *WireGuardTelemetry) GetInterfaceExists() bool {
	if x != nil {
		return x.InterfaceExists
	}
	return false
}

func (x *WireGuardTelemetry) GetLinkStatus() string {
	if x != nil {
		return x.LinkStatus
	}
	return ""
}

func (x *WireGuardTelemetry) GetPeers() []*WireGuardPeer {
	if x != nil {
		return x.Peers
	}
	return nil
}

// WireGuardPeer represents a connected peer within the mesh.
type WireGuardPeer struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PublicKey         string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Endpoint          string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	RxBytes           int64                  `protobuf:"varint,3,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	TxBytes           int64                  `protobuf:"varint,4,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	LastHandshakeTime string                 `protobuf:"bytes,5,opt,name=last_handshake_time,json=lastHandshakeTime,proto3" json:"last_handshake_time,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WireGuardPeer) Reset() {
	*x = WireGuardPeer{}
	mi := &file_coral_mesh_v1_network_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireGuardPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireGuardPeer) ProtoMessage() {}

func (x *WireGuardPeer) ProtoReflect() protoreflect.Message {
	mi := &file_coral_mesh_v1_network_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireGuardPeer.ProtoReflect.Descriptor instead.
func (*WireGuardPeer) Descriptor() ([]byte, []int) {
	return file_coral_mesh_v1_network_proto_rawDescGZIP(), []int{2}
}

func (x *WireGuardPeer) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *WireGuardPeer) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *WireGuardPeer) GetRxBytes() int64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *WireGuardPeer) GetTxBytes() int64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

func (x *WireGuardPeer) GetLastHandshakeTime() string {
	if x != nil {
		return x.LastHandshakeTime
	}
	return ""
}

var File_coral_mesh_v1_network_proto protoreflect.FileDescriptor

const file_coral_mesh_v1_network_proto_rawDesc = "" +
	"\n" +
	"\x1bcoral/mesh/v1/network.proto\x12\rcoral.mesh.v1\"\x8a\x01\n" +
	"\rMeshTelemetry\x12\x17\n" +
	"\amesh_ip\x18\x01 \x01(\tR\x06meshIp\x12\x1f\n" +
	"\vmesh_subnet\x18\x02 \x01(\tR\n" +
	"meshSubnet\x12?\n" +
	"\twireguard\x18\x03 \x01(\v2!.coral.mesh.v1.WireGuardTelemetryR\twireguard\"\x94\x01\n" +
	"\x12WireGuardTelemetry\x12)\n" +
	"\x10interface_exists\x18\x01 \x01(\bR\x0finterfaceExists\x12\x1f\n" +
	"\vlink_status\x18\x02 \x01(\tR\n" +
	"linkStatus\x122\n" +
	"\x05peers\x18\x03 \x03(\v2\x1c.coral.mesh.v1.WireGuardPeerR\x05peers\"\xb0\x01\n" +
	"\rWireGuardPeer\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12\x19\n" +
	"\brx_bytes\x18\x03 \x01(\x03R\arxBytes\x12\x19\n" +
	"\btx_bytes\x18\x04 \x01(\x03R\atxBytes\x12.\n" +
	"\x13last_handshake_time\x18\x05 \x01(\tR\x11lastHandshakeTimeB\xa9\x01\n" +
	"\x11com.coral.mesh.v1B\fNetworkProtoP\x01Z0github.com/coral-mesh/coral/coral/mesh/v1;meshv1\xa2\x02\x03CMX\xaa\x02\rCoral.Mesh.V1\xca\x02\rCoral\\Mesh\\V1\xe2\x02\x19Coral\\Mesh\\V1\\GPBMetadata\xea\x02\x0fCoral::Mesh::V1b\x06proto3"

var (
	file_coral_mesh_v1_network_proto_rawDescOnce sync.Once
	file_coral_mesh_v1_network_proto_rawDescData []byte
)

func file_coral_mesh_v1_network_proto_rawDescGZIP() []byte {
	file_coral_mesh_v1_network_proto_rawDescOnce.Do(func() {
		file_coral_mesh_v1_network_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coral_mesh_v1_network_proto_rawDesc), len(file_coral_mesh_v1_network_proto_rawDesc)))
	})
	return file_coral_mesh_v1_network_proto_rawDescData
}

var file_coral_mesh_v1_network_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_coral_mesh_v1_network_proto_goTypes = []any{
	(*MeshTelemetry)(nil),      // 0: coral.mesh.v1.MeshTelemetry
	(*WireGuardTelemetry)(nil), // 1: coral.mesh.v1.WireGuardTelemetry
	(*WireGuardPeer)(nil),      // 2: coral.mesh.v1.WireGuardPeer
}
var file_coral_mesh_v1_network_proto_depIdxs = []int32{
	1, // 0: coral.mesh.v1.MeshTelemetry.wireguard:type_name -> coral.mesh.v1.WireGuardTelemetry
	2, // 1: coral.mesh.v1.WireGuardTelemetry.peers:type_name -> coral.mesh.v1.WireGuardPeer
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_coral_mesh_v1_network_proto_init() }
func file_coral_mesh_v1_network_proto_init() {
	if File_coral_mesh_v1_network_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coral_mesh_v1_network_proto_rawDesc), len(file_coral_mesh_v1_network_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_coral_mesh_v1_network_proto_goTypes,
		DependencyIndexes: file_coral_mesh_v1_network_proto_depIdxs,
		MessageInfos:      file_coral_mesh_v1_network_proto_msgTypes,
	}.Build()
	File_coral_mesh_v1_network_proto = out.File
	file_coral_mesh_v1_network_proto_goTypes = nil
	file_coral_mesh_v1_network_proto_depIdxs = nil
}
