// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: coral/discovery/v1/discovery.proto

package discoveryv1connect

import (
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"

	connect "connectrpc.com/connect"
	v1 "github.com/coral-io/coral/coral/discovery/v1"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DiscoveryServiceName is the fully-qualified name of the DiscoveryService service.
	DiscoveryServiceName = "coral.discovery.v1.DiscoveryService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DiscoveryServiceRegisterColonyProcedure is the fully-qualified name of the DiscoveryService's
	// RegisterColony RPC.
	DiscoveryServiceRegisterColonyProcedure = "/coral.discovery.v1.DiscoveryService/RegisterColony"
	// DiscoveryServiceLookupColonyProcedure is the fully-qualified name of the DiscoveryService's
	// LookupColony RPC.
	DiscoveryServiceLookupColonyProcedure = "/coral.discovery.v1.DiscoveryService/LookupColony"
	// DiscoveryServiceHealthProcedure is the fully-qualified name of the DiscoveryService's Health RPC.
	DiscoveryServiceHealthProcedure = "/coral.discovery.v1.DiscoveryService/Health"
)

// DiscoveryServiceClient is a client for the coral.discovery.v1.DiscoveryService service.
type DiscoveryServiceClient interface {
	// Register or update a colony's information
	RegisterColony(context.Context, *connect.Request[v1.RegisterColonyRequest]) (*connect.Response[v1.RegisterColonyResponse], error)
	// Lookup colony information by mesh ID
	LookupColony(context.Context, *connect.Request[v1.LookupColonyRequest]) (*connect.Response[v1.LookupColonyResponse], error)
	// Health check
	Health(context.Context, *connect.Request[v1.HealthRequest]) (*connect.Response[v1.HealthResponse], error)
}

// NewDiscoveryServiceClient constructs a client for the coral.discovery.v1.DiscoveryService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDiscoveryServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DiscoveryServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	discoveryServiceMethods := v1.File_coral_discovery_v1_discovery_proto.Services().ByName("DiscoveryService").Methods()
	return &discoveryServiceClient{
		registerColony: connect.NewClient[v1.RegisterColonyRequest, v1.RegisterColonyResponse](
			httpClient,
			baseURL+DiscoveryServiceRegisterColonyProcedure,
			connect.WithSchema(discoveryServiceMethods.ByName("RegisterColony")),
			connect.WithClientOptions(opts...),
		),
		lookupColony: connect.NewClient[v1.LookupColonyRequest, v1.LookupColonyResponse](
			httpClient,
			baseURL+DiscoveryServiceLookupColonyProcedure,
			connect.WithSchema(discoveryServiceMethods.ByName("LookupColony")),
			connect.WithClientOptions(opts...),
		),
		health: connect.NewClient[v1.HealthRequest, v1.HealthResponse](
			httpClient,
			baseURL+DiscoveryServiceHealthProcedure,
			connect.WithSchema(discoveryServiceMethods.ByName("Health")),
			connect.WithClientOptions(opts...),
		),
	}
}

// discoveryServiceClient implements DiscoveryServiceClient.
type discoveryServiceClient struct {
	registerColony *connect.Client[v1.RegisterColonyRequest, v1.RegisterColonyResponse]
	lookupColony   *connect.Client[v1.LookupColonyRequest, v1.LookupColonyResponse]
	health         *connect.Client[v1.HealthRequest, v1.HealthResponse]
}

// RegisterColony calls coral.discovery.v1.DiscoveryService.RegisterColony.
func (c *discoveryServiceClient) RegisterColony(ctx context.Context, req *connect.Request[v1.RegisterColonyRequest]) (*connect.Response[v1.RegisterColonyResponse], error) {
	return c.registerColony.CallUnary(ctx, req)
}

// LookupColony calls coral.discovery.v1.DiscoveryService.LookupColony.
func (c *discoveryServiceClient) LookupColony(ctx context.Context, req *connect.Request[v1.LookupColonyRequest]) (*connect.Response[v1.LookupColonyResponse], error) {
	return c.lookupColony.CallUnary(ctx, req)
}

// Health calls coral.discovery.v1.DiscoveryService.Health.
func (c *discoveryServiceClient) Health(ctx context.Context, req *connect.Request[v1.HealthRequest]) (*connect.Response[v1.HealthResponse], error) {
	return c.health.CallUnary(ctx, req)
}

// DiscoveryServiceHandler is an implementation of the coral.discovery.v1.DiscoveryService service.
type DiscoveryServiceHandler interface {
	// Register or update a colony's information
	RegisterColony(context.Context, *connect.Request[v1.RegisterColonyRequest]) (*connect.Response[v1.RegisterColonyResponse], error)
	// Lookup colony information by mesh ID
	LookupColony(context.Context, *connect.Request[v1.LookupColonyRequest]) (*connect.Response[v1.LookupColonyResponse], error)
	// Health check
	Health(context.Context, *connect.Request[v1.HealthRequest]) (*connect.Response[v1.HealthResponse], error)
}

// NewDiscoveryServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDiscoveryServiceHandler(svc DiscoveryServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	discoveryServiceMethods := v1.File_coral_discovery_v1_discovery_proto.Services().ByName("DiscoveryService").Methods()
	discoveryServiceRegisterColonyHandler := connect.NewUnaryHandler(
		DiscoveryServiceRegisterColonyProcedure,
		svc.RegisterColony,
		connect.WithSchema(discoveryServiceMethods.ByName("RegisterColony")),
		connect.WithHandlerOptions(opts...),
	)
	discoveryServiceLookupColonyHandler := connect.NewUnaryHandler(
		DiscoveryServiceLookupColonyProcedure,
		svc.LookupColony,
		connect.WithSchema(discoveryServiceMethods.ByName("LookupColony")),
		connect.WithHandlerOptions(opts...),
	)
	discoveryServiceHealthHandler := connect.NewUnaryHandler(
		DiscoveryServiceHealthProcedure,
		svc.Health,
		connect.WithSchema(discoveryServiceMethods.ByName("Health")),
		connect.WithHandlerOptions(opts...),
	)
	return "/coral.discovery.v1.DiscoveryService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DiscoveryServiceRegisterColonyProcedure:
			discoveryServiceRegisterColonyHandler.ServeHTTP(w, r)
		case DiscoveryServiceLookupColonyProcedure:
			discoveryServiceLookupColonyHandler.ServeHTTP(w, r)
		case DiscoveryServiceHealthProcedure:
			discoveryServiceHealthHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDiscoveryServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDiscoveryServiceHandler struct{}

func (UnimplementedDiscoveryServiceHandler) RegisterColony(context.Context, *connect.Request[v1.RegisterColonyRequest]) (*connect.Response[v1.RegisterColonyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coral.discovery.v1.DiscoveryService.RegisterColony is not implemented"))
}

func (UnimplementedDiscoveryServiceHandler) LookupColony(context.Context, *connect.Request[v1.LookupColonyRequest]) (*connect.Response[v1.LookupColonyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coral.discovery.v1.DiscoveryService.LookupColony is not implemented"))
}

func (UnimplementedDiscoveryServiceHandler) Health(context.Context, *connect.Request[v1.HealthRequest]) (*connect.Response[v1.HealthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("coral.discovery.v1.DiscoveryService.Health is not implemented"))
}
